### ISSUE TITLE
Xdebug fails install

### ISSUE THREAD

**Issue by upchuk** [geerlingguy/drupal-vm#1776] opened 2018-05-17 16:22 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/upchuk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (latest)

### Full console output

```
TASK [geerlingguy.php-xdebug : Build Xdebug.] **********************************
changed: [drupalvm] => (item=phpize)
failed: [drupalvm] (item=./configure) => {"changed": true, "cmd": "./configure", "delta": "0:00:00.557990", "end": "2018-05-17 16:11:38.571881", "item": "./configure", "msg": "non-zero return code", "rc": 1, "start": "2018-05-17 16:11:38.013891", "stderr": "configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.\nconfigure: error: not supported. Need a PHP version >= 7.0.0 and < 7.3.0 (found 5.6.36-1+ubuntu14.04.1+deb.sury.org+1)", "stderr_lines": ["configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.", "configure: error: not supported. Need a PHP version >= 7.0.0 and < 7.3.0 (found 5.6.36-1+ubuntu14.04.1+deb.sury.org+1)"], "stdout": "checking for grep that handles long lines and -e... /bin/grep\nchecking for egrep... /bin/grep -E\nchecking for a sed that does not truncate output... /bin/sed\nchecking for cc... cc\nchecking whether the C compiler works... yes\nchecking for C compiler default output file name... a.out\nchecking for suffix of executables... \nchecking whether we are cross compiling... no\nchecking for suffix of object files... o\nchecking whether we are using the GNU C compiler... yes\nchecking whether cc accepts -g... yes\nchecking for cc option to accept ISO C89... none needed\nchecking how to run the C preprocessor... cc -E\nchecking for icc... no\nchecking for suncc... no\nchecking whether cc understands -c and -o together... yes\nchecking for system library directory... lib\nchecking if compiler supports -R... no\nchecking if compiler supports -Wl,-rpath,... yes\nchecking build system type... x86_64-unknown-linux-gnu\nchecking host system type... x86_64-unknown-linux-gnu\nchecking target system type... x86_64-unknown-linux-gnu\nchecking for PHP prefix... /usr\nchecking for PHP includes... -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib\nchecking for PHP extension directory... /usr/lib/php/20131226\nchecking for PHP installed headers prefix... /usr/include/php/20131226\nchecking if debug is enabled... no\nchecking if zts is enabled... no\nchecking for re2c... no\nchecking for gawk... no\nchecking for nawk... nawk\nchecking if nawk is broken... no\nchecking whether to enable Xdebug support... yes, shared\nchecking whether to enable Xdebug developer build flags... no\nchecking Check for supported PHP versions... ", "stdout_lines": ["checking for grep that handles long lines and -e... /bin/grep", "checking for egrep... /bin/grep -E", "checking for a sed that does not truncate output... /bin/sed", "checking for cc... cc", "checking whether the C compiler works... yes", "checking for C compiler default output file name... a.out", "checking for suffix of executables... ", "checking whether we are cross compiling... no", "checking for suffix of object files... o", "checking whether we are using the GNU C compiler... yes", "checking whether cc accepts -g... yes", "checking for cc option to accept ISO C89... none needed", "checking how to run the C preprocessor... cc -E", "checking for icc... no", "checking for suncc... no", "checking whether cc understands -c and -o together... yes", "checking for system library directory... lib", "checking if compiler supports -R... no", "checking if compiler supports -Wl,-rpath,... yes", "checking build system type... x86_64-unknown-linux-gnu", "checking host system type... x86_64-unknown-linux-gnu", "checking target system type... x86_64-unknown-linux-gnu", "checking for PHP prefix... /usr", "checking for PHP includes... -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib", "checking for PHP extension directory... /usr/lib/php/20131226", "checking for PHP installed headers prefix... /usr/include/php/20131226", "checking if debug is enabled... no", "checking if zts is enabled... no", "checking for re2c... no", "checking for gawk... no", "checking for nawk... nawk", "checking if nawk is broken... no", "checking whether to enable Xdebug support... yes, shared", "checking whether to enable Xdebug developer build flags... no", "checking Check for supported PHP versions... "]}
failed: [drupalvm] (item=make) => {"changed": true, "cmd": "make", "delta": "0:00:00.003167", "end": "2018-05-17 16:11:38.816101", "item": "make", "msg": "non-zero return code", "rc": 2, "start": "2018-05-17 16:11:38.812934", "stderr": "make: *** No targets specified and no makefile found.  Stop.", "stderr_lines": ["make: *** No targets specified and no makefile found.  Stop."], "stdout": "", "stdout_lines": []}
```

### Summary

Trying to set up a box with Ubuntu 1404, PHP 5.6 and xdebug. But it fails the install...Any clue @geerlingguy ?

**Comment by geerlingguy** [comment] 2018-05-17 18:35
It looks like the problem is the version of XDebug you have configured is not compatible with PHP < 7.0:

```
error: not supported. Need a PHP version >= 7.0.0 and < 7.3.0 (found 5.6.361+ubuntu14.04.1+deb.sury.org+1)
```

See the note for PHP 5.6 for `php_xdebug_version` in the role documentation: https://github.com/geerlingguy/ansible-role-php-xdebug#role-variables

**Comment by upchuk** [comment] 2018-05-17 19:03
@geerlingguy Great, that worked. Thanks for the tip. Now it went further and still being tripped by 1771 :(

**Comment by geerlingguy** [comment] 2018-05-18 17:31
Awesome, closing out this issue then.

**Closed by geerlingguy** 2018-05-18 17:31 UTC
Labels: question
