### ISSUE TITLE
Can't send emails without mailhog - Host not found

### ISSUE THREAD

**Issue by adriadrop** [geerlingguy/drupal-vm#1615] opened 2017-11-21 09:42 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
Vagrant 1.9.1

### Your OS
 - **macOS** Sierra

### Full console output

```

Nov 21 09:29:16 local postfix/pickup[1491]: 0E99F281209: uid=33 from=<www-data>
Nov 21 09:29:16 local postfix/cleanup[7650]: 0E99F281209: message-id=<20171121092916.0E99F281209@local.dv.com>
Nov 21 09:29:16 local postfix/qmgr[1492]: 0E99F281209: from=<www-data@local.dv.com>, size=641, nrcpt=1 (queue active)
Nov 21 09:29:16 local postfix/smtp[7652]: 0E99F281209: to=<marko@arabba.hr>, relay=none, delay=0.02, delays=0.01/0.01/0/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=arabba.hr type=MX: Host not found, try again)
```

### Summary

When using mailhog i get emails in it and that works ok, when I remove mailhog and put 
php_sendmail_path: "/usr/sbin/sendmail -t -i" 
to use default mail service seems I cant get emails to work. I keep getting above output and I don't receive emails. 

I am wondering is there some extra DNS config needed so that VM actually sends emails?

**Comment by FinBoWa** [comment] 2017-11-21 09:51
Why debug emails to the world from the vagrant testbed? You have confirmed with mailhog the emails work so personally I wouldn't put too much effort on getting mails from your internal networks vagrant box they might get event spam blocked. 

Just make the mail delivery work on "live" staging or production servers.

**Comment by adriadrop** [comment] 2017-11-21 09:56
I tried sending email to any email that is on the same domain as this vagrant VM site which is local.dv.com and then I don't get this host unknown thing. So it seems like something is needed with configuration of mail and dns?

Nov 21 09:45:29 local postfix/pickup[1491]: 9D22A281F94: uid=33 from=<www-data>
Nov 21 09:45:29 local postfix/cleanup[7735]: 9D22A281F94: message-id=<20171121094529.9D22A281F94@local.dv.com>
Nov 21 09:45:29 local postfix/qmgr[1492]: 9D22A281F94: from=<www-data@local.dv.com>, size=644, nrcpt=1 (queue active)
Nov 21 09:45:29 local postfix/local[7737]: 9D22A281F94: to=<marko@local.dv.com>, relay=local, delay=0.02, delays=0.01/0/0/0, dsn=5.1.1, status=bounced (unknown user: "marko")
Nov 21 09:45:29 local postfix/cleanup[7735]: A0339281F99: message-id=<20171121094529.A0339281F99@local.dv.com>
Nov 21 09:45:29 local postfix/qmgr[1492]: A0339281F99: from=<>, size=2385, nrcpt=1 (queue active)
Nov 21 09:45:29 local postfix/bounce[7738]: 9D22A281F94: sender non-delivery notification: A0339281F99
Nov 21 09:45:29 local postfix/qmgr[1492]: 9D22A281F94: removed
Nov 21 09:45:29 local postfix/local[7737]: A0339281F99: to=<www-data@local.dv.com>, relay=local, delay=0, delays=0/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
Nov 21 09:45:29 local postfix/qmgr[1492]: A0339281F99: removed

**Comment by adriadrop** [comment] 2017-11-21 10:00
FinBoWa please don't assume things like that. I am working on complex system with emails going in and out, using mailgun https://www.mailgun.com/  to send emails. Having complex php libraries to receive emails from those senders and process them, so I need to have mail running locally as same as on live server.

**Comment by FinBoWa** [comment] 2017-11-21 10:15
Everyone is working on a complex system, but my suggestion is valid the important bit for your app is validated: the email gets created and send as mailhog gets it. 

As you did not give context I assumed that you might be doing unnecessary work and gave you a tip. 

Anyways: getting mails actually delivered is more a server configuration issue, not directly a Drupal Vm issue. 

Tips for fixing that your case could be

- have you checked that you can ping the domain correcly if not add a line to /etc/hosts
- use your own custom DNS servers on the box to fake mx translations if you absulutely must use "real email dns"
- stick to email addresses that actually work on the boxes. Seems that you tried but got "unknown user: "marko", is there a user called marko ??

**Comment by FinBoWa** [comment] 2017-11-21 10:34
Also if you look closely at my comment it starts with "Why debug emails to the world from the vagrant testbed?" so maybe revisiting the need for the downvote is in order on your end.

**Comment by adriadrop** [comment] 2017-11-21 11:03
I am going with this -> Expected to have email working just as on some other AMP stacks like MAMP/LAMp. So when I make change to drupalvm as suggested here
https://github.com/geerlingguy/drupal-vm/issues/364
i was hoping it would work.

But seems to me that this is not enough. I tried this on vanilla drupalvm and problem is the same so this must be some vagrant config we need to change to make this work as current config only works for mailhog. But what to change and which settings that is what I am trying to find out.

**Comment by FinBoWa** [comment] 2017-11-21 11:30
You on virtualbox? 

https://www.virtualbox.org/ticket/11540

I'd presume there is alternative fix somewhere also to changing the resolv.conf to point some where else. 

I'd suggest on debuging with `dig mx arabba.hr`, if you get a correct response in side the box, thought the server might still reject it if it can't ping it back as its in local network.

**Comment by FinBoWa** [comment] 2017-11-21 11:59
I'd argue its Drupalvms purpose to automatically fix all "vagrant/virtualbox" that don't cause issues in normal use cases. 

Using google dns can cause other issues like resolving to a ip that is not optimal for your location:

```
;; ANSWER SECTION:
www.google.com.au.      276     IN      A       216.58.203.99
;; Query time: 152 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)

ISP DNS:

;; ANSWER SECTION:
www.google.com.au.      219     IN      A       216.58.196.227
;; Query time: 37 msec
;; SERVER: 139.130.4.4#53(139.130.4.4)

```

**Comment by geerlingguy** [comment] 2017-12-22 23:19
@adriadrop - In this case, I would agree with @FinBoWa's latest suggestion—Drupal VM usually sticks to any VirtualBox/Vagrant defaults because doing otherwise often results in a lot of weird and annoying side effects.

The use case of sending live email external to Drupal VM (at least in local development environments running on VirtualBox—the prod configuration works great running on live servers on the Internet) isn't part of the core experience I'd like to support.

I have spent too many hours of my life working out email delivery issues, and I do not wish to add to that any support for Drupal VM running locally :)

**Closed by geerlingguy** 2017-12-22 23:19 UTC
