### ISSUE TITLE
PHP memory limit config value not respected for FPM on Ubuntu

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#441] opened 2016-02-16 15:41 UTC
In my config.yml, I have 256M set for memory, but Drupal reports it as 128M.

I am doing this with a fresh install of 2.2.1 of DrupalVM.

**Comment by kevinquillen** [comment] 2016-02-16 15:49
I checked the PHP role and its default is also 256M. Is it possible the PHP FPM additions has caused a change?

**Comment by oxyc** [comment] 2016-02-16 16:06
I checked my boxes and I can confirm I have the same issue. It's filed upstream already https://github.com/geerlingguy/ansible-role-php/issues/53

**Comment by geerlingguy** [comment] 2016-02-16 16:53
It's because of Debian/Ubuntu's pathing insanity. I do need to fix this sometime, but I've been going through all my roles and updating them for Galaxy 2.0 and clearing out some cobwebs... so the PHP role is a little later in that list. Help is welcome :D

**Comment by geerlingguy** [comment] 2016-02-20 05:49
This is the last issue I have on my chopping block for the next minor release of Drupal VM, so I hope to get to it upstream this weekend :)

**Comment by oxyc** [comment] 2016-02-20 20:45
I have a PR for it now https://github.com/geerlingguy/ansible-role-php/pull/83.

**Comment by geerlingguy** [comment] 2016-02-20 21:06
Thanks @oxyc - if you haven't already, I'll work more on getting it to green in an hour or two when I'm back from errands, or tonight after finishing out the day's work. It's a beautiful day in STL so doing lots of outdoor things while it's not freezing cold :)

**Comment by geerlingguy** [comment] 2016-02-20 23:12
This should now be fixed upstream; I just tagged 1.9.1 of the PHP role, and am testing with my local copy of Drupal VM. Will close this once fix is confirmed.

**Comment by geerlingguy** [comment] 2016-02-21 02:56
Tested and fixed. Found a new bug that resulted in the xdebug role, but fixed that as well, and just pushed a new tag to Galaxy. I'll be working on polishing up the 2.3.0 release soon.

**Closed by geerlingguy** 2016-02-21 02:56 UTC
Labels: bug, upstream
