### ISSUE TITLE
How to set an xdebug breakpoint in a custom drush command?

### ISSUE THREAD

**Issue by MKorostoff** [geerlingguy/drupal-vm#1001] opened 2016-11-18 18:48 UTC
### Issue Type
 - Support Request

### Your Environment
```
Vagrant 1.8.7
VirtualBox 5.1.8r111374
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** 10.12.1

### Summary

Can I get xdebug to stop on a breakpoint inside a drush command?  I'm using Drupal 8, here's what I've done so far:

1. Followed the [steps here](http://docs.drupalvm.com/en/latest/extras/xdebug/) and succefully activated a breakpoint in the browser.
2. Created a custom drush command.
3. Set a breakpoint in my custom Drush command function.
4. Invoked my custom drush command from the terminal.
5. See that xdebug pauses, but NOT at my breakpoint ([screenshot](https://monosnap.com/file/id2IelJBS1ROs6sHooOIEaykPz2UgQ.png)).
6. Hit "play" to continue execution to the next breakpoint
7. Drush hangs forever.  The breakpoint is never activated, and the code never finishes executing.

Sidenote, but I tried to rectify this by [following the steps here](https://dev.acquia.com/blog/debugging-drupal-8/debugging-drupal-8-in-phpstorm-local-cli-debugging-in-mac-os-x-acquia-dev-desktop-2-and-xdebug/06/09/2016/16706) but got the exact same results described above.

**Comment by geerlingguy** [comment] 2016-11-18 22:56
Hmm... I was just getting things set up on a new laptop yesterday—but not for drush commands. I just followed the official docs to configure Sublime Text for breakpoints in a browser session, but it's been a while since I've tried doing the same with Drush commands :/

Has anyone else debugged with drush/Xdebug lately?

**Comment by geerlingguy** [comment] 2016-11-23 21:59
Also linking to [Remote Debugging](https://xdebug.org/docs/remote) documentation, as there might be something helpful in there.

**Comment by geerlingguy** [comment] 2016-12-02 19:57
Closing for now—let me know if you're still having trouble and/or found any other resolution to this issue. It might be best to ask further questions about remote debugging with CLI commands/Drush on a forum like Drupal Answers, since I think it's a more general issue and not necessarily related to Drupal VM.

Also, if you were running VirtualBox 5.1.8, you might've hit some of it's weird networking issues. Please try upgrading to 5.1.10 and see if it's still an issue.

**Comment by MKorostoff** [comment] 2016-12-02 20:08
@geerlingguy I don't understand why this was closed.  Yes I'm still having trouble, no I have not found any resolution to this issue.  As a workaround, I created a route/controller which calls the same function as my drush command.  I can put a breakpoint in that, though it's not ideal for a number of reasons I won't get into.

This is something I do regularly with native Mac apache [following these steps](https://www.lullabot.com/articles/debugging-drush-commands-with-xdebug-and-phpstorm).  If you're suggesting that I can apply those steps are directly to the Drupal VM paradigm, I believe you, but I don't really understand how I'd do it.

**Comment by geerlingguy** [comment] 2016-12-02 20:53
@MKorostoff - I can reopen if you'd like, but as I'm not readily using this kind of debugging setup for any of my drush commands, and haven't had issues with Sublime, it's not something I'll be able to spend time helping with in the near term—it might be better on some other support forum/answer site...

I typically try to close issues that aren't necessarily bugs in Drupal VM after a couple weeks, otherwise this issue queue would have hundreds of support requests. I hate to do it, but it's the only way I can maintain the project with some sanity (and yes, I know about queue filters and such, but this project is one of over a hundred OSS projects I maintain, and even with some help, I have to keep it as trim as possible :).

**Comment by oxyc** [comment] 2016-12-10 06:02
Any chance https://github.com/drush-ops/drush/issues/1534#issuecomment-127760845 helps?

**Comment by kimkennof** [comment] 2017-01-02 11:50
FYI: I've also noticed this behavior, but when I push the "Stop" button, the Xdebug session continues on the proper thread and if I do this like, 2 times, I end up in my custom breakpoint...

**Comment by oxyc** [comment] 2017-01-31 16:16
@MKorostoff did you try increasing the number of max simultaneous connections (I noticed drush issue queue had that suggested as a fix 20+ times)? Or kimkennof's suggestion:

> FYI: I've also noticed this behavior, but when I push the "Stop" button, the Xdebug session continues on the proper thread and if I do this like, 2 times, I end up in my custom breakpoint...

If you did, and this still does not work, I might try and get PHPStorm setup to try and reproduce.

**Comment by oxyc** [comment] 2017-02-28 22:04
I'll close this as there's been no response for some time. @MKorostoff if you still have this issue and can confirm you've tried all suggestions brought fourth in this issue–feel free to reopen and I'll get PHPStorm up and running.

**Closed by oxyc** 2017-02-28 22:04 UTC
Labels: question

**Comment by michaellenahan** [comment] 2018-05-03 12:47
This is a helpful tutorial for drupal-vm, drush and xdebug on phpstorm:
https://www.appnovation.com/blog/how-i-stepped-my-way-through-failing-drush-drupal-8-migration-phpstorms-xdebug-integrationpart
https://www.appnovation.com/blog/how-i-stepped-my-way-through-failing-drush-drupal-8-migration-phpstorms-xdebug-integration
