### ISSUE TITLE
Compatibility with VirtualBox 6.0.6: Issues with nfs.

### ISSUE THREAD

**Issue by ayalon** [geerlingguy/drupal-vm#1926] opened 2019-04-30 12:14 UTC
Compatibility with Virtualbox 6.0.6:

Creating a new virtualbox with `vagrant_box: geerlingguy/ubuntu1604` works.

After creating the box, run `vagrant halt`.

If you run vagrant up, this error will appear:
`bash: line 5: setup: command not found`

**Comment by phizev** [comment] 2019-05-01 20:19
Duplicate of, or at least related to #1924 although it is closed.
I ran into the same issue with geerlingguy/ubuntu1804 on Windows, Linux and a coworker on Mac, apart from the other persons commenting there.

**Comment by cleverhoods** [comment] 2019-05-16 12:49
I got this error while trying to enable SOLR to an already provisioned machine (VirtualBox 6.0.8) on Mac (Mojave).
Downgrading to 6.0.4 solved the issue.

**Comment by ayalon** [comment] 2019-05-16 12:51
It is not related to sold. I simply only occurs on reprovisioning an existing machine.
You can easily recreate the same machine from scratch. But as soon as you reprovision, you will run into the issue.

**Comment by danepowell** [comment] 2019-05-16 16:36
Upstream issue: https://github.com/dotless-de/vagrant-vbguest/issues/278

**Comment by geerlingguy** [comment] 2019-05-16 16:44
Let's consolidate this into #1927 — closing this issue.

**Closed by geerlingguy** 2019-05-16 16:44 UTC
