### ISSUE TITLE
PHPUnit tests sometimes fail with 'Operation not permitted' or 'Directory not empty' during rmdir operation

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1491] opened 2017-07-28 13:48 UTC
- Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.16r113841
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.12.5 (16F73)

### Full console output

One run:

```
Drupal\Tests\netforum_auth\Functional\AuthenticationTest::testAdminUserUsesDrupalAuthentication
rmdir(sites/simpletest/52528722): Operation not permitted
```

Another run:

```
Drupal\Tests\netforum_auth\Functional\AuthenticationTest::testAdminUserUsesDrupalAuthentication
Exception: Warning: file_put_contents(sites/simpletest/61504822/files/php/twig/597a393cb6709_form-element.html.twig_dJcTIbdx1y7B0dbOtEyyZSSZ1/.htaccess): failed to open stream: Permission denied
Drupal\Component\PhpStorage\FileStorage->ensureDirectory()() (Line: 122)
```

### Summary

I initially [posted about this here](https://drupal.stackexchange.com/questions/242651/running-functional-test-the-actual-tests-pass-but-phpunit-throws-an-error-abou) but did not get too far. None of the suggestions worked, so I am turning to the server side gurus here.

Sometimes the test runs without producing any error, other times it produces errors like the ones above. I don't really know why. File/folder ownership looks correct and is being generated by Drupal and executed as the Apache user.

Is there something I have not done in regards to setting this up? The test extends BrowserTestBase and only has one stub for checking the current user, just to get started. Sometimes I can run it multiple times in a row without issue, other times I get multiple errors.

I am running it from PHPStorm using the remote interpreter, as written in the drupal.org docs. I even tried running from the command line with the same results.

**Comment by geerlingguy** [comment] 2017-08-01 04:15
Are you running a recent version of Drupal VM? There were some permissions changes that could help out with the default NFS mount.

Other than that, can you provide a reliable set of steps to reproduce, ideally starting from a completely fresh/empty Drupal VM installation? I have been able to successfully run and debug Honeypot's simpletests, as well as Drupal Core phpunit tests, both from the CLI and within Drupal's UI.

However, I've never tried doing this stuff through PHPStorm. And I'm wondering if that's where the weirdness lies—so many of these little IDE conveniences seem to take hours and/or days to get working correctly for one person... I don't use PHPStorm much/if at all, so I can't be of much help there.

**Comment by oxyc** [comment] 2017-09-23 01:41
Did you try it with a recent version of Drupal VM?

**Comment by wizonesolutions** [comment] 2017-12-08 12:51
This happens to me as well when running PHPUnit on the command line. Doesn't matter whether I run tests as `vagrant` or `www-data`

```
www-data@www:/var/www/drupalvm$ XDEBUG_CONFIG="remote_host=192.168.88.1 remote_enable=On" PHP_IDE_CONFIG="serverName=www.fillpdf-service.com" ./phpunit.sh web/modules/contrib/fillpdf/tests/src/Functional/PdfPopulationTest.php
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

E

Time: 1.08 minutes, Memory: 6.00MB

There was 1 error:

1) Drupal\Tests\fillpdf\Functional\PdfPopulationTest::testPdfPopulation
rmdir(sites/simpletest/24402401/files/php/twig): Directory not empty

/var/www/drupalvm/web/core/lib/Drupal/Core/File/FileSystem.php:256
/var/www/drupalvm/web/core/includes/file.inc:1196
/var/www/drupalvm/web/core/includes/file.inc:922
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/tests/Drupal/Tests/BrowserTestBase.php:508
/var/www/drupalvm/web/core/tests/Drupal/Tests/BrowserTestBase.php:519
```

Going to try updating my Drupal VM code and see if that helps.

**Comment by wizonesolutions** [comment] 2017-12-08 13:05
Pulled from repo, re-provisioned, reloaded VM. Running tests as `vagrant` (because that has always worked anyway). No luck :(

```
vagrant@www:/var/www/drupalvm$ XDEBUG_CONFIG="remote_host=192.168.88.1 remote_enable=On" PHP_IDE_CONFIG="serverName=www.fillpdf-service.com" ./phpunit.sh web/modules/contrib/fillpdf/tests/src/Functional/PdfPopulationTest.php
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

E

Time: 58.5 seconds, Memory: 6.00MB

There was 1 error:

1) Drupal\Tests\fillpdf\Functional\PdfPopulationTest::testPdfPopulation
rmdir(sites/simpletest/14743438/files/php/twig): Directory not empty

/var/www/drupalvm/web/core/lib/Drupal/Core/File/FileSystem.php:256
/var/www/drupalvm/web/core/includes/file.inc:1196
/var/www/drupalvm/web/core/includes/file.inc:922
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/includes/file.inc:918
/var/www/drupalvm/web/core/tests/Drupal/Tests/BrowserTestBase.php:508
/var/www/drupalvm/web/core/tests/Drupal/Tests/BrowserTestBase.php:519

FAILURES!
Tests: 1, Assertions: 18, Errors: 1.
```

**Comment by geerlingguy** [comment] 2018-04-24 19:06
Strange. Does it work if you run it on your Mac/workstation directly (and not in the VM)? It definitely seems permissions-related to me.

**Comment by wizonesolutions** [comment] 2018-04-24 21:15
It might have been permissions. I know I somehow got past it. It might have been a red herring for something else. I don't recall now :(

**Comment by geerlingguy** [comment] 2018-04-25 15:06
K, for now I'll close this issue—if this happens again for someone, please file a new issue, and make sure to include any step-by-step instructions for reproducing on a fresh instance of Drupal VM (sometimes I guess it can be hard with project-specific tests... but if you can reproduce it with a contrib module or core test, that would be ideal!).

**Closed by geerlingguy** 2018-04-25 15:06 UTC
Labels: question
