### ISSUE TITLE
Various issues: box download, networking, vagrant up - caused by Vagrant 1.8.7 or VirtualBox 5.1.8

### ISSUE THREAD

**Issue by liquidcms** [geerlingguy/drupal-vm#981] opened 2016-11-10 23:31 UTC
## Two major problems and their solutions

There are currently three major problems caused by VirtualBox, Vagrant, and some other recent software updates:

  - Vagrant 1.8.7 has a major bug that doesn't allow base boxes to be downloaded on macOS (any version)—<s>either downgrade to 1.8.6 or use the hack to fix 1.8.7 mentioned here: https://github.com/mitchellh/vagrant/issues/7969</s> upgrade to Vagrant 1.9.0.
  - VirtualBox 5.1.8 has some weird networking issues. It works for me (project maintainer), but some people have reported issues with proxies, content downloads, etc.—if you encounter issues, <s>downgrade to 5.1.6</s> upgrade to 5.1.10/
  - The latest versions of the `geerlingguy/*` boxes are now built to work ONLY with VirtualBox 5.1.x; they no longer support VirtualBox 5.0.x. Please upgrade, or download/remain on older versions of the boxes.

### Vagrant not able to download boxes

```
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
drupalvm: Box Provider: virtualbox
drupalvm: Box Version: >= 0
The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
vagrant login. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error:
```

### VirtualBox networking issue

I apologize that i have never used Vagrant before).. but your Quick Start does sound like this should be pretty simple:

    Install Vagrant and VirtualBox.
    Download or clone this project to your workstation.
    cd into this project directory and run vagrant up.

i did this and i get this:

D:\Users\Peter\Downloads\Drupal\geerlingguy-drupal-vm-835ffe5>vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

Any hints on how to debug this?

**Comment by avantcontra** [comment] 2016-11-11 03:42
For my case:
mac osx 10.12.1

1. Uninstall VirtualBox 5.1.8 and install 5.1.6 instead.
2. Remove and reinstall vagrant 1.8.7, and the box.
3. Before vagrant up, fix the curl bug of vagrant 1.8.7, using this:
https://github.com/mitchellh/vagrant/issues/7969

**Comment by revjtanton** [comment] 2016-11-11 14:56
I can confirm avantcontra's solution works.

**Comment by geerlingguy** [comment] 2016-11-11 15:14
The upstream fix seems to be here, in Vagrant's packaging project: https://github.com/mitchellh/vagrant-installers/pull/98 — but until Vagrant 1.8.8 is out, this will continue to be an issue :(

I'll leave this ticket open until that happens.

**Comment by liquidcms** [comment] 2016-11-11 17:06
thanks avantcontra - this worked like a charm!!

**Comment by jmevalentin** [comment] 2016-11-17 21:06
I do have VirtualBox 5.1.6 and Vagrant 1.8.6, and I've removed the embedded curl from my vagrant install as well. What else could I try? Btw, I'm on OS X 10.9.5

**Comment by geerlingguy** [comment] 2016-11-17 21:11
@jmevalentin - It looks like you've chimed in on https://github.com/geerlingguy/drupal-vm/issues/585#issuecomment-258747154 and https://github.com/geerlingguy/drupal-vm/issues/672#issuecomment-221998435 — I guess the last thing to try is completely removing your `~/.vagrant` folder and then trying to bring up the machine again.

Other than that, you'd need to see what kind of shared folder setup you're using—sometimes if someone shares the wrong folder path, weird things can happen too.

**Comment by jmevalentin** [comment] 2016-11-20 22:04
@geerlingguy #672 was an older issue I was able to resolve. #585 was the one I was looking for to continue our conversation but couldn't seem to find. As for your advice here, I deleted the ~/.vagrant.d folder but I still get the same issue. I'm not sure how shared folder setup affects anything, as I'm not sharing anything strange, and I am now trying to run the vagrant repo in a temp directory under my home directory. Is there a possibility that ownership of any system folders can affect this? I'm on a mac and wonder if it is hosed up some how. I did get it to work on a separate PC.

**Comment by geerlingguy** [comment] 2016-11-30 20:13
Vagrant 1.9.0 was released on the 28th, and it seems to have fixed the download issue. VirtualBox 5.1.10 was released last week, and it seems to have fixed its weird networking glitches.

Therefore, I will close this issue after bumping the requirements in Drupal VM.

**Closed** 2016-11-30 20:15 UTC
Labels: bug, upstream

**Comment by synprash** [comment] 2018-08-16 12:34
Changing vagrant cloud url worked for me. 
 
`export VAGRANT_SERVER_URL="https://vagrantcloud.com"`
