### ISSUE TITLE
Error generating drupal project (using composer)

### ISSUE THREAD

**Issue by ccportela** [geerlingguy/drupal-vm#1421] opened 2017-06-09 18:25 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
Vagrant 1.9.1
VirtualBox 5.1.22_Ubuntur115126
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

### Your OS
 - **Linux** (ubuntu 17.04)

### Full console output
`vagrant up` output:
https://gist.github.com/ccportela/a0c94aa23fa57e369558eef5d8ed6cdb#file-gistfile1-txt

### Summary
When composer tries to create drupal project, there is an error (sometimes Segmentation Fault, now "No such file or directory".

`vagrant provision` gives me the same output (same error).

But:
`cp example.drupal.composer.json drupal/composer.json`
`cd drupal`
`composer install`
installs drupal without errors.

Thanks in advance.

**Comment by oxyc** [comment] 2017-06-09 22:59
> jun 09 09:49:49 legolas exportfs[2111]: exportfs: incompatible duplicated export entries:
jun 09 09:49:49 legolas exportfs[2111]: exportfs:         192.168.88.4:/home/ccosta/trabajo/activo/biologiaorg/drupal-vm (0x242c) [IGNORED]

Seems you're `/etc/exports` file is out of sync. It seems to have an old entry for the same path.

**Comment by oxyc** [comment] 2017-06-09 23:08
If that doesn't help could you:

1. Delete the generated `drupal/` directory (if you have it), as it's probably corrupt.

2. Post your `config.yml`

**Comment by ccportela** [comment] 2017-06-10 06:27
Thank you very much, @oxyc! I think that these bad exportfs entries are not interfering with this problem (and... I don't find where to delete them: I deleted them from `/etc/exports` in my host machine, but these message persists).

In the test I've sent, there isn't `config.yml` file.

**Comment by oxyc** [comment] 2017-06-10 15:45
So you're only using the default configurations?

Could you post the exact error message you get, together with which task triggers it? The one you posted was cut off before the message.

**Comment by oxyc** [comment] 2017-06-10 15:47
Also note that during the provisioning of Drupal VM, a new folder `drupal/` will be created where your `Vagrantfile` is located. This is where the Drupal core files will be downloaded. If the _create composer project_ fails, you should delete this directory before trying to re-provision: `rm -rf drupal/`

**Comment by geerlingguy** [comment] 2017-06-21 04:15
@ccportela - Were you able to get the exact error message, or is this now working? If so, we can close it out, if not, please post an update here so we can help you further. Thanks!

**Comment by ccportela** [comment] 2017-06-28 09:52
Sorry, Jeff. The error persists. I'll update the issue as soon as possible. It's not a terrible one, since I can complete the installation with a roundabout. 

Thank you.

**Comment by oxyc** [comment] 2017-07-20 22:26
@ccportela are you still having issues?

**Comment by ccportela** [comment] 2017-07-21 09:34
Yes, @oxyc. I'm sorry for the delay. Here is the full process:

`git clone`
`cp default.config.yml config.yml` (change ip, machine name, hostname)
`vagrant up`

the process runs almost well, but...

`TASK [geerlingguy.drupal : Generate Drupal project with composer package.] *****
fatal: [drupalvm-test]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:45:09.327207", "end": "2017-07-21 07:36:31.532619", "failed": true, "rc": 1, "start": "2017-07-21 06:51:22.205412", "stderr": "    1/2:\tht
tp://packagist.org/p/provider-latest$1fea3db0b7f57f3e428875ad650260bf6864e24b7e6c328923f3954a11e410f1.json\n    2/2:\thttp://packagist.org/p/provider-2017-04$2f99899f7c3560d766a5ddc7973b84f8aba4766ab37b8a7f28eb56de1db77374.json\n    Finished: success: 2, skipped: 0, failure: 0, total: 2\nInstalling drupal-composer/drupal-project (8.x-dev 217da1c26ab558d8c3ea0efcf98a342c8c95d1b1)
\n  - Installing drupal-composer/drupal-project (8.x-dev 217da1c): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)         \b\b\b\b\b\b\b\b\b\nCreated project in /var/www/drupalvm/drupal\n    1/25:\thttps://packages.drupal.org/8/drupal/provider-2011-2$a18812db3baa8f681742783316a28094674399e174cf7abd25cd35622d1be856.json\n    3/
25:\thttps://packages.drupal.org/8/drupal/provider-2011-4$fb2df43f18a852f6dd236331b1a6e0ea4533fbd128121037b76c62211c83a334.json\n    3/25:\thttps://packages.drupal.org/8/drupal/provider-2012-1$9e9d9abdcc99f819f526eb73af489240b502a886169c1bab3554273b7fd7dd3a.json\n    4/25:\thttps://packages.drupal.org/8/drupal/provider-2012-2$8ec05b8e6d55c917bb7eee1eaf3d93d970a35a547de9157e6392a
62b56f75a34.json\n    5/25:\thttps://packages.drupal.org/8/drupal/provider-2012-3$fc5ac33d12d808d38ab9459138d10e7ef2019eabd668f88a10b84d8720a4f49c.json\n    6/25:\thttps://packages.drupal.org/8/drupal/provider-2013-1$f06e18d8a11453e5ed9dab54370f94545d03dced20343413c97dd5bbf57fa664.json\n    7/25:\thttps://packages.drupal.org/8/drupal/provider-2013-2$b2d8f6806661c00affa954336943a
f6af4616bbd15b5ce1d30bb67e6ca570879.json\n    8/25:\thttps://packages.drupal.org/8/drupal/provider-2013-3$edfc753198cc2ecec04c729dbf9a40c4b421866bd4857d1446759a27f5bbc77c.json\n    10/25:\thttps://packages.drupal.org/8/drupal/provider-2013-4$99aafa1c1021aa307cd48a08521e555f6a0bfa0b9725c2a78230a0f0a46a10e5.json\n    10/25:\thttps://packages.drupal.org/8/drupal/provider-2014-1$e96
f5f64218495016b093118f48c4b5913d61bb7dbdc79a3582a7d1ce4ed07c5.json\n    11/25:\thttps://packages.drupal.org/8/drupal/provider-2014-2$af4464504304a65a4f38bf838c91d226635878b9dbebf2c91384570b41564bfb.json\n    12/25:\thttps://packages.drupal.org/8/drupal/provider-2015-1$34b7b26299305b4b81220db0a4d2bfba62c195884c66dc463a9b9fefb0219cf0.json\n    13/25:\thttps://packages.drupal.org/8
/drupal/provider-2015-2$b36316a76dd95eef7fc4a536fd4d822935f6a107d109e5fec315dc63f3c12ac6.json\n    14/25:\thttps://packages.drupal.org/8/drupal/provider-2014-4$0adb330ca0caca707b548a760892f26b270c6a0a1fbd1ab3e44556aa255b7c16.json\n    15/25:\thttps://packages.drupal.org/8/drupal/provide
r-2015-3$e06d4e7c0e587871aff66babfae336c7665104a173f7f930419104b1187ffaaf.json\n    16/25:\thttps://packages.drupal.org/8/drupal/provider-2012-4$a9127a7c559a68d0cbd6a4fc4173178134e558f807112ef31cb0e638f85ca3f1.json\n    17/25:\thttps://packages.drupal.org/8/drupal/provider-2016-2$8805b3763899d8ea629705148ed9bc0e0c2da81c954f0b6a4b96ebf9f9376c7f.json\n    18/25:\thttps://packages.drupal.org/8/drupal/provider-2015-4$04c615c381a7ce59f1e6979861a569ebae58835d6b840afeb623548b0f3c69a5.json\n    19/25:\thttps://packages.drupal.org/8/drupal/provider-2011-3$2ba83ef6df61878955c94bd40036297bfdc0fb67067db4dd96702f5aa13fb1e6.json\n    20/25:\thttps://packages.drupal.org/8/drupal/provider-2016-1$a8a7a32016864f8b417fa72fa77a96e6a11d2069df455832b8bc60a588174126.json\n    21/25:\thttps://packages.drupal.org/8/drupal/provider-2016-3$dfcefc727b31ca83e0d0ab9f79660c1bfab4ef3bc01527f42d759542be11cb44.json\n    22/25:\thttps://packages.drupal.org/8/drupal/provider-2014-3$135b7ab85598d607b0a54cbc0045e94df45f2e7c5da378def28ff34d53effa2a.json\n    23/25:\thttps://packages.drupal.org/8/drupal/provider-2017-2$d8ec19357714ddf5091a649c4078a07fcd76ea8e7776f28b5bb2cda430c02370.json\n    24/25:\thttps://packages.drupal.org/8/drupal/provider-2016-4$c867d5fbd9f2219eab99fc049b29b53f1c6dddadc5e91ec21d7b247dde9b58e5.json\n    25/25:\thttps://packages.drupal.org/8/drupal/provider-2017-1$9076f8fe3ef40095a0f34745482c40a92138f14e5e4b705849d51e97a1cb2c8f.json\n    Finished: success: 25, skipped: 0, failure: 0, total: 25\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n    1/104:\thttps://codeload.github.com/sebastianbergmann/php-file-iterator/legacy.zip/3cc8f69b3028d0f96a9078e6295d86e9bf019be5\n    2/104:\thttps://codeload.github.com/sebastianbergmann/php-text-template/legacy.zip/31f8b717e51d9a2afca6c9f046f5d69fc27c8686\n    3/104:\thttps://codeload.github.com/sebastianbergmann/php-timer/legacy.zip/3dcf38ca72b158baf0bc245e9184d3fdffa9c46f\n    4/104:\thttps://codeload.github.com/sebastianbergmann/environment/legacy.zip/be2c607e43ce4c89ecd60e75c6a85c126e754aea\n    5/104:\thttps://codeload.github.com/sebastianbergmann/exporter/legacy.zip/42c4c2eec485ee3e159ec9884f95b431287edde4\n    6/104:\thttps://codeload.github.com/sebastianbergmann/php-token-stream/legacy.zip/e03f8f67534427a787e21a385a67ec3ca6978ea7\n    7/104:\thttps://codeload.github.com/doctrine/instantiator/legacy.zip/8e884e78f9f0eb1329e445619e04456e64d8051d\n    8/104:\thttps://codeload.github.com/sebastianbergmann/comparator/legacy.zip/2b7424b55f5047b47ac6e5ccb20b2aea4011d9be\n    9/104:\thttps://codeload.github.com/sebastianbergmann/diff/legacy.zip/7f066a26a962dbe58ddea9f72a4e82874a3975a4\n    10/104:\thttps://codeload.github.com/sebastianbergmann/recursion-context/legacy.zip/b19cc3298482a335a95f3016d2f8a6950f0fbcd7\n    11/104:\thttps://codeload.github.com/sebastianbergmann/version/legacy.zip/58b3a85e7999757d6ad81c787a1fbf5ff6c628c6\n    12/104:\thttps://codeload.github.com/jcalderonzumba/MinkPhantomJSDriver/legacy.zip/008f43670e94acd39273d15add1e7348eb23848d\n    13/104:\thttps://codeload.github.com/sebastianbergmann/phpunit-mock-objects/legacy.zip/ac8e7a3db35738d56ee9a76e78a4e03d97628983\n    14/104:\thttps://codeload.github.com/phpspec/prophecy/legacy.zip/93d39f1f7f9326d746203c7c056f300f7f126073\n    15/104:\thttps://codeload.github.com/sebastianbergmann/global-state/legacy.zip/bc37d50fea7d017d3d340f230811c9f1d7280af4\n    16/104:\thttps://codeload.github.com/minkphp/MinkBrowserKitDriver/legacy.zip/10e67fb4a295efcd62ea0bf16025a85ea19534fb\n    17/104:\thttps://codeload.github.com/minkphp/MinkGoutteDriver/legacy.zip/8b9ad6d2d95bc70b840d15323365f52fcdaea6ca\n    18/104:\thttps://codeload.github.com/FriendsOfPHP/Goutte/legacy.zip/db5c28f4a010b4161d507d5304e28a7ebf211638\n    19/104:\thttps://codeload.github.com/symfony/browser-kit/legacy.zip/8079a6b3668ef15cdbf73a4c7d31081abb8bb5f0\n    20/104:\thttps://codeload.github.com/mikey179/vfsStream/legacy.zip/0247f57b2245e8ad2e689d7cee754b45fbabd592\n    21/104:\thttps://codeload.github.com/pear/Console_Table/legacy.zip/64100b9ee81852f4fa17823e55d0b385a544f976\n    22/104:\thttps://codeload.github.com/jcalderonzumba/gastonjs/legacy.zip/4ff4a788d4995ae0d4b45fdcb1b76650e2eec72a\n    23/104:\thttps://codeload.github.com/phpDocumentor/ReflectionDocBlock/legacy.zip/e6a969a640b00d8daa3c66518b0405fb41ae0c4b\n    24/104:\thttps://codeload.github.com/asm89/stack-cors/legacy.zip/65ccbd455370f043c2e3b93482a3813603d68731\n    25/104:\thttps://codeload.github.com/consolidation/output-formatters/legacy.zip/3872f19517bfc9da0e14c9e5b6fe0f8c7439ea3a\n    26/104:\thttps://codeload.github.com/minkphp/Mink/legacy.zip/e6930b9c74693dff7f4e58577e1b1743399f3ff9\n    27/104:\thttps://codeload.github.com/composer/semver/legacy.zip/c7cb9a2095a074d131b65a8a0cd294479d785573\n    28/104:\thttps://codeload.github.com/sebastianbergmann/php-code-coverage/legacy.zip/eabf68b476ac7d0f73793aada060f1c1a9bf8979\n    29/104:\thttps://codeload.github.com/consolidation/annotated-command/legacy.zip/c1da3d970b230990ed22e9e5c8c309beb8cca881\n    31/104:\thttps://codeload.github.com/sebastianbergmann/phpunit/legacy.zip/46023de9a91eec7dfb06cc56cb4e260017298517\n    31/104:\thttps://codeload.github.com/doctrine/inflector/legacy.zip/90b2128806bfde671b6952ab8bea493942c1fdae\n    32/104:\thttps://codeload.github.com/egulias/EmailValidator/legacy.zip/5642614492f0ca2064c01d60cc33284cc2f731a9\n    33/104:\thttps://codeload.github.com/doctrine/cache/legacy.zip/b6f544a20f4807e81f7044d31e679ccbb1866dc3\n    34/104:\thttps://codeload.github.com/paragonie/random_compat/legacy.zip/634bae8e911eefa89c1abfbf1b66da679ac8f54d\n    35/104:\thttps://codeload.github.com/stackphp/builder/legacy.zip/59fcc9b448a8ce5e338a04c4e2e4aca893e83425\n    36/104:\thttps://codeload.github.com/symfony/polyfill-apcu/legacy.zip/2e7965b8cdfbba50d0092d3f6dca97dddec409e2\n    37/104:\thttps://codeload.github.com/Masterminds/html5-php/legacy.zip/7866e93dcf0245de22378414e0c2c7350abc45af\n    38/104:\thttps://codeload.github.com/symfony-cmf/routing/legacy.zip/fb1e7f85ff8c6866238b7e73a490a0a0243ae8ac\n    39/104:\thttps://codeload.github.com/symfony/class-loader/legacy.zip/151afda88c9e3f8b45efa2ce791c69528327e18c\n    40/104:\thttps://codeload.github.com/symfony/psr-http-message-bridge/legacy.zip/66085f246d3893cbdbcec5f5ad15ac60546cf0de\n    41/104:\thttps://codeload.github.com/njh/easyrdf/legacy.zip/acd09dfe0555fbcfa254291e433c45fdd4652566\n    42/104:\thttps://codeload.github.com/symfony/routing/legacy.zip/5cdaffed631e88c972f283bb4f9ca699f3c8bffa\n    43/104:\thttps://codeload.github.com/zendframework/zend-escaper/legacy.zip/2dcd14b61a72d8b8e27d579c6344e12c26141d4e\n    44/104:\thttps://codeload.github.com/symfony/serializer/legacy.zip/ff6bd03c458a6007b05a2c4c4199cbc3417bf074\n    45/104:\thttps://codeload.github.com/zendframework/zend-stdlib/legacy.zip/debedcfc373a293f9250cc9aa03cf121428c8e78\n    46/104:\thttps://codeload.github.com/doctrine/common/legacy.zip/930297026c8009a567ac051fd545bf6124150347\n    47/104:\thttps://codeload.github.com/drush-ops/drush/legacy.zip/a1d3ab0f1d9ce01556d70015906caaed723f7ba7\n    48/104:\thttps://codeload.github.com/symfony/polyfill-iconv/legacy.zip/ae1347fa81423b67dbc232c8c111facb367ff8b9\n    49/104:\thttps://codeload.github.com/doctrine/annotations/legacy.zip/f25c8aab83e0c3e976fd7d19875f198ccf2f7535\n    50/104:\thttps://codeload.github.com/composer/installers/legacy.zip/79ad876c7498c0bbfe7eed065b8651c93bfd6045\n    51/104:\thttps://codeload.github.com/doctrine/lexer/legacy.zip/83893c552fd2045dd78aef794c31e694c37c0b8c\n    52/104:\thttps://codeload.github.com/zendframework/zend-diactoros/legacy.zip/b03f285a333f51e58c95cce54109a4a9ed691436\n    53/104:\thttps://codeload.github.com/doctrine/collections/legacy.zip/6c1e4eef75f310ea1b3e30945e9f06e652128b8a\n    54/104:\thttps://codeload.github.com/dflydev/dflydev-dot-access-configuration/legacy.zip/ae6e7138b1d9063d343322cca63994ee1ac5161d\n    55/104:\thttps://codeload.github.com/dflydev/dflydev-dot-access-data/legacy.zip/3fbd874921ab2c041e899d044585a2ab9795df8a\n    56/104:\thttps://codeload.github.com/dflydev/dflydev-placeholder-resolver/legacy.zip/c498d0cae91b1bb36cc7d60906dab8e62bb7c356\n    57/104:\thttps://codeload.github.com/symfony/http-kernel/legacy.zip/fadab94a5a9fb8e4d59884782b20b35274ff4876\n    58/104:\thttps://codeload.github.com/hechoendrupal/drupal-console-core/legacy.zip/af7181073cd3cbd2efabe0343f0d5d24fdf02413\n    59/104:\thttps://codeload.github.com/stecman/symfony-console-completion/legacy.zip/5461d43e53092b3d3b9dbd9d999f2054730f4bbb\n    60/104:\thttps://codeload.github.com/symfony/event-dispatcher/legacy.zip/1377400fd641d7d1935981546aaef780ecd5bf6d\n    61/104:\thttps://codeload.github.com/symfony/filesystem/legacy.zip/714b1036010c354ae2b25d7f9ca27e14e265e9f2\n    62/104:\thttps://codeload.github.com/hechoendrupal/drupal-console-en/legacy.zip/63919e6f348ae2c1821952d067bc7e8f5edf6fe8\n    63/104:\thttps://codeload.github.com/symfony/process/legacy.zip/57e52a0a6a80ea0aec4fc1b785a7920a95cb88a8\n    64/104:\thttps://codeload.github.com/zendframework/zend-feed/legacy.zip/94579e805dd108683209fe14b3b5d4276de3de6e\n    65/104:\thttps://codeload.github.com/webflo/drupal-finder/legacy.zip/6ef150707aad1755d91f9b0d2108bcc16661e76b\n    66/104:\thttps://codeload.github.com/alchemy-fr/Zippy/legacy.zip/5ffdc93de0af2770d396bf433d8b2667c77277ea\n    67/104:\thttps://codeload.github.com/webmozart/path-util/legacy.zip/d939f7edc24c9a1bb9c0dee5cb05d8e859490725\n    68/104:\thttps://codeload.github.com/webmozart/assert/legacy.zip/2db61e59ff05fe5126d152bd0655c9ea113e550f\n    69/104:\thttps://codeload.github.com/symfony/translation/legacy.zip/a89af885b8c6d0142c79a02ca9cc059ed25d40d8\n    70/104:\thttps://codeload.github.com/symfony/validator/legacy.zip/6c019627f2a69b9ab2ac41fd53102148a55af564\n    71/104:\thttps://codeload.github.com/vlucas/phpdotenv/legacy.zip/3cc116adbe4b11be5ec557bf1d24dc5e3a21d18c\n    72/104:\thttps://codeload.github.com/hechoendrupal/drupal-console-extend-plugin/legacy.zip/ae2a76680f93c0fea31bbcafc6b0bcc234bb2fb4\n    73/104:\thttps://codeload.github.com/weknowinc/drupal-console-dotenv/legacy.zip/94e88646801c2f80ec2e5e66d3d8f21b0b467405\n    74/104:\thttps://codeload.github.com/symfony/finder/legacy.zip/4f4e84811004e065a3bb5ceeb1d9aa592630f9ad\n    75/104:\thttps://codeload.github.com/guzzle/guzzle/legacy.zip/f4db5a78a5ea468d4831de7f0bf9d9415e348699\n    76/104:\thttps://codeload.github.com/twigphp/Twig/legacy.zip/f878bab48edb66ad9c6ed626bf817f60c6c096ee\n    77/104:\thttps://codeload.github.com/symfony/yaml/legacy.zip/4c29dec8d489c4e37cf87ccd7166cd0b0e6a45c5\n    78/104:\thttps://codeload.github.com/guzzle/promises/legacy.zip/a59da6cf61d80060647ff4d3eb2c03a2bc694646\n    79/104:\thttps://codeload.github.com/symfony/config/legacy.zip/0b8541d18507d10204a08384640ff6df3c739ebe\n    80/104:\thttps://codeload.github.com/guzzle/psr7/legacy.zip/f5b8a8512e2b58b0071a7280e39f14f72e05d87c\n    81/104:\thttps://codeload.github.com/hechoendrupal/drupal-console/legacy.zip/a7b32fe16640d8fcba2f3e6c0802bd8fa264e70b\n    82/104:\thttps://codeload.github.com/php-fig/http-message/legacy.zip/f6561bf28d520154e4b0ec72be95418abe6d9363\n    83/104:\thttps://codeload.github.com/php-fig/log/legacy.zip/4ebe3a8bf773a19edfe0a84b6585ba3d401b724d\n    84/104:\thttps://codeload.github.com/symfony/dependency-injection/legacy.zip/db8bdcfc6f54c6968756f31c8a9ea77ac10d08d7\n    85/104:\thttps://codeload.github.com/dnoegel/php-xdg-base-dir/legacy.zip/265b8593498b997dc2d31e75b89f053b5cc9621a\n    86/104:\thttps://codeload.github.com/JakubOnderka/PHP-Console-Highlighter/legacy.zip/7daa75df45242c8d5b75a22c00a201e7954e4fb5\n    87/104:\thttps://codeload.github.com/symfony/debug/legacy.zip/8470d7701177a88edeb0cec59b44d50ef4477e9b\n    88/104:\thttps://codeload.github.com/JakubOnderka/PHP-Console-Color/legacy.zip/e0b393dacf7703fc36a4efc3df1435485197e6c1\n    89/104:\thttps://codeload.github.com/symfony/var-dumper/legacy.zip/5fe3ba6d3817ae378d141962616e048ac85ba21d\n    90/104:\thttps://codeload.github.com/bobthecow/psysh/legacy.zip/58a31cc4404c8f632d8c557bc72056af2d3a83db\n    91/104:\thttps://codeload.github.com/symfony/dom-crawler/legacy.zip/fc2c588ce376e9fe04a7b8c79e3ec62fe32d95b1\n    92/104:\thttps://codeload.github.com/symfony/expression-language/legacy.zip/2b8394d92f012fe3410e55e28c24fd90c9864a01\n    93/104:\thttps://codeload.github.com/symfony/polyfill-php54/legacy.zip/7dd1a8b9f0442273fdfeb1c4f5eaff6890a82789\n    94/104:\thttps://codeload.github.com/symfony/css-selector/legacy.zip/ba3204654efa779691fac9e948a96b4a7067e4ab\n    95/104:\thttps://codeload.github.com/symfony/polyfill-php55/legacy.zip/94566239a7720cde0820f15f0cc348ddb51ba51d\n    96/104:\thttps://codeload.github.com/ircmaxell/password_compat/legacy.zip/5c5cde8822a69545767f7c7f3058cb15ff84614c\n    97/104:\thttps://codeload.github.com/symfony/polyfill-mbstring/legacy.zip/f29dca382a6485c3cbe6379f0c61230167681937\n    98/104:\thttps://codeload.github.com/drupal-composer/drupal-scaffold/legacy.zip/1374e1031b98beb502abea3854f361304965c628\n    99/104:\thttps://codeload.github.com/cweagans/composer-patches/legacy.zip/b3036f23b73570ab5d869e345277786c8eb248a9\n    100/104:\thttps://codeload.github.com/symfony/http-foundation/legacy.zip/9ff3a0b3756ace2e3da7dded37e920ee776faa4e\n    101/104:\thttps://codeload.github.com/symfony/console/legacy.zip/46e65f8d98c9ab629bbfcc16a4ff023f61c37fb2\n    102/104:\thttps://codeload.github.com/gabordemooij/redbean/legacy.zip/d0944d7f966d7f45a0d973981fe3f64aff0050f0\n    103/104:\thttps://codeload.github.com/nikic/PHP-Parser/legacy.zip/0808939f81c1347a3c8a82a5925385a08074b0f1\n    104/104:\thttps://codeload.github.com/drupal/core/legacy.zip/7adfc8c43615258e242868a393e82971a67be51a\n    Finished: success: 104, skipped: 0, failure: 0, total: 104\nPackage operations: 104 installs, 0 updates, 0 removals\n  - Installing cweagans/composer-patches (1.6.1): Loading from cache\n  - Installing drupal-composer/drupal-scaffold (2.3.0): Loading from cache\n  - Installing composer/installers (v1.3.0): Loading from cache\n  - Installing symfony/polyfill-mbstring (v1.4.0): Loading from cache\n  - Installing ircmaxell/password-compat (v1.0.4): Loading from cache\n  - Installing symfony/polyfill-php55 (v1.4.0): Loading from cache\n  - Installing symfony/polyfill-php54 (v1.4.0): Loading from cache\n  - Installing symfony/http-foundation (v2.8.25): Loading from cache\n  - Installing symfony/expression-language (v2.8.25): Loading from cache\n  - Installing symfony/dom-crawler (v3.3.5): Loading from cache\n  - Installing symfony/css-selector (v2.8.25): Loading from cache\n  - Installing jakub-onderka/php-console-color (0.1): Loading from cache\n  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache\n  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache\n  - Installing nikic/php-parser (v3.0.6): Loading from cache\n  - Installing symfony/var-dumper (v2.8.25): Loading from cache\n  - Installing psr/log (1.0.2): Loading from cache\n  - Installing symfony/debug (v2.8.25): Loading from cache\n  - Installing symfony/console (v2.8.25): Loading from cache\n  - Installing psy/psysh (v0.8.9): Loading from cache\n  - Installing psr/http-message (1.0.1): Loading from cache\n  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache\n  - Installing guzzlehttp/promises (v1.3.1): Loading from cache\n  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache\n  - Installing gabordemooij/redbean (v4.3.4): Loading from cache\n  - Installing symfony/finder (v2.8.25): Loading from cache\n  - Installing symfony/yaml (v2.8.25): Loading from cache\n  - Installing drupal/console-extend-plugin (0.9.1): Loading from cache\n  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache\n  - Installing drupal/console-dotenv (0.3.0): Loading from cache\n  - Installing webmozart/assert (1.2.0): Loading from cache\n  - Installing webmozart/path-util (2.3.0): Loading from cache\n  - Installing webflo/drupal-finder (0.3.0): Loading from cache\n  - Installing twig/twig (v1.34.4): Loading from cache\n  - Installing symfony/translation (v2.8.25): Loading from cache\n  - Installing symfony/process (v2.8.25): Loading from cache\n  - Installing symfony/filesystem (v2.8.25): Loading from cache\n  - Installing symfony/event-dispatcher (v2.8.25): Loading from cache\n  - Installing symfony/dependency-injection (v2.8.25): Loading from cache\n  - Installing symfony/config (v2.8.25): Loading from cache\n  - Installing stecman/symfony-console-completion (0.7.0): Loading from cache\n  - Installing drupal/console-en (1.0.0-rc25): Loading from cache\n  - Installing dflydev/placeholder-resolver (v1.0.2): Loading from cache\n  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache\n  - Installing dflydev/dot-access-configuration (v1.0.2): Loading from cache\n  - Installing drupal/console-core (1.0.0-rc25): Loading from cache\n  - Installing doctrine/collections (v1.3.0): Loading from cache\n  - Installing doctrine/lexer (v1.0.1): Loading from cache\n  - Installing doctrine/annotations (v1.2.7): Loading from cache\n  - Installing alchemy/zippy (0.4.3): Loading from cache\n  - Installing drupal/console (1.0.0-rc25): Loading from cache\n  - Installing zendframework/zend-stdlib (3.1.0): Loading from cache\n  - Installing zendframework/zend-escaper (2.5.2): Loading from cache\n  - Installing zendframework/zend-feed (2.8.0): Loading from cache\n  - Installing zendframework/zend-diactoros (1.4.0): Loading from cache\n  - Installing symfony/validator (v2.8.25): Loading from cache\n  - Installing symfony/serializer (v2.8.25): Loading from cache\n  - Installing symfony/routing (v2.8.25): Loading from cache\n  - Installing symfony/psr-http-message-bridge (v1.0.0): Loading from cache\n  - Installing symfony/polyfill-iconv (v1.4.0): Loading from cache\n  - Installing symfony/http-kernel (v2.8.25): Loading from cache\n  - Installing symfony/polyfill-apcu (v1.4.0): Loading from cache\n  - Installing symfony/class-loader (v2.8.25): Loading from cache\n  - Installing symfony-cmf/routing (1.4.1): Loading from cache\n  - Installing stack/builder (v1.0.4): Loading from cache\n  - Installing paragonie/random_compat (v2.0.10): Loading from cache\n  - Installing masterminds/html5 (2.2.2): Loading from cache\n  - Installing egulias/email-validator (1.2.14): Loading from cache\n  - Installing easyrdf/easyrdf (0.9.1): Loading from cache\n  - Installing doctrine/inflector (v1.1.0): Loading from cache\n  - Installing doctrine/cache (v1.6.1): Loading from cache\n  - Installing doctrine/common (v2.7.2): Loading from cache\n  - Installing composer/semver (1.4.2): Loading from cache\n  - Installing asm89/stack-cors (1.1.0): Loading from cache\n  - Installing drupal/core (8.3.5): Loading from cache\n    Failed to download drupal/core from dist: Could not delete web/core/.nfs0000000000288c1b00000001: \n    Now trying to download from source\n  - Installing drupal/core (8.3.5): \n                                                            \n  [RuntimeException]                                        \n  Could not delete web/core/.nfs0000000000288c1b00000001:   \n                                                            \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}
`
If a do a `vagrant provision`:
`TASK [geerlingguy.drupal : Generate Drupal project with composer package.] *****
fatal: [drupalvm-test]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:22.202898", "end": "2017-07-21 07:53:55.270018", "failed": true, "rc": 1, "start": "2017-07-21 07:53:33.067120", "stderr": "    1/5:\thttp://packagist.org/p/provider-2017-07$178ded5fd6c16277a5c5620c5563550b2e41c3eec4b7f3c5a87f97f994e1cf2e.json\n    2/5:\thttp://packagist.org/p/provider-latest$0bfd401a98e0af06ad9c968b02e6daec97d7581198fc9b88a7c0acf768d911c6.json\n    3/5:\thttp://packagist.org/p/provider-2017-01$3792e93d1892cb424231a494f293ae442a0ed2c286ddcb05e49ae0be5b860d4d.json\n    4/5:\thttp://packagist.org/p/provider-2017-04$0a53e279cc2d7f6b54a8d932d5c78d2d8394e8faf18a10ce8b58f326032ef399.json\n    5/5:\thttp://packagist.org/p/provider-2016$176be54a3674fc63395c1514cd827e5ab0e16fe801415af952000038f0da14de.json\n    Finished: success: 5, skipped: 0, failure: 0, total: 5\nInstalling drupal-composer/drupal-project (8.x-dev 217da1c26ab558d8c3ea0efcf98a342c8c95d1b1)\n\n                                                             \n  [InvalidArgumentException]                                 \n  Project directory /var/www/drupalvm/drupal/ is not empty.  \n                                                             \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/home/ccosta/test-tmp/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm-test              : ok=174  changed=3    unreachable=0    failed=1   
`

(this is coherent).

If I try:

`➜  drupal-vm git:(master) ✗ rm -r drupal
➜  drupal-vm git:(master) ✗ mkdir drupal
➜  drupal-vm git:(master) ✗ vagrant provision
`
we have the same problem.

But we can get the system installed copying example.drupal.composer.json into drupal, for example, and installing drupal.

**Comment by oxyc** [comment] 2017-07-21 14:42
So this is the error message:

>  Failed to download drupal/core from dist: Could not delete web/core/.nfs0000000000288c1b00000001:
> Now trying to download from source\n - Installing drupal/core (8.3.5): \n \n [RuntimeException]
> Could not delete web/core/.nfs0000000000288c1b00000001:

The reason `vagrant provision` fails is basically that `vagrant up` failed to download Drupal earlier, and the Drupal installation had some but not all files in place. When this happens you have to delete the `drupal/` directory from your host. As a precaution, to not accidentally delete any uncommitted code, Drupal VM does not (currently) do this for you.

I have a feeling this has to do with NFS and UDP. Could you check if https://github.com/geerlingguy/drupal-vm/pull/1482 fixes it for you?

**Comment by geerlingguy** [comment] 2017-08-01 03:13
I've since merged #1482, as well as some other optimizations for Drupal project generation, so I'm going to close this issue for now. If you can still reproduce the issue, feel free to reopen with any further debugging info.

**Closed by geerlingguy** 2017-08-01 03:13 UTC
Labels: linux, question
