### ISSUE TITLE
drupalvm_user... ansible_ssh_user undefined

### ISSUE THREAD

**Issue by jonnyeom** [geerlingguy/drupal-vm#1302] opened 2017-04-17 19:01 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.18r114002
Using the geerlingguy/ubuntu1204 Box
```

### Your OS

 - **Linux** Ubuntu 16.04

### Full console output

> fatal: [mca]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined\n\nThe error appears to have been in '/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.composer/tasks/main.yml': line 37, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure composer directory exists.\n  ^ here\n"}

### Summary

On Vagrant Up, the provisioning errors out on the **Ensure composer directory exists** Task.
The error has been pasted above.

This seems to be a duplicate of an older issue, https://github.com/geerlingguy/drupal-vm/issues/533.
Any thoughts?

**Comment by oxyc** [comment] 2017-04-17 19:18
Honestly I'm quite confused as to how this could happen. Could you hack `provisioning/vars/main.yml` and change

```yaml
drupalvm_user: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
```

to

```yaml
drupalvm_user: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
```

Does that by any chance fix it?

**Comment by jonnyeom** [comment] 2017-04-18 13:12
I am still getting the error with that change.

**Comment by oxyc** [comment] 2017-04-18 13:30
Wonder if it's because you're running python3 and this is an ansible bug.

Could you install python 2 with `apt install -y python-minimal` and try again.

**Comment by jonnyeom** [comment] 2017-04-18 20:14
It seems that I already have that package installed. 
It is strange because I have successfully provisioned this box before.

**Comment by oxyc** [comment] 2017-04-18 22:53
Would you mind posting your `config.yml` and I'll try and reproduce this.

**Comment by oxyc** [comment] 2017-04-18 22:57
Could you log in to VM and check which version of ansible is installed?

https://github.com/ansible/ansible/issues/23675

**Comment by oxyc** [comment] 2017-04-18 23:08
If this is indeed the issue, you can pin a specific ansible version by adding a `Vagrantfile.local` that contains:

```rb
config.vm.provisioners[0].config.install_mode = 'pip'
config.vm.provisioners[0].config.version = '2.2.2.0'
```

**Comment by oxyc** [comment] 2017-04-18 23:29
The above fails for me.

```
     drupalvm_project: Installing Ansible...
    drupalvm_project: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:

Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
  Downloading setuptools-35.0.1-py2.py3-none-any.whl (390kB)
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Collecting appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Installing collected packages: pip, appdirs, pyparsing, six, packaging, setuptools, wheel
  Found existing installation: pip 8.1.2


Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1558k  100 1558k    0     0   767k      0  0:00:02  0:00:02 --:--:--  767k
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/tmp/tmpWdZKv8/pip.zip/pip/req/req_install.py:1025: UserWarning: Module pip was already imported from /tmp/tmpWdZKv8/pip.zip/pip/__init__.py, but /usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg is being added to sys.path
Cannot remove entries from nonexistent file /usr/local/lib/python2.7/dist-packages/easy-install.pth
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by oxyc** [comment] 2017-04-19 04:56
> Ansible 2.0 has deprecated the “ssh” from ansible_ssh_user, ansible_ssh_host, and ansible_ssh_port to become ansible_user, ansible_host, and ansible_port. If you are using a version of Ansible prior to 2.0, you should continue using the older style variables (ansible_ssh_*). These shorter variables are ignored, without warning, in older versions of Ansible.
http://docs.ansible.com/ansible/intro_inventory.html

**Ansible 2.2.2.0 `ansible_local` provisioner**

```
"ansible_ssh_user": "vagrant"
"ansible_user": "vagrant"
"ansible_user_id": "root"
"ansible_env.SUDO_USER": "vagrant"
"ansible_env.USER": "root"
```

**Ansible 2.2.1.0 `ansible` provisioner**

```
"ansible_ssh_user": "vagrant"
"ansible_user": "vagrant"
"ansible_user_id": "root"
"ansible_env.SUDO_USER": "vagrant"
"ansible_env.USER": "root"
```


**Ansible 2.3.0.0 `ansible_local` provisioner**

```
"ansible_ssh_user": "VARIABLE IS NOT DEFINED!"
"ansible_user": "VARIABLE IS NOT DEFINED!"
"ansible_user_id": "root"
"ansible_env.SUDO_USER": "vagrant"
"ansible_env.USER": "root"
```

**Ansible 2.3.0.0 `ansible` provisioner**

```
"ansible_ssh_user": "vagrant"
"ansible_user": "vagrant"
"ansible_user_id": "root"
"ansible_env.SUDO_USER": "vagrant"
"ansible_env.USER": "root"
```

So I don't think switching to `ansible_user` fixes this unfortunately. But we should do it either way as `ansible_ssh_user` is deprecated. Ran all of these on Vagrant 1.9.3

**Comment by oxyc** [comment] 2017-04-19 05:01
I'm still unable to reproduce this with `ansible_local` and 2.3.0.0 though. So maybe it's something entirely different...

**Comment by oxyc** [comment] 2017-04-19 05:19
I can confirm this bug exists when using `ansible_local` and Ubuntu 12.04. The bug does not exist on Ubuntu 16.04, nor with `ansible` as the provisioner.

The variables resolve to the same values as on 16.04.

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.3 (default, Jun 22 2015, 19:33:41) [GCC 4.6.3]
```

**Comment by jonnyeom** [comment] 2017-04-19 13:33
@oxyc I uninstalled ansible and added the `Vagrantfile.local` and provisioning was successful.

**Comment by oxyc** [comment] 2017-04-19 13:40
Great! That's some weird bug right there. I don't see a way we can fix it though. @geerlingguy should we dig deeper and see why it works with `pip` and not the ansible ppa on Ubuntu 12.04 or just point people to this issue if it comes up again?

**Comment by geerlingguy** [comment] 2017-04-20 02:41
It seems this is definitely due to a change in Ansible itself, see: https://github.com/ansible/ansible/issues/23530

**Comment by oxyc** [comment] 2017-04-20 02:46
Also why isn't undefined being caught by `|default()`?

**Comment by geerlingguy** [comment] 2017-04-20 14:06
@oxyc - It's weird... the behavior of `ansible_user` is confusing me since 2.3.0 was released. Someone mentioned using `ansible_user_id`...

**Comment by oxyc** [comment] 2017-04-20 14:12
> Someone mentioned using ansible_user_id...

That only returns `root` though.

For now, this specific bug only seem to occur when you're running Ubuntu 12.04 and `ansible_local` though (havent checked 14.04). And the fix is fairly simple: 

Uninstall ansible
```sh
vagrant ssh -c 'sudo apt-get remove ansible'
```

and add a Vagrantfile.local with

```rb
config.vm.provisioners[0].config.install_mode = 'pip'
```

**Comment by geerlingguy** [comment] 2017-04-20 14:13
That sounds like a decent enough workaround. One other question, though—shouldn't https://github.com/geerlingguy/drupal-vm/blob/2997dc9a3db2108f14ac1e3bb0b6d1540a5beef3/provisioning/vars/main.yml#L8 be `ansible_user` and not `ansible_ssh_user`?

**Comment by oxyc** [comment] 2017-04-20 14:16
> be ansible_user and not ansible_ssh_user?

Yes, even if it wont fix the but it should be updated. 

Also, if we rely on environment variables( which I think we could) this should also be fixable with them alone:

```yaml
drupalvm_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id) }}"
```

If running through sudo this would return the `vagrant` user. If the command is running directly `root` will be returned. And lastly (if no environment variables are available) `ansible_user_id` will return the current user `root`.

**Comment by geerlingguy** [comment] 2017-04-20 20:32
@oxyc - For that change... I would want to do a little extra testing to confirm it doesn't change any existing configurations; I do think relying on the env vars would be more stable than `ansible_user` type variables, judging by the inconsistency in the past few releases!

**Comment by geerlingguy** [comment] 2017-04-20 21:49
Going to tentatively mark this as fixed, as I've merged the PR. I will do a little testing really quick on prod.drupalvm.com and verify it doesn't cause any changes.

**Closed** 2017-04-20 21:49 UTC
Labels: question, upstream
