### ISSUE TITLE
MySQL server problema

### ISSUE THREAD

**Issue by vinceferro** [geerlingguy/drupal-vm#109] opened 2015-05-23 10:35 UTC
Hi, i'm trying to setup the VM using those great repo, but I'm having some problems with mysql.
Anyone has the same problem? 

Thank you!

![schermata 2015-05-23 alle 12 32 15](https://cloud.githubusercontent.com/assets/1297351/7783619/264686be-0148-11e5-8d0b-f68b4307c2ca.png)

**Comment by davidlukac** [comment] 2015-05-26 09:08
Might be related to #95 ?

**Comment by geerlingguy** [comment] 2015-05-26 15:18
Closing as a duplicate of #95 (which seems to be dancing around all the potential issues, but seems mostly environment-related :-/).

**Closed by geerlingguy** 2015-05-26 15:18 UTC

**Comment by geerlingguy** [comment] 2015-06-19 19:44
See also: https://github.com/geerlingguy/ansible-role-mysql/issues/40 — this seems to be related to a bug in Ansible 1.9.1 (if you downgrade to 1.9.0.1 and re-create your VM, it should be fixed). Hopefully Ansible 1.9.2 is released soon!
