### ISSUE TITLE
Error on Drupal install when using Makefile

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#837] opened 2016-07-30 22:42 UTC
As a first step to customizing DrupalVM for Drupal 7 instead of Drupal 8 I followed instructions at  http://docs.drupalvm.com/en/latest/deployment/drush-make/. I got the following errors.

TASK [Check if site is already installed.] *************************************
ok: [drupalvm]

TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.691820", "end": "2016-07-30 22:33:21.922578", "failed": true, "rc": 255, "start": "2016-07-30 22:33:21.230758", "stderr": "PHP Fatal error:  Uncaught Error: Class 'Drush\\Log\\Logger' not found in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc:1268\nStack trace:\n#0 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(147): _drush_create_default_logger()\n#1 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(27): drush_preflight_prepare()\n#2 /var/www/drupalvm/drupal/vendor/drush/drush/drush.php(12): drush_main()\n#3 {main}\n  thrown in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc on line 1268", "stdout": "\nFatal error: Uncaught Error: Class 'Drush\\Log\\Logger' not found in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc:1268\nStack trace:\n#0 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(147): _drush_create_default_logger()\n#1 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(27): drush_preflight_prepare()\n#2 /var/www/drupalvm/drupal/vendor/drush/drush/drush.php(12): drush_main()\n#3 {main}\n  thrown in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc on line 1268", "stdout_lines": ["", "Fatal error: Uncaught Error: Class 'Drush\\Log\\Logger' not found in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc:1268", "Stack trace:", "#0 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(147): _drush_create_default_logger()", "#1 /var/www/drupalvm/drupal/vendor/drush/drush/includes/preflight.inc(27): drush_preflight_prepare()", "#2 /var/www/drupalvm/drupal/vendor/drush/drush/drush.php(12): drush_main()", "#3 {main}", "  thrown in /var/www/drupalvm/drupal/vendor/drush/drush/includes/drush.inc on line 1268"], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=137  changed=7    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Attached is the config.yml file & drupal.make.yml files.
[drupal.make.zip](https://github.com/geerlingguy/drupal-vm/files/392129/drupal.make.zip)

What have I done wrong?

**Comment by geerlingguy** [comment] 2016-08-01 20:47
I'm testing out your config/makefile locally to see if I can reproduce the error.

**Comment by geerlingguy** [comment] 2016-08-01 21:09
@ColumbiaBlooms - It seems to build for me using the same makefile and config.yml that you attached, and http://drupalvm.dev/ loads without incident. Just to be sure (I'm trying to correlate the various issues posted in the past few days)—you're on Windows 10?

**Comment by chrisboustead** [comment] 2016-08-31 20:58
Having the same issue, ansible gets to over 100 tasks and then fails on a random task with the "NO MORE HOSTS LEFT" message.  Running on OSX.

**Comment by ColumbiaBlooms** [comment] 2016-08-31 22:07
I am using Windows 10.

**Comment by stero** [comment] 2016-09-06 17:46
Same here on OSX.

**Comment by JasonWeakley** [comment] 2016-09-29 13:27
I am getting the following error:
`TASK [Copy drush makefile into place.] *****************************************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "the file_name '/vagrant/drupal.make.yml' does not exist, or is not readable"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=135  changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

At first I thought it might have something to do trying to install a VM on shared network (because when I'm in 'My Documents' I assume I'm working locally on the hard drive, but not so). I first tried by installing Drupal 8, installed it on the hard drive and it all worked. 

Then I've been trying to install 7 on the hard drive and running into this Ansible error. Any ideas?

**Comment by geerlingguy** [comment] 2016-09-29 15:26
@JasonWeakley - Usually this means that either you didn't create the drupal.make.yml file (you need to copy it from the example make file), or the default /vagrant mount didn't mount when you ran `vagrant up`. If the former, copy that example makefile to drupal.make.yml. If the latter, run `vagrant reload --provision` to reboot the VM and remount the shared drive.

**Comment by geerlingguy** [comment] 2016-09-29 15:28
I can't reproduce this error even trying a few different settings for the Drupal 7 site, using Ubuntu 16.04, 14.04, or CentOS 7 as the base box (nor with the original config files provided by @ColumbiaBlooms).

For anyone who is still having this issue—please post the exact `config.yml` you're using, as well as the `drupal.make.yml`, and also please let me know if you get the exact same error every time you run `vagrant provision` (or if it changes), and also if you get the exact same error after running `vagrant destroy -f`, then `vagrant up` again.

For now, until I can get something reproducible, I'm going to close this and suggest you try destroying and rebuilding the VM at a minimum.

**Closed by geerlingguy** 2016-09-29 15:28 UTC
Labels: question
