### ISSUE TITLE
Cannot use Drupal Console

### ISSUE THREAD

**Issue by MKorostoff** [geerlingguy/drupal-vm#1011] opened 2016-11-23 20:59 UTC
### Issue Type
 - Bug Report / Support Request

### Environment

```
Vagrant 1.8.7
VirtualBox 5.1.8r111374
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### OS
 MacOS 10.12.1

### Full console output

```
vagrant@mysite:/var/www/mysite/docroot$ drupal cache:rebuild all

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "cache" namespace.         
                                                                  
```

![cache](https://cloud.githubusercontent.com/assets/1197335/20578501/9e9dad8c-b195-11e6-8045-6c61dbd4eec7.png)

```
vagrant@mysite:/var/www/mysite/docroot$ drupal list

                                                                                                                        
 [WARNING] In order to list all of the available commands, you should run this inside a drupal root directory.          
                                                                                                                        


                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--shellexec_output" option does not exist.         
                                                          

list [--xml] [--raw] [--format FORMAT] [-l|--uri URI] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env [ENV]] [--root [ROOT]] [--no-debug] [--learning] [-c|--generate-chain] [-i|--generate-inline] [-d|--generate-doc] [-t|--target [TARGET]] [-y|--yes] [--] <command> [<namespace>]
```

![error](https://cloud.githubusercontent.com/assets/1197335/20578518/bb889632-b195-11e6-945a-445da2e43cdf.png)

### Summary

I followed [the steps here](http://docs.drupalvm.com/en/latest/extras/drupal-console/), but produced the results shown above.

**Comment by geerlingguy** [comment] 2016-11-23 21:44
Please see:

  - https://github.com/hechoendrupal/DrupalConsole/issues/2782
  - https://github.com/hechoendrupal/DrupalConsole/issues/2754#issuecomment-251450025

I'm not sure if this is a drupal-vm issue or something upstream/project-related...

**Comment by MKorostoff** [comment] 2016-11-23 21:52
@geerlingguy thanks for the reply.  That sort of worked, now Drupal Console will run, but gives this error message:

```
[WARNING] In order to list all of the available commands, you should run this inside a drupal root directory.
```

![console](https://cloud.githubusercontent.com/assets/1197335/20579776/b6488c20-b19c-11e6-8871-2150e98d996a.png)

But the thing is I _am_ in Drupal root directory as you can see in the above screenshot.

**Comment by geerlingguy** [comment] 2016-11-23 21:54
@MKorostoff inside the VM, if you do an `ls -lah` in that directory, can you post the output? Just to make sure the files are shared in correctly and have an accessible owner/group.

**Comment by geerlingguy** [comment] 2016-11-23 21:54
Also, older issue, but maybe there's a bug with the initialization of the Drupal connection? https://github.com/hechoendrupal/DrupalConsole/issues/565

**Comment by MKorostoff** [comment] 2016-11-23 21:59
@geerlingguy sure, here you go:

```
$ ls -lah
total 92K
drwxr-xr-x 20 503 root  680 Nov 23 16:23 .
drwxr-xr-x 34 503 root 1.2K Nov 23 21:10 ..
-rw-r--r--  1 503 root  382 Nov  2 17:01 autoload.php
drwxr-xr-x 33 503 root 1.1K Nov 17 19:21 core
-rw-r--r--  1 503 root  948 Nov  2 17:01 .csslintrc
-rw-r--r--  1 503 root 6.1K Nov 23 17:46 .DS_Store
-rw-r--r--  1 503 root  350 Nov  2 17:01 .editorconfig
-rw-r--r--  1 503 root  185 Nov  2 17:01 .eslintignore
-rw-r--r--  1 503 root   36 Nov  2 17:01 .eslintrc
-rw-r--r--  1 503 root 3.6K Nov  2 17:08 .gitattributes
-rw-r--r--  1 503 root 7.8K Nov  2 17:08 .htaccess
-rw-r--r--  1 503 root  549 Nov  2 17:01 index.php
drwxr-xr-x  6 503 root  204 Nov 23 16:23 modules
drwxr-xr-x  6 503 root  204 Nov 23 17:46 profiles
-rw-r--r--  1 503 root 1.6K Nov  2 17:01 robots.txt
lrwxr-xr-x  1 503 root   42 Nov  2 17:08 simplesaml -> ../vendor/simplesamlphp/simplesamlphp/www/
drwxr-xr-x  6 503 root  204 Nov 16 20:57 sites
drwxr-xr-x  5 503 root  170 Nov  2 17:09 themes
-rw-r--r--  1 503 root  554 Nov  2 17:01 update.php
-rw-r--r--  1 503 root 4.5K Nov  2 17:08 web.config
```

![ls](https://cloud.githubusercontent.com/assets/1197335/20579972/b74a09cc-b19d-11e6-9f3e-0f39b5452b1c.png)

I'm not really clear what's being discussed in hechoendrupal/DrupalConsole#565, but I do notice the discussion revolves around Drupal Console 0.7.5, while I am currently running Drupal Console 1.0.0-beta5 on Drupal VM

**Comment by geerlingguy** [comment] 2016-11-23 22:00
I wonder if it could be a permissions thing. Can you try running the console command with `sudo`, just to see if it works?

**Comment by MKorostoff** [comment] 2016-11-23 22:02
@geerlingguy Same result as [above](#issuecomment-262638810) when running with sudo

**Comment by MKorostoff** [comment] 2016-11-23 22:07
@geerlingguy good news! I _can_ get Drupal console to run with this command, issued from within drupal docroot:

```
../vendor/drupal/console/bin/drupal list
```

I guess I have 2 versions of console installed, one global at /usr/local/bin/drupal and another within the vendor directory.  They're the same version (1.0.0-beta5) but only the one in the vendor directory works.

Note, the vendor directory for this project is _a sibling_ of docroot, not inside of docroot.  Not sure if that matters.

**Comment by geerlingguy** [comment] 2016-11-23 22:11
Ah, interesting... so it sounds similar to drush issues that arise from having it installed globally and local to the project :/

I don't have time to go deeper into this right now, but will try to when I get a chance, and open the floor to others who might have better insight.

**Comment by oxyc** [comment] 2016-11-24 03:13
I think this is the upstream issue https://github.com/hechoendrupal/DrupalConsole/issues/2785

**Comment by oxyc** [comment] 2016-11-24 03:52
@MKorostoff could you try updating to the latest drupal-console RC. I tried to reproduce but for me it works with `1.0.0-rc9`.

**Comment by twerthmueller** [comment] 2016-11-28 11:59
I still get the following "error" (also with rc10):
<img width="774" alt="fullscreen_28_11_16__12_57" src="https://cloud.githubusercontent.com/assets/6920143/20667619/76ed44c2-b56a-11e6-933f-a211c73708ff.png">

**Comment by oxyc** [comment] 2016-11-28 13:30
@twerthmueller and you have the latest rc9?

**Comment by MKorostoff** [comment] 2016-11-28 14:44
@oxyc unfortunately, I was not able to upgrade drupal console.  To do this, I attempted the following:

First I SSH'ed into the vagrant box, and ran `drupal self-update`.  This upgrade attempt failed:

![self-update-failed](https://cloud.githubusercontent.com/assets/1197335/20672425/43eb159c-b54f-11e6-9a51-e4582fd7109a.png)

To work around this, I changed the directory permissions on `/usr/local/bin` to 777.  Then ran the update again, at which time it (sort of) succeeded:

![update-succes](https://cloud.githubusercontent.com/assets/1197335/20672311/d79647f4-b54e-11e6-8f32-89a74f6ca8b6.png)

I'm not sure where (or if) this update was applied, but as far as I can tell my system is still running 1.0.0-beta5, as evidenced by these commands:

![not_updated](https://cloud.githubusercontent.com/assets/1197335/20672393/2c59c50e-b54f-11e6-809f-3911fa236d44.png)

**Comment by jmolivas** [comment] 2016-11-28 15:27
@MKorostoff @twerthmueller Starting on RC releases DC must be installed per site. 

You can still install the global executable now named Launcher to help you find the drupal installation and DC on that particular site.

Try `drupal list` instead to show the available commands.

**Comment by twerthmueller** [comment] 2016-11-28 15:38
When I run the global installed launcher I getting the following error:
<img width="913" alt="fullscreen_28_11_16__16_35" src="https://cloud.githubusercontent.com/assets/6920143/20674348/e5c659a6-b588-11e6-9420-bdc9bdd25354.png">

When I run the DC command from the project vendor directory:

<img width="917" alt="fullscreen_28_11_16__16_37" src="https://cloud.githubusercontent.com/assets/6920143/20674384/0af60fe6-b589-11e6-972d-a5d518e45405.png">

**Comment by jmolivas** [comment] 2016-11-28 16:14
@twerthmueller  DC should work from `root` and `webroot` and any other directory within the site.

Do you mind to try `drupal-composer` 
```
composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction
```
And the do the execute 
```
drupal list
cd web
drupal list
```

**Comment by twerthmueller** [comment] 2016-11-28 16:44
It sems to work locally and DC does recognize the drupal directory.

<img width="894" alt="fullscreen_28_11_16__17_38" src="https://cloud.githubusercontent.com/assets/6920143/20676890/a4acf674-b591-11e6-8f80-16e8ab89e16a.png">

**Comment by jmolivas** [comment] 2016-11-28 17:14
@twerthmueller  I just did the same executing the commands at https://github.com/geerlingguy/drupal-vm/issues/1011#issuecomment-263314261 and have the same result:

![drupal-composer-drupal-console](https://cloud.githubusercontent.com/assets/366275/20678262/e76f9e68-b54a-11e6-97c4-4230f8744246.png)


As you can see the message is different now

> [WARNING] In order to list all of the available commands you should install drupal first.

Actually now is recognizing the drupal site and asking you run installer you can now execute:
```
drupal site:install
```

**Comment by twerthmueller** [comment] 2016-11-28 17:21
The problem in my case was was the `drupal/lightning` distro. Because the core is defined in the distro and not in the root composer.json. As soon as i added `drupal/core` as a required package in the root composer.json, DC does recognize the drupal installation.

See also:
- https://github.com/hechoendrupal/DrupalConsole/issues/2785#issuecomment-263330751
- https://github.com/webflo/drupal-finder/issues/9

**Comment by fubarhouse** [comment] 2016-11-28 23:16
That's an interesting find... I'll have to raise Lightning's compatibility issue with DC at my next govCMS seminar - as they're trying to push D8 and the unofficially supported distribution is Lightning.

Interesting thread all around 👍

**Comment by jmolivas** [comment] 2016-11-28 23:21
@fubarhouse is fixed now a new tag was released for `webflo/drupal-finder` project
https://github.com/webflo/drupal-finder/releases/tag/0.2.1


New DrupalConsole release tomorrow or Wednesday

**Comment by fubarhouse** [comment] 2016-11-29 00:00
@jmolivas Excellent, thanks for the info!

**Comment by oxyc** [comment] 2016-12-10 05:49
So I guess this has been fixed? @MKorostoff

**Comment by geerlingguy** [comment] 2016-12-10 16:07
Closing for now—let me know if it's not fixed!

**Closed by geerlingguy** 2016-12-10 16:07 UTC
Labels: question
