### ISSUE TITLE
Error in vagrant up

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/drupal-vm#645] opened 2016-05-18 14:29 UTC
Hello, 

I have updated the drupal-vm this morning. 

My configuration is:

Ansible 2.0.2
Virtualbox 5.0.14 r105127 
vagrant 1.8.1

When I try to: vagrant provision,  I found this error:

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [drupaltest]

TASK [include_vars] ************************************************************

TASK [include] *****************************************************************
included: /Users/franciscoluisfernandezsoriano/Documents/iinventi-local/provisioning/tasks/init-debian.yml for drupaltest

TASK [Update apt cache if needed.] *********************************************
ok: [drupaltest]

TASK [Get software for Python-based control.] **********************************
ok: [drupaltest] => (item=[u'curl', u'python-apt', u'python-pycurl', u'build-essential', u'sudo', u'unzip'])

TASK [Disable the ufw firewall (since we use a simple iptables firewall).] *****
changed: [drupaltest]

TASK [Add repository for Apache 2.4 on Ubuntu 12.] *****************************
skipping: [drupaltest]

TASK [Add repository for PHP 5.5.] *********************************************
skipping: [drupaltest]

TASK [Add repository for PHP 5.6.] *********************************************
skipping: [drupaltest]

TASK [Add repository for PHP 7.0.] *********************************************
skipping: [drupaltest]

TASK [Define php_xhprof_html_dir.] *********************************************
skipping: [drupaltest]

TASK [include] *****************************************************************
skipping: [drupaltest]

TASK [Run configured pre-provision shell scripts.] *****************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [drupaltest]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/franciscoluisfernandezsoriano/Documents/iinventi-local/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupaltest                 : ok=5    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Thanks.

**Comment by oxyc** [comment] 2016-05-18 14:58
You are missing a variable in your `config.yml`. Please add `pre_provision_scripts: []` somewhere in your `config.yml`.

Closing this as a duplicate of #641

**Closed by oxyc** 2016-05-18 14:58 UTC
