### ISSUE TITLE
Pre-provisionscript

### ISSUE THREAD

**Issue by ellahikamran** [geerlingguy/drupal-vm#1162] opened 2017-02-09 12:42 UTC
### Issue Type

 - Bug Report 

### Your Environment

```
Installed Version: 1.9.1
Latest Version: 1.9.1
ansible 2.2.1.0 ( this is only installed on the virtual machine , not on the host)

```

### Your OS

 - **Windows** (version)

### Full console output

```
failed: [drupalvm] (item=/vagrant/scripts/preprovision.sh) => {"changed": true, "failed": true, "item": "/vagrant/scripts/preprovision.sh", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1486643770.04-104151138249892/preprovision.sh: not found\n", "stdout": "", "stdout_lines": []}
 INFO interface: info:  to retry, use: --limit @/vagrant/provisioning/playbook.retry
```

### Summary
I am trying to run pre-provision script , i have referenced the fiile releative to playbook.yml file , but the provisioning task is generating the following error.

**Comment by oxyc** [comment] 2017-02-09 12:49
To confirm, you have a `scripts/preprovision.sh` located in the project root (next to your `Vagrantfile`)?

**Comment by ellahikamran** [comment] 2017-02-09 13:10
yes the scripts folder sits on the same level as VagrantFile,  my confg.yml file has the following , 
`pre_provision_scripts:
  -"../scripts/preprovision.sh"
post_provision_scripts: []`

**Comment by oxyc** [comment] 2017-02-28 21:32
I'm unable to reproduce this with Vagrant 1.9.1

> TASK [Run configured pre-provision shell scripts.] *****************************
changed: [drupalvm_project] => (item=../scripts/preprovision.sh)

With the following `config.yml`:

```yaml
force_ansible_local: true
pre_provision_scripts:
  - "../scripts/preprovision.sh"
post_provision_scripts: []
```

And the following directory structure:

```
.
├── Vagrantfile
├── config.yml
├── default.config.yml
├── drupal/
├── drupal.make.yml
├── example.drupal.composer.json
├── example.drupal.make.yml
├── examples/
├── mkdocs.yml
├── provisioning/
├── scripts
│   └── preprovision.sh
└── ....
```

**Comment by geerlingguy** [comment] 2017-02-28 23:14
Closing this for now — @ellahikamran please let us know if this is still an issue for you.

**Closed by geerlingguy** 2017-02-28 23:14 UTC
Labels: question
