### ISSUE TITLE
Can not install latest Solr with BLT - 7.3.1

### ISSUE THREAD

**Issue by ndobromirov** [geerlingguy/drupal-vm#1790] opened 2018-06-15 13:45 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.3
VirtualBox 5.1.34r121010
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

```
blt --version
BLT 8.9.x-dev
```

### Your OS
 - Host: **Linux** (Ubuntu 14.04 LTS)
 - Guest: **Linux** (Ubuntu 16.04 LTS)  

### Full console output
This only the output related to solr. No other errors are present in the output.
https://gist.github.com/ndobromirov/abf93d6934eab3ce4bf8e56781a7e7fe

### Summary
This is done through Aquia's BLT.
Solr-related settings added to the box/config.yml
```
# SOLR - settings.
solr_version: "7.3.1"
solr_xms: "64M"
solr_xmx: "128M"
solr_cores:
  - collection1
  - collection2
  - collection3
  - collection4
  - collection5
```

`vagrant up --provision` fails with the output you can see in the solr output.

**Comment by geerlingguy** [comment] 2018-08-08 05:15
The role itself works with 7.x as tested in CI (https://travis-ci.org/geerlingguy/ansible-role-solr), so I'm guessing there's some configuration that's going wrong, possibly caused by Acquia BLT? I know Acquia doesn't use a very new version of Solr currently, so BLT likely only supports 4.x or 5.x maybe.

Have you logged into the VM using `vagrant ssh` and run the commands suggested in the error output? E.g. `systemctl status solr.service` or `journalctl -xe`?

**Comment by geerlingguy** [comment] 2018-08-16 18:57
Have you tried doing a complete rebuild, e.g. `vagrant destroy`, then have the latest settings, the n`vagrant up` to build it again?

**Comment by geerlingguy** [comment] 2018-12-28 23:32
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!

**Closed by geerlingguy** 2018-12-28 23:32 UTC
Labels: question
