### ISSUE TITLE
Composer docker-bake command fails when using CentOS 7

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#1430] opened 2017-06-16 03:10 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS
 - **macOS** (Sierra)

### Full console output
```
TASK [geerlingguy.firewall : Check if firewalld package is installed (on RHEL).] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "yum list installed firewalld", "delta": "0:00:00.308112", "end": "2017-06-16 02:52:57.843496", "failed": true, "rc": 1, "start": "2017-06-16 02:52:57.535384", "stderr": "Error: No matching Packages to list", "stderr_lines": ["Error: No matching Packages to list"], "stdout": "Loaded plugins: fastestmirror, ovl", "stdout_lines": ["Loaded plugins: fastestmirror, ovl"]}
...ignoring

...

TASK [geerlingguy.postfix : Ensure postfix is started and enabled at boot.] ****
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service postfix: Job for postfix.service failed because the control process exited with error code. See \"systemctl status postfix.service\" and \"journalctl -xe\" for details.\n"}

```

### Summary
Trying out Docker with Centos7 to test and ran into the failure above.  

`ubuntu1604` got a bit further but ended with:

```
TASK [geerlingguy.firewall : Check if ufw package is installed (on Ubuntu).] ***
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "service ufw status", "delta": "0:00:00.081245", "end": "2017-06-16 03:08:20.262377", "failed": true, "rc": 3, "start": "2017-06-16 03:08:20.181132", "stderr": "", "stderr_lines": [], "stdout": "? ufw.service\n   Loaded: not-found (Reason: No such file or directory)\n   Active: inactive (dead)", "stdout_lines": ["? ufw.service", "   Loaded: not-found (Reason: No such file or directory)", "   Active: inactive (dead)"]}
...ignoring

...

TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service apache2: Job for apache2.service failed because the control process exited with error code. See \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}

```

**Comment by joelpittet** [comment] 2017-06-16 18:12
I slimmed down my config.yml to just a few changes and it worked, so I'll try to narrow down the culprit(s)
```
vagrant_ip: 192.168.99.99

vagrant_hostname: drupaldocker.dev
vagrant_machine_name: drupaldocker
```

**Comment by joelpittet** [comment] 2017-06-16 18:30
The cento7 change fails with the firewall & postfix error the same with just these changes:

bake.sh: `DISTRO="${DISTRO:-centos7}"`
config.yml: `vagrant_box: geerlingguy/centos7`

So my config has nothing to do with the original problem from what I can tell.

**Comment by geerlingguy** [comment] 2017-06-19 15:06
@joelpittet - Can you also provide the command you used to bake the image? (Just so I can reproduce it locally)—I know that both the postfix and firewall roles have had issues because of systemd/Ansible integration in the past, but I didn't see these issues last time I built. Maybe it's something in Ansible 2.3.1, or just a case I haven't run into yet.

**Comment by geerlingguy** [comment] 2017-06-19 15:07
(Also, just noting that as of about 1 week ago, I had tested the bake command with Ubuntu 16.04 and it worked, so I'm wondering if something changed or if there might be some environment difference that caused it not to work in your case.)

**Comment by joelpittet** [comment] 2017-06-19 17:29
Command:
```
DISTRO=centos7 DRUPALVM_HOSTNAME=docker-vm DRUPALVM_HOSTNAME=drupaldocker.dev DRUPALVM_IP_ADDRESS=192.168.99.99 composer docker-bake
```

config.yml
```
vagrant_box: geerlingguy/centos7
vagrant_ip: 192.168.99.99

vagrant_hostname: drupaldocker.dev
vagrant_machine_name: drupaldocker
```

For ubuntu, it almost worked but I have something in my longer config that it didn't like.  I'll concentrate on this set of changes to the scope of this issue is narrow.

**Comment by evenme** [comment] 2017-06-22 16:53
I'm having similar problem trying to use docker build:

```
$ docker build --rm -t drupal-vm .
...

TASK [Ensure postfix is installed (RedHat).] ***********************************
changed: [localhost]

TASK [Ensure postfix is started and enabled at boot.] **************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/systemctl", "failed": true, "msg": "Failed to get D-Bus connection: Operation not permitted", "rc": 1, "stderr": "Failed to get D-Bus connection: Operation not permitted\n", "stderr_lines": ["Failed to get D-Bus connection: Operation not permitted"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/etc/ansible/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=3    unreachable=0    failed=1

The command '/bin/sh -c ansible-playbook /etc/ansible/drupal-vm/provisioning/playbook.yml   && systemctl enable php7.1-fpm.service' returned a non-zero code: 2
```

Dockerfile:
```
FROM geerlingguy/docker-centos7-ansible:latest
MAINTAINER Jeff Geerling

# Copy provisioning directory, variable overrides, and scripts into container.
COPY ./ /etc/ansible/drupal-vm
COPY ./provisioning/docker/vars/docker-hub-overrides.yml /etc/ansible/drupal-vm/local.config.yml
COPY ./provisioning/docker/bin/* /usr/local/bin

# Provision Drupal VM inside Docker.
RUN ansible-playbook /etc/ansible/drupal-vm/provisioning/playbook.yml \
  # Enable FPM. See https://github.com/geerlingguy/drupal-vm/issues/1366.
  && systemctl enable php7.1-fpm.service

EXPOSE 80 443 3306 8025

CMD ["/lib/systemd/systemd"] ```

**Comment by geerlingguy** [comment] 2017-06-29 04:42
So it seems something is definitely funky with Systemd use and CentOS 7, maybe it's in the shell script? I'll have to dig into it later when I get a little time to build a few test environments.

**Comment by evenme** [comment] 2017-07-14 19:02
I got the same error trying with docker-debian8-ansible image:
```TASK [Ensure postfix is started and enabled at boot.] **************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "failed": true, "msg": "Failed to get D-Bus connection: Unknown error -1", "rc": 1, "stderr": "Failed to get D-Bus connection: Unknown error -1\n", "stderr_lines": ["Failed to get D-Bus connection: Unknown error -1"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/etc/ansible/playbook.retry```

**Comment by joelpittet** [comment] 2017-07-14 23:21
@evenme which error was the same?  The error you posted looks different and it's not Centos7 related.

**Comment by MrPaulDriver** [comment] 2017-10-10 08:08
Seeing the same message with Windows 10

**Comment by geerlingguy** [comment] 2018-12-28 23:16
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!

**Closed by geerlingguy** 2018-12-28 23:16 UTC
Labels: docker, question
