### ISSUE TITLE
changing php_fpm_pool_user and php_fpm_pool_group to "nginx" kills the build process

### ISSUE THREAD

**Issue by yobottehg** [geerlingguy/drupal-vm#1165] opened 2017-02-10 09:59 UTC
### Issue Type
Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS
 **macOS** (10.12.3)

### Full console output

```
fatal: [wondrous-intern]: FAILED! => {"cache_update_time": 1486718572, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php7.1-mysql'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  python-crypto python-ecdsa python-httplib2 python-jinja2 python-markupsafe\n  python-paramiko python-pkg-resources python-setuptools python-six\n  python-yaml sshpass\nUse 'sudo apt autoremove' to remove them.\nThe following NEW packages will be installed:\n  php7.1-mysql\n0 upgraded, 1 newly installed, 0 to remove and 56 not upgraded.\nNeed to get 119 kB of archives.\nAfter this operation, 453 kB of additional disk space will be used.\nGet:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.1-mysql amd64 7.1.1-1+deb.sury.org~xenial+1 [119 kB]\nFetched 119 kB in 0s (667 kB/s)\nSelecting previously unselected package php7.1-mysql.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 69478 files and directories currently installed.)\r\nPreparing to unpack .../php7.1-mysql_7.1.1-1+deb.sury.org~xenial+1_amd64.deb ...\r\nUnpacking php7.1-mysql (7.1.1-1+deb.sury.org~xenial+1) ...\r\nProcessing triggers for php7.1-fpm (7.1.1-1+deb.sury.org~xenial+1) ...\r\nJob for php7.1-fpm.service failed because the control process exited with error code. See \"systemctl status php7.1-fpm.service\" and \"journalctl -xe\" for details.\r\ninvoke-rc.d: initscript php7.1-fpm, action \"restart\" failed.\r\ndpkg: error processing package php7.1-fpm (--unpack):\r\n subprocess installed post-installation script returned error exit status 1\r\nErrors were encountered while processing:\r\n php7.1-fpm\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  python-crypto python-ecdsa python-httplib2 python-jinja2 python-markupsafe", "  python-paramiko python-pkg-resources python-setuptools python-six", "  python-yaml sshpass", "Use 'sudo apt autoremove' to remove them.", "The following NEW packages will be installed:", "  php7.1-mysql", "0 upgraded, 1 newly installed, 0 to remove and 56 not upgraded.", "Need to get 119 kB of archives.", "After this operation, 453 kB of additional disk space will be used.", "Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.1-mysql amd64 7.1.1-1+deb.sury.org~xenial+1 [119 kB]", "Fetched 119 kB in 0s (667 kB/s)", "Selecting previously unselected package php7.1-mysql.", "(Reading database ... ", "(Reading database ... 5%", "(Reading database ... 10%", "(Reading database ... 15%", "(Reading database ... 20%", "(Reading database ... 25%", "(Reading database ... 30%", "(Reading database ... 35%", "(Reading database ... 40%", "(Reading database ... 45%", "(Reading database ... 50%", "(Reading database ... 55%", "(Reading database ... 60%", "(Reading database ... 65%", "(Reading database ... 70%", "(Reading database ... 75%", "(Reading database ... 80%", "(Reading database ... 85%", "(Reading database ... 90%", "(Reading database ... 95%", "(Reading database ... 100%", "(Reading database ... 69478 files and directories currently installed.)", "Preparing to unpack .../php7.1-mysql_7.1.1-1+deb.sury.org~xenial+1_amd64.deb ...", "Unpacking php7.1-mysql (7.1.1-1+deb.sury.org~xenial+1) ...", "Processing triggers for php7.1-fpm (7.1.1-1+deb.sury.org~xenial+1) ...", "Job for php7.1-fpm.service failed because the control process exited with error code. See \"systemctl status php7.1-fpm.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript php7.1-fpm, action \"restart\" failed.", "dpkg: error processing package php7.1-fpm (--unpack):", " subprocess installed post-installation script returned error exit status 1", "Errors were encountered while processing:", " php7.1-fpm"]}
```

### Summary

Like stated here http://docs.drupalvm.com/en/latest/configurations/webservers-nginx/
I changed the php_fpm_pool_user and php_fpm_pool_group to nginx to reflect the use of nginx. If i create the vm the above error is given. 

If i do not do this everything is fine.

**Comment by geerlingguy** [comment] 2017-02-10 22:35
It looks like the failure is here:

```
Job for php7.1-fpm.service failed because the control process exited with error code.
See "systemctl status php7.1-fpm.service" and "journalctl -xe" for details.
```

After that failure, can you run `systemctl status php7.1-fpm.service` inside the VM and see what it says?

**Comment by geerlingguy** [comment] 2017-02-10 22:36
Also, I presume you're using Ubuntu 16.04 (any other config.yml changes?).

**Comment by yobottehg** [comment] 2017-02-11 07:48
I use drupalvm as a compose dependency and a local.config.yml as overwrite.
```
# Composer settings
build_composer_project: false

#drush alias fix
configure_drush_aliases: false

# Base settings for vagrant box
vagrant_hostname: wondrous-intern.dev
vagrant_machine_name: wondrous-intern
vagrant_ip: 192.168.88.177

# Correct folders
drupal_composer_install_dir: "/var/www/drupalvm"

# webserver
drupalvm_webserver: nginx
#php_fpm_pool_user: nginx
#php_fpm_pool_group: nginx

#solr
solr_version: "6.4.1"

post_provision_scripts:
  - "{{ config_dir }}/../scripts/vagrant/configure-solr.sh"

# Use mariaDB instead of mysql
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

#php
php_version: "7.1"
php_memory_limit: "256M"

# xdebug
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_max_nesting_level: 512
php_xdebug_idekey: PHPSTORM

# Site install false
install_site: false
drupal_enable_modules: []

installed_extras:
 # - adminer
 # - blackfire
 # - drupalconsole
 # - memcached
 # - newrelic
 # - nodejs
 # - ruby
 # - selenium
 # - varnish
 # - xhprof
 # - drush
 - solr
 - redis
 - mailhog
 - xdebug
 - pimpmylog
```

**Comment by yobottehg** [comment] 2017-02-11 07:55
The task where it fails is this one:
`TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (Debian).] ********`

here the output:
```
agrant@wondrous-intern:~$ systemctl status php7.1-fpm.service
● php7.1-fpm.service - The PHP 7.1 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.1-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-02-11 07:54:48 UTC; 46s ago
     Docs: man:php-fpm7.1(8)
  Process: 28801 ExecStart=/usr/sbin/php-fpm7.1 --nodaemonize --fpm-config /etc/php/7.1/fpm/php-fpm.conf (code=exited, statu
 Main PID: 28801 (code=exited, status=78)
```

**Comment by oxyc** [comment] 2017-03-01 00:21
I can reproduce this, it's caused because there is no user called `nginx`:

```sh
vagrant@drupalvm-project:~$ systemctl status php7.1-fpm.service
* php7.1-fpm.service - The PHP 7.1 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.1-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-02-28 23:46:58 UTC; 32min ago
     Docs: man:php-fpm7.1(8)
  Process: 28892 ExecStart=/usr/sbin/php-fpm7.1 --nodaemonize --fpm-config /etc/php/7.1/fpm/php-fpm.conf (code=exited, status=78)
 Main PID: 28892 (code=exited, status=78)
vagrant@drupalvm-project:~$ sudo /usr/sbin/php-fpm7.1 --nodaemonize --fpm-config 
sudo /usr/sbin/php-fpm7.1 --nodaemonize --fpm-config /etc/php/7.1/fpm/php-fpm.conf
[01-Mar-2017 00:19:55] ERROR: [pool www] cannot get uid for user 'nginx'
[01-Mar-2017 00:19:55] ERROR: FPM initialization failed
```

**Comment by oxyc** [comment] 2017-03-15 21:26
I'll close this. To fix it you can add a preprovision script/task that creates the `nginx` user if you need it.

**Closed by oxyc** 2017-03-15 21:26 UTC
Labels: question
