### ISSUE TITLE
Malformed version error setting up Drupal 7

### ISSUE THREAD

**Issue by bradbulger** [geerlingguy/drupal-vm#1742] opened 2018-03-21 16:38 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.3
VirtualBox 5.1.22r115126
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/brad/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 10 2018, 00:01:11) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (version)

### Full console output

https://gist.github.com/bradbulger/62a354ec51a3b2b70983d4ae054d7708

### Summary

Trying to set up a Drupal 7 site. I make the recommended changes to config.yml and drupal.make.yml, and then try to start with vagrant up. I get an error "Message: ArgumentError: Malformed version number string 2.4.3.0". That's the ansible version. I've tried updating it, reinstalling, doesn't matter.

I can start up vagrant in an unmodified clone of the code. So I don't know the source of the problem. I've put the changes I've made to config.yml and drupal.make.yml into the gist.

**Comment by bradbulger** [comment] 2018-03-21 16:43
This looks to be the same as issue #1736 - applying the change from the comment there got me past this error.

**Comment by geerlingguy** [comment] 2018-03-21 17:05
Yes, this is a dupe of #1736; this should now be fixed in the latest master commit.

**Closed** 2018-03-21 17:05 UTC
Labels: duplicate
