### ISSUE TITLE
404 Errors after updating to macOS Catalina

### ISSUE THREAD

**Issue by charlieartist** [geerlingguy/drupal-vm#1979] opened 2019-10-08 14:30 UTC
Updated my system to macOS Catalina (10.15) yesterday.

After setup was complete, went to my local boxes, ran `vagrant reload --provision` for all, was able to stand up. Now, I can access the dashboards for all of the sites fine, but when going to the URLs, get 404 errors.

To be sure there wasn't any cruft, did `vagrant destroy`, then rebuilt, but the same issues.

Possibly an Apache rewrite issue?

To clarify, I confirmed on my system:
Vagrant: 2.2.5
Ansible: 2.8.5
VirtualBox: Version 6.0.12 r133076 (Qt5.6.3)

And, I ran the update to Vagrant Hostsupdater

- - -

Further investigation has revealed that while the Drupal VM dashboard is where it's supposed to be, there's no sign of the Drupal install in the VM.

**Comment by danepowell** [comment] 2019-10-08 20:46
Probably a dupe of #1978, are any files getting mounted in the VM?

**Comment by charlieartist** [comment] 2019-10-08 20:48
@danepowell No, none are. Now, I did a clone and standup of Drupal VM, so I know it works on Catalina. I'm still going through other items. I did check your post at 1978, and don't believe it's the same.

**Closed** 2019-10-13 14:50 UTC

**Comment by charlieartist** [comment] 2019-10-13 14:51
This issue has been combined with [1978](https://github.com/geerlingguy/drupal-vm/issues/1978).
