### ISSUE TITLE
yo install not happening 

### ISSUE THREAD

**Issue by prathyushmr** [geerlingguy/drupal-vm#452] opened 2016-02-18 11:30 UTC
the yo installation getting skipped 
config.yml  
nodejs_version: "4.*"
nodejs_npm_global_packages:
  - name: "yo"

**Comment by oxyc** [comment] 2016-02-18 11:33
The `4.*` needs to be `4.x`, otherwise it should work. Does your config look like this:
```yaml
nodejs_version: "4.x"
nodejs_npm_global_packages:
  - name: "yo"
```

**Comment by prathyushmr** [comment] 2016-02-18 11:38
nodejs is getting installed to the  latest one , no issue with that . But the yo install getting skipped

**Comment by oxyc** [comment] 2016-02-18 11:47
Ah, okay then it's probably the same issue as https://github.com/geerlingguy/drupal-vm/issues/424

**Comment by prathyushmr** [comment] 2016-02-18 12:05
npm list -g --depth=0                  
/usr/lib                                             
└── npm@2.14.9                                       
The same result when run as a vagrant or  root user

**Comment by geerlingguy** [comment] 2016-02-18 15:57
This is a dupe of #424 - Please follow that issue and hopefully we can get it resolved soon...

**Closed by geerlingguy** 2016-02-18 15:57 UTC
