### ISSUE TITLE
mount.nfs: access denied by server while mounting on RHEL guest

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#1040] opened 2016-12-08 20:06 UTC
### Issue Type
 - Bug Report

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** Sierra

### Full console output

```
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,udp 192.168.88.1:/Users/NAME/Sites/drupal /var/www/sites/drupal
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www/sites/drupal
fi
else
exit $result
fi
Stdout from the command:
Stderr from the command:
mount.nfs: access denied by server while mounting 192.168.88.1:/Users/NAME/Sites/drupal
```

### Summary

I was running a workshop to show people DrupalVM, unfortunately we ran out of time and each participant in the group had an error of some kind or another:(  The easiest to reproduce is this one: With `Vagrant 1.8.6`  things worked on my machine, but two people had the latest `Vagrant 1.9.1` and got the error above. I upgraded to `1.9.1` and also got the above error.  

Downgrading back to `1.8.6` fixed the problem but then we ran into problems with the plugins not working and needing to be re-installed.

Wondering if maybe we can list versions of the dependencies to avoid somewhere in the docs or project readme?  And also do you know if there is a workaround for this issue on `1.9.1`

**Instructions I gave:**
https://gist.github.com/joelpittet/53572942d0f306d2bca19e09e08c0512

**Comment by geerlingguy** [comment] 2016-12-09 16:29
@joelpittet - I'm looking into this now. Testing Vagrant 1.9.1 locally to see if I can reproduce the error. Was everyone using a Mac, or were some people using any other machines?

The past couple months have been incredibly rough dependency-wise—I _know_ that Vagrant 1.8.7 and VirtualBox 5.1.8 had major bugs, but other versions _should_ be more stable. I've been on Vagrant 1.9.0 for a few weeks with zero issues (Windows or Mac), but am just updating to 1.9.1 today.

**Comment by joelpittet** [comment] 2016-12-09 18:04
The people that this specific problem were all using Macs. I think that was the biggest issue with Mac installations, the Windows issues were more varied.

I tested the upstream vagrant patch that looks like it caused this regression from `1.9.0` to `1.9.1` and it was pretty clear that pull request caused the problems.
https://github.com/mitchellh/vagrant/pull/8052

**Comment by geerlingguy** [comment] 2016-12-09 18:31
@joelpittet - Just to clarify, it looks like this bug only affects CentOS/RHEL guests? (And not Ubuntu?).

**Comment by geerlingguy** [comment] 2016-12-09 18:34
I can reproduce the issue with a barebones Vagrantfile on 1.9.1 (only on RHEL, of course).

**Comment by joelpittet** [comment] 2016-12-09 20:01
yes Centos7 seems to be where this is happening

**Comment by jorissteyn** [comment] 2016-12-14 13:27
> Was everyone using a Mac, or were some people using any other machines?

I'm on a Arch Linux host (vagrant 1.9.1, virtualbox 5.1.10) using base box geerlingguy/centos7 1.1.5, encountering this exact issue.

**Comment by benhosmer** [comment] 2016-12-14 17:11
I can confirm that Vagrant 1.9.1 is responsible for the nfs error even on CentOS 7.

Downgrading to 1.9.0 I was able to mount my nfs shares with no problem. 

Incidentally, this isn't a DrupalVM error at all. I encountered the same error with my own bare CentOS 7 box.

**Comment by geerlingguy** [comment] 2016-12-14 17:52
@jorissteyn - Can you see if it works fine with 1.9.0? I'm hoping it will get fixed in 1.9.2...

**Comment by joelpittet** [comment] 2016-12-15 21:02
`1.9.0` worked for me

**Comment by geerlingguy** [comment] 2016-12-28 17:08
The upstream issues are:

  - https://github.com/mitchellh/vagrant/issues/8138
  - https://github.com/mitchellh/vagrant/issues/5424

I'm going to leave this open just to make sure people using Drupal VM with CentOS 7 don't open duplicate issues (we'll keep the discussion focused here).

**Comment by geerlingguy** [comment] 2016-12-28 17:08
Oops, didn't mean to close!

**Comment by geerlingguy** [comment] 2017-02-28 18:04
It looks like Vagrant 1.9.2 (released today) fixes the main bug—at least tested on macOS with CentOS 7 guest!

I'm going to close this—if anyone else is still having trouble, please let me know and we can reopen and dig further.

**Closed by geerlingguy** 2017-02-28 18:04 UTC
Labels: question, upstream

**Comment by Zorlin** [comment] 2017-04-06 04:00
@geerlingguy Hi there,

```
wings@bar:~/Projects/drupal-vm$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
 ==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
[drupalvm] GuestAdditions 5.1.18 running --- OK.
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2017-04-06 11:38:22 AWST; 19min ago
 Main PID: 3069 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Apr 06 11:38:22 bar systemd[1]: Starting NFS server and services...
Apr 06 11:38:22 bar systemd[1]: Started NFS server and services.
exportfs: duplicated export entries:
exportfs: 	192.168.88.88:/home/wings/Projects/drupal-vm
exportfs: 	192.168.88.88:/home/wings/Projects/drupal-vm
exportfs: /home/wings/Projects/drupal-vm does not support NFS export
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.88.1:/home/wings/Projects/drupal-vm /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.88.1:/home/wings/Projects/drupal-vm

wings@bar:~/Projects/drupal-vm$ vagrant -v
Vagrant 1.9.3
```

**Comment by geerlingguy** [comment] 2017-04-06 13:10
`exportfs: /home/wings/Projects/drupal-vm does not support NFS export` seems to be the issue.

Have you manually installed NFS? http://docs.drupalvm.com/en/latest/getting-started/installation-linux/#ubuntu

**Comment by larmedina75** [comment] 2017-07-05 20:20
I have this problem with "mount.nfs: access denied by server while mounting" message on vagrant up.
Error shows "mount -o vers=3,udp... " command and this URL provides a fix that works for me: [https://www.comoinstalarlinux.com/error-en-vagrant-al-montar-directorio-compartido-con-nfs/](https://www.comoinstalarlinux.com/error-en-vagrant-al-montar-directorio-compartido-con-nfs/)

The problem is on NFS protocol version if your host uses NFS 4, you need to config command for use version 4 and do not use UDP. Make changes to your Vagrantfile to do this.

Regards

**Comment by oxyc** [comment] 2017-07-06 00:21
It's unfortunate that macOS doesn't have a working NFSv4 :/ @geerlingguy anything we can do about this? Basically Drupal VM doesn't work out of the box on a lot of linux hosts anymore

**Comment by geerlingguy** [comment] 2017-07-06 02:10
Is there any way we could set one set of defaults for 'any linux' and another for 'any macos' or windows? For now it seems like that would be the simplest fix. Once Apple starts shipping nfs 4, it could be a little more annoying...

Is there an upstream issue for this with Vagrant? It seems like it should be handled there.

**Comment by benhosmer** [comment] 2017-07-06 12:18
@geerlingguy it's a fairly constant whack-a-mole game with VirtualBox and Linux hosts. I use Fedora for my daily driver and the kernel gets updated on a fairly regular basis. I don't know of any specific upstream ticket with Vagrant for this.

**Comment by oxyc** [comment] 2017-07-06 13:19
Some `nfs-utils` versions across distros

- [x] Ubuntu 16.04: UDP enabled `nfs-utils v1.2.8` [ref](https://launchpad.net/ubuntu/xenial/+source/nfs-utils)
- [ ] Fedora 25, 26: UDP disabled `nfs-utils v2.1.1-5.rc4+` [ref](https://apps.fedoraproject.org/packages/nfs-utils)
- [x] Arch Linux: UDP enabled `nfs-utils v2.1.1-4` [ref](https://www.archlinux.org/packages/core/i686/nfs-utils/)
- [x] Debian 9: UDP enabled `nfs-utils v 1.3.4-2.1` [ref](https://packages.debian.org/search?searchon=sourcenames&keywords=nfs-utils)

So it seems Fedora is pretty edge.

**Comment by oxyc** [comment] 2017-07-06 13:51
I created a new issue for this, please use that one instead.
