### ISSUE TITLE
Drush Unable To Run In Newly Provisioned Drupal VM

### ISSUE THREAD

**Issue by casc-or** [geerlingguy/drupal-vm#1643] opened 2017-12-18 04:37 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
Virtualbox 5.2.2r119230
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

### Your OS

 - Windows 10 Pro Version 1709
 
### Full console output

https://gist.github.com/casc-or/de3ab5fcbbc282ccbcc0608fa21fd1f1
### Summary

Attempting to install Drupal VM in a working Windows 10 / Vagrant / VirtualBox environment (I already use it for Laravel Homestead development.

Installation arrives nearly at the end before a failed Ansible command as seen in the linked gist.

Attempting to run the drush commend by SSH into the vagrant box gives this

vagrant@drupalvm:/var/www/drupalvm/drupal/vendor/drush/drush$ /var/www/drupalvm/drupal/vendor/drush/drush/drush --root=/var/www/drupalvm/drupal/web status bootstrap
-bash: /var/www/drupalvm/drupal/vendor/drush/drush/drush: Permission denied
vagrant@drupalvm:/var/www/drupalvm/drupal/vendor/drush/drush$

The Drupal site WILL start at its config page though.

Would appreciate assistance in resolving this.

**Comment by fubarhouse** [comment] 2017-12-18 11:07
What you have there is a permission denied error, #1614 could be related.

As for a fix - you could try making drush to be executable.
`chmod 775 /var/www/drupalvm/drupal/vendor/drush/drush/drush`

**Comment by casc-or** [comment] 2017-12-18 12:38
I'm not a *nix whiz, but I don't think that worked.

-rw-rw-rw- 1 9999 vagrant_group  4368 Dec 17 18:27 drush

That's after trying logged in as vagrant, and then sudo chmod ... as well. 

Some additional info which may be relevant - the directory is in a shared folder from the host, and I'm using NFS to mount it (thanks to Allegro NFS from Franz, works well).

**Comment by casc-or** [comment] 2017-12-18 14:57
There's something wrong in the install here.

I did vagrant destroy -f followed by vagrant up --provision. The first attempt brought the message
```
C:\Users\username\Sites\drupal-vm>vagrant up --provision > provision.txt
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'unknown' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```
So then it occurred to me that there was an odd VM in Virtualbox named packer-ubuntu-16.04-amd64_1513601919388_14911 which presumably is part of the Drupal VM install. I deleted it too and ran the vagrant up --provision command again.

This time it completed, but with the same error again.

### Full console output


https://gist.github.com/casc-or/af6cdb3e42a7df86241300ac92f7e2f8

The only mod I made to the default.config.yml file was to give it my desired IP and to comment out the line 
```
#  - name: vagrant-hostsupdater
```
I edited the hosts myself before install.

After install, I used vagrant ssh (and puTTY) to SSH into the VM and try to chmod. Results were the same - here's what the drush files look like
```
-rw-rw-rw- 1 9999 vagrant_group  4368 Dec 17 18:27 drush
-rw-rw-rw- 1 9999 vagrant_group 14013 Dec 17 18:27 drush.api.php
-rw-rw-rw- 1 9999 vagrant_group  1937 Dec 17 18:27 drush.complete.sh
-rw-rw-rw- 1 9999 vagrant_group    21 Dec 17 18:27 drush.info
-rw-rw-rw- 1 9999 vagrant_group  4954 Dec 17 18:27 drush.launcher
-rw-rw-rw- 1 9999 vagrant_group 23280 Dec 17 18:27 drush_logo-black.png
-rw-rw-rw- 1 9999 vagrant_group   221 Dec 17 18:27 drush.php

```
Either there is something I'm missing in the instructions for installation, or something doesn't like the environment I'm using.

Help appreciated - I need to get a Drupal 8 project going.

**Comment by FinBoWa** [comment] 2017-12-18 15:48
you are running virtualbox 5.2. I think that has some issues https://github.com/geerlingguy/drupal-vm/issues/1587 not sure are all of them fixed and would they affect windows

**Comment by casc-or** [comment] 2017-12-18 15:52
I'm trying again but this time running the vagrant up --provision in a Windows Administrative Command Prompt.

In all attempts though early in the process I see these errors
```
Err:24 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-87.110
  404  Not Found [IP: 91.189.91.26 80]
Get:25 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libc6-dev amd64 2.23-0ubuntu9 [2,082 kB]
Err:24 http://security.ubuntu.com/ubuntu xenial-security/main amd64 linux-libc-dev amd64 4.4.0-87.110
  404  Not Found [IP: 91.189.91.26 80]
Get:26 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 manpages-dev all 4.04-2 [2,048 kB]
Err:20 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 dkms all 2.2.0.3-2ubuntu11.3
  404  Not Found [IP: 91.189.91.26 80]
Fetched 24.6 MB in 17s (1,388 kB/s)
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/d/dkms/dkms_2.2.0.3-2ubuntu11.3_all.deb  404  Not Found [IP: 91.189.91.26 80]

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-87.110_amd64.deb  404  Not Found [IP: 91.189.91.26 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Makes me wonder if there is a disconnect between what the provisioning is trying to install and current versions?

**Comment by casc-or** [comment] 2017-12-18 15:56
Thanks, FinBoWa, but Vagrant 2.0.1 as installed does support Virtualbox 5.2 (and as noted earlier I am running a Laravel Homestead VM on the same host setup with no problem)

https://github.com/hashicorp/vagrant/issues/9090

**Comment by fubarhouse** [comment] 2017-12-18 21:58
@casc-or,

The mode change wasn't affected, and the end result is the same - permission denied to the drush binary.

I recommend you run the following:
`sudo apt-get update --fix-missing`

What you're looking for in the permissions is rwxrwxrw-, which is the equivelant of 0775.

Here's an example of mine, which is 0777:
````
vagrant@drupalvm:/$ stat $(which drush)
  File: '/usr/local/bin/drush' -> '/home/vagrant/.dvm/versions/drush-8.1.15/vendor/bin/drush'
  Size: 57        	Blocks: 0          IO Block: 4096   symbolic link
Device: fc00h/64512d	Inode: 4990515     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (  900/ vagrant)   Gid: (  900/ vagrant)
Access: 2017-12-18 01:01:23.544041000 +0000
Modify: 2017-12-18 01:01:23.540038999 +0000
Change: 2017-12-18 01:01:23.540038999 +0000
 Birth: -
vagrant@drupalvm:/$
````
You can check that this is the problem by running:
`sudo /var/www/drupalvm/drupal/vendor/drush/drush/drush`

Which will run drush as the root user, if permission is denied for the root user it'll eliminate a bunch of problems.

To change the permissions (I've revised this):

`sudo chmod -R 775 /var/www/drupalvm/drupal/vendor/drush/drush/`

and you can follow-up by running:
`stat /var/www/drupalvm/drupal/vendor/drush/drush/drush`, and look for 0775 under the line that starts with Access. Then, see if you can run it.

This should be enough to get any additional information. I still think it's related to the issue I mentioned, and I believe there's a genuine bug for Windows in here. I've never actually got it to work in Windows, so you're doing better than me :)

**Comment by casc-or** [comment] 2017-12-18 22:27
Thanks for your efforts to try and help.

I haven't mentioned it in this thread, but I have already run 
```
sudo apt-get update --fix-missing
```
after having seen it referenced at the end of the section I pasted where ubuntu files aren't retrieved which appear to be security related. No effect.

I did try recursively changing permissions on the drush directory, without success. 

I don't think I've tried running drush as root - I'll try that as soon as the VM finishes provisioning (again).

**Comment by casc-or** [comment] 2017-12-18 22:38
Still nothing. "Command not found".
```
vagrant@drupalvm:/$ sudo /var/www/drupalvm/drupal/vendor/drush/drush/drush
sudo: /var/www/drupalvm/drupal/vendor/drush/drush/drush: command not found
vagrant@drupalvm:/$ ls -l /var/www/drupalvm/drupal/vendor/drush/drush/drush*.*
-rw-rw-rw- 1 9999 vagrant_group 14013 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush.api.php
-rw-rw-rw- 1 9999 vagrant_group  1937 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush.complete.sh
-rw-rw-rw- 1 9999 vagrant_group    21 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush.info
-rw-rw-rw- 1 9999 vagrant_group  4954 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush.launcher
-rw-rw-rw- 1 9999 vagrant_group 23280 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush_logo-black.png
-rw-rw-rw- 1 9999 vagrant_group   221 Dec 17 18:27 /var/www/drupalvm/drupal/vendor/drush/drush/drush.php
vagrant@drupalvm:/$
```

**Comment by geerlingguy** [comment] 2017-12-22 22:23
@casc-or - I can't reproduce the error, but I haven't yet tried using VirtualBox 5.2.x (I'm still on the latest 5.1.x release), and I wonder if there's any chance that has something to do with it (the way shares work, the way the guest additions are updated, etc... could have something to do with it).

I will try to get a running VirtualBox 5.2.x setup locally and see if I can reproduce the issue.

**Comment by casc-or** [comment] 2017-12-22 22:38
Thanks @geerlingguy - I am presently working through your instructions on setting up [BLT and Drupal VM within Windows 10](https://www.jeffgeerling.com/blog/2017/set-blt-and-drupal-vm-entirely-within-windows-10) to see if I can make that work and will let you know if I can, but my strong preference would be to do the simpler (to me) Vagrant / Drupal VM all from Windows.

**Comment by geerlingguy** [comment] 2017-12-28 23:08
I've pushed new Vagrant base boxes for all OSes, with the 5.2.4 Guest Additions, and I've tested at least ubuntu1604, ubuntu1404, debian9, and centos7 on my Mac. Haven't done any extra testing on my PC (It's in my office and I'm off this week :).

Everything seems to work correctly using all the config.yml defaults on my Mac at least.

**Comment by casc-or** [comment] 2018-01-01 15:19
So - I finally got this to run.

Way back in this thread I said

> Some additional info which may be relevant - the directory is in a shared folder from the host, and I'm using NFS to mount it (thanks to Allegro NFS from Franz, works well).

Turns out it only works well for my Laravel Homestead box.

From the Allegro NFS documentation

> By default, all regular files report mode 0666 (rw-rw-rw-) mode. Files with filename extensions that are usually executable (.exe, .com, .bat, etc) report mode 0777 (rwxrwxrwx). Directories report mode 0777. You can use the umask to turn some of the default mode bits off before reporting them back to the client. Unless you have special needs, it is recommended that you leave the umask setting at 0. See the Notes section below for more information. The parameter is expressed in octal notation.

and 

> chmod is not supported. chmod requests are simply ignored by Allegro NFS. This was a specific design decision to avoid confusing problems that can be caused when the chmod'd files are subsequently accessed on the Windows side. The execute bit is simulated based on filename extension. Files with filename extension exe, bat, and com automatically have the 'x' bit set. If you need the execute bit set, you can make Allegro NFS enable the execute bit on every file, which may suit your needs.


My best guess is that the Laravel Homestead files must get installed with the correct permissions while the Drupal-VM files must be getting permissions (not) set during the installation process. 

So, I could try setting execute on all files but that doesn't sound like a good idea - sooner or later some file is going to get to a production server with 777 by mistake.

I disabled nfs folder syncing and everything worked albeit slowly.

Now that I know what the issue is and have a functioning installation, I'm working towards the workflow as described in [Drupal VM on Windows - a fast container for BLT project development](https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development). I have a question on that but I'll post it on the comments there.

Thanks to everyone posting on this thread for all their assistance!

**Comment by geerlingguy** [comment] 2018-01-04 06:04
@casc-or - Ah, thanks for the reminder, and thanks for the follow-up throughout, hopefully it helps someone else (or yourself again) in the future! I'm closing this issue; please feel free to post any follow-ups if you find blockers towards getting your workflow set up.

**Closed by geerlingguy** 2018-01-04 06:04 UTC
Labels: question, windows
