### ISSUE TITLE
Why Vagrant share can not work?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#571] opened 2016-04-21 13:18 UTC
I use a link given by 'vagrant share' but I get this error 'Failed to connect to Vagrant Share' in my browser.

Is it feature for Drupal VM?

**Comment by geerlingguy** [comment] 2016-04-22 15:07
I've personally never used Vagrant Share, and I don't know much about how it's supposed to work, etc.—however, anyone else who has used it can chime in and maybe give feedback as to how it's supposed to work?

I'm wondering if there might be a networking issue preventing it from working on your computer. AFAICR, according to the docs, it should work with most any Vagrant box.

**Comment by oxyc** [comment] 2016-04-30 19:09
Did you get it working? For me it works out of the box.

Scanning the Vagrant issue queue it seems the most common problem is a firewall. From your earlier issues I assume you run windows where I guess it's more common to have a restrictive firewall?

**Comment by ArtuGit** [comment] 2016-05-03 17:22
oxyc, thank you.
I will try,

**Comment by oxyc** [comment] 2016-05-03 20:35
What's the terminal output after you run `vagrant share`? If anything sticks out, it might be worth searching for it in the Vagrant issue queue too. https://github.com/mitchellh/vagrant/issues

If you figure it out, would be great if you could post it here for future reference!

**Comment by geerlingguy** [comment] 2016-05-10 13:20
Going to close this for now; typically, Vagrant share should work according to Vagrant's documentation, and it's likely there's a networking issue if it's not working—I'd suggest looking around Vagrant's queue to see if the problem you're getting has been documented there. If you find there's an issue caused by Drupal VM's Vagrant config, then we can reopen this issue; please make sure to copy and paste any relevant error messages as they're important in diagnosing the root cause.

**Closed by geerlingguy** 2016-05-10 13:20 UTC
Labels: question
