### ISSUE TITLE
Syntax error in solr .install file

### ISSUE THREAD

**Issue by jesrig** [geerlingguy/drupal-vm#1024] opened 2016-11-28 20:55 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.7
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS
 - **Windows** (version)

### Full console output
https://gist.github.com/jesrig/055786c71229bfd5d3bdda6256c67fe8

### Summary
I have am using drupalvm 3.5.2, Vagrant 1.8.7, and Virtualbox 5.1.6. I am trying to provision and I'm getting the following error:

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here

The error appears to have been in '/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment] 2016-11-28 21:45
@jesrig - Please see: https://github.com/geerlingguy/drupal-vm/issues/1018

**Comment by jesrig** [comment] 2016-11-28 21:52
@geerlingguy How do I upgrade Ansible? I don't think I ever installed that persay, I thought it was packaged in the drupalvm package. This is why my environment stated `bash: ansible: command not found`.

**Comment by geerlingguy** [comment] 2016-11-28 22:37
@jesrig - Ah, in that case, it's the installed version inside the VM, oops! Can you do `vagrant ssh` and then `ansible --version`?

**Comment by jesrig** [comment] 2016-11-29 14:43
Here you go:
...
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
...

**Comment by geerlingguy** [comment] 2016-11-29 14:50
@jesrig - if you destroy the VM (`vagrant destroy -f`) and then build it again, does it still error out and have the same version of Ansible inside? It seems like it should be installing the latest version from `pip`, but maybe it's using a different source.

Alternatively, you could log in and install it/upgrade it yourself (if with pip, `pip uninstall ansible` then `pip install ansible` would do it).

**Comment by jesrig** [comment] 2016-11-29 14:54
@geerlingguy I'd rather not have to destroy it. I've had to do this a bunch of other times in hte past when I had Vagrant issues and I have reimport the db etc.

This is the error I get when I try to uninstall ansible:

`Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 336, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/ansible'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by geerlingguy** [comment] 2016-11-29 16:49
@jesrig - Are you on CentOS 6 by chance? That might be the source of the SNI issue :/

**Comment by jesrig** [comment] 2016-11-29 17:43
Nope, Ubuntu 1404

**Comment by geerlingguy** [comment] 2016-12-02 20:09
I'm going to do a little testing on my Windows 10 laptop and see if this is working yet, or if I need to rebuild my boxes...

**Comment by geerlingguy** [comment] 2016-12-02 21:40
@jesrig - Installing new VMs seems to grab the latest version of Ansible (e.g. 2.2.0 currently), so my best suggestion would be to run `vagrant destroy -f` to destroy the current VM instance, then run `vagrant up` to build a new VM. It should download the correct version of Ansible.

You can check what version of Ansible you have installed by running `vagrant ssh` to log into the VM, then run `ansible --version` to see the current version.

Closing this as I can't reproduce the issue on 16.04 or 14.04 currently, with a new VM. I'm guessing this was a temporary issue caused by Vagrant installing the older version of Ansible previously.

**Closed by geerlingguy** 2016-12-02 21:40 UTC
Labels: bug, windows

**Comment by farah0808** [comment] 2016-12-14 19:47
@geerlingguy Hi sorry, the Ansible version fix didn't fix my issue. Is that specifically for Windows? I'm using Mac and am trying to install a new box for Drupal 8. Should I open a new issue?

**Comment by geerlingguy** [comment] 2016-12-14 21:09
@farah0808 - Yes, please open a new issue and post the exact error and other details; it is likely something different (but could be related).
