### ISSUE TITLE
Task firewall config does not complete

### ISSUE THREAD

**Issue by carnnia** [geerlingguy/drupal-vm#829] opened 2016-07-26 17:14 UTC
## Fix

If you're on Windows and you cloned Drupal VM in a way that resulted in some files getting Windows line endings, it could be the line endings cause issues when you try to run `vagrant up` or `vagrant provision`. A quick fix:

1. Find `/drupalvm/provisioning/roles/geerlingguy.firewall/templates/firewall.j2`
2. Edit it in notepad++ and convert it to Unix format (LF)
3. Edit > EOL Conversion > UNIX Format
4. Save the file
5. Run `vagrant up` or `vagrant provision` again.

## Original Issue

the drupal folder that the documentation refers to is not generated. the synced folder that i put in config.yml is empty. the error printed to screen is:

TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable firewall: rc=1 firewall.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable firewall\nupdate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}

**Comment by carnnia** [comment] 2016-07-26 18:02
my host is windows7. here is the put put of vagrant up:
----------------START-----

ccarnnia@CST328169 MINGW64 /d/drupal-vm (master)
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => D:/drupal-vm
    drupalvm: /var/www/drupalvm => D:/drupal-vm/data
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [drupalvm]

TASK [Define config_dir.] ******************************************************
skipping: [drupalvm]

TASK [include_vars] ************************************************************
ok: [drupalvm] => (item=/vagrant/config.yml)

TASK [include] *****************************************************************
included: /vagrant/provisioning/tasks/init-debian.yml for drupalvm

TASK [Update apt cache if needed.] *********************************************
ok: [drupalvm]

TASK [Get software for Python-based control.] **********************************
changed: [drupalvm] => (item=[u'curl', u'python-apt', u'python-pycurl', u'build-essential', u'sudo', u'unzip'])

TASK [Disable the ufw firewall (since we use a simple iptables firewall).] *****
changed: [drupalvm]

TASK [Add repository for Apache 2.4 on Ubuntu 12.] *****************************
skipping: [drupalvm]

TASK [Add repository for PHP 5.5.] *********************************************
skipping: [drupalvm]

TASK [Add repository for PHP 5.6.] *********************************************
skipping: [drupalvm]

TASK [Add repository for PHP 7.0.] *********************************************
skipping: [drupalvm]

TASK [Define php_xhprof_html_dir.] *********************************************
skipping: [drupalvm]

TASK [include] *****************************************************************
skipping: [drupalvm]

TASK [Run configured pre-provision shell scripts.] *****************************

TASK [Run configured pre-provision ansible task files.] ************************

TASK [Set the PHP webserver daemon correctly when nginx is in use.] ************
skipping: [drupalvm]

TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
skipping: [drupalvm]

TASK [geerlingguy.repo-remi : Import remi GPG key.] ****************************
skipping: [drupalvm]

TASK [geerlingguy.firewall : Ensure iptables is installed (RedHat).] ***********
skipping: [drupalvm]

TASK [geerlingguy.firewall : Ensure iptables is installed (Debian).] ***********
ok: [drupalvm]

TASK [geerlingguy.firewall : Flush iptables the first time playbook runs.] *****
changed: [drupalvm]

TASK [geerlingguy.firewall : Copy firewall script into place.] *****************
changed: [drupalvm]

TASK [geerlingguy.firewall : Copy firewall init script into place.] ************
changed: [drupalvm]

**TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable firewall: rc=1 firewall.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable firewall\nupdate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}**

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=10   changed=5    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

----------------END-------

**Comment by geerlingguy** [comment] 2016-07-26 19:05
@carnnia 

> the drupal folder that the documentation refers to is not generated.

The part of Drupal VM that builds the drupal site via composer doesn't run until a little later in the build process.

> firewall Default-Start contains no runlevels, aborting.

Can I ask what version of Drupal VM are you running, and also what version of Vagrant and VirtualBox is installed? Also, can you give the output of `vagrant box list`?

One note—I haven't tested Drupal VM on Windows 7 in at least a year, and I'm not sure if anyone else using it on windows is still on 7 (I think there are some users... but everyone who helps with bugfixes/testing on Windows is at least on 8, mostly on 10), so I can't help much if it turns out there's something related to Windows 7...

**Comment by carnnia** [comment] 2016-07-26 19:35
i am now trying to install it on my ubuntu machine. i'll keep you informed.
back to windows:
Drupal VM: the latest, I guess. I just cloned the repo.
VirtualBox: Version 5.0.26 r108824
Vagrant: Vagrant 1.8.5
List of boxes:
ccarnnia@CST328169 MINGW64 /d/drupal-vm (master)
$ vagrant box list
geerlingguy/ubuntu1604 (virtualbox, 1.0.4)
precise32              (virtualbox, 0)

**Comment by geerlingguy** [comment] 2016-07-26 22:00
Okay, thanks, very helpful!

Also, does anything in this issue help? https://github.com/geerlingguy/drupal-vm/issues/695

Maybe try `vagrant provision` to see if the second run through works?

**Comment by oliperas** [comment] 2016-07-30 19:01
I have the same issue on win7 64 pro.

**Comment by geerlingguy** [comment] 2016-08-10 02:28
@oliperas - Can you try with `geerlingguy/ubuntu1404`? There are some differences between that box and the bento box.

**Comment by oliperas** [comment] 2016-08-10 05:36
Tried with geerlingguy/ubuntu1404

`TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on bo                                               ot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "failed                                                determining service state, possible typo of service name?"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=9    changed=6    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by geerlingguy** [comment] 2016-08-10 11:54
@oliperas - Just to confirm, are you on windows, and what version of Windows if so? Also, what version of Vagrant are you running (run `vagrant --version`).

**Comment by suryatp** [comment] 2016-08-15 17:57
Facing same problem..

TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on bo ot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "failed determining service state, possible typo of service name?"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************
to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm : ok=9 changed=6 unreachable=0 failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.


OS: windows 7 Enterprise Service Pack1.
Virtaul Box version: 5.1.2
vagrant version: 1.8.5
vagrant boxlist:  geerlingguy/ubuntu1404 (Virtualbox 1.1.3)
vagrant plugin list: vagrant -share (1.1.5, system)
                               vagrant -winnfsd (1.3.0)

**Comment by geerlingguy** [comment] 2016-08-16 19:44
I'm closing #695 and moving that conversation into this thread. For anyone having this problem, please post the following:

  1. Exact OS version you're using (e.g. Windows 7, 8, 10)
  2. The step where the build fails.
  3. Any config.yml customizations (especially which `vagrant_box` you're using).
  4. Versions of Vagrant, VirtualBox and Drupal VM being used.

**Comment by suryatp** [comment] 2016-08-16 20:14
Brock, just FYI. I shall post it as a new ticket.
--
Best regards,
Surya Paruchuri

**Comment by geerlingguy** [comment] 2016-08-16 20:17
So, using the following environment, all fresh/brand new installs, I can't replicate the issue:

  1. Windows 10
  2. Cygwin
  3. N/A - success with all defaults
  4. No config.yml customizations (using all defaults)
  5. Vagrant 1.8.5, VirtualBox 5.1.2, Drupal VM 3.2.0

**Comment by suryatp** [comment] 2016-08-16 20:21
So do I have to move-on to windows 10 to install drupalvm? Cannot I run it
on windows 7 and yes I think I am using a custom config.yml file.

--
Best regards,
Surya Paruchuri

**Comment by stevepurkiss** [comment] 2016-08-16 20:25
OK so seems I hadn't done a 'sudo apt-get upgrade' & 'sudo apt-get dist-upgrade' on my linux laptop for a while - just done that now and it's running through fine. 

So perhaps that's the issue on yours, can't remember how cygwin works, seem to remember it runs linux within windows so perhaps the version of linux it's running needs some updates.

**Comment by geerlingguy** [comment] 2016-08-16 20:59
@suryatp - Drupal VM _should_ work on Windows 7... but I don't have access to any computers with that old a version of Windows, and I only know one person with quick access to a Windows 8 laptop, so I can only reliably test things in a Windows 10 environment.

**Comment by brockfanning** [comment] 2016-08-16 21:28
I'm happy to help test Windows 7. However, I can't recreate the problem. Here are my stats:

1. OS: Windows 7 Professional, service pack 1
2. Shell: Babun (wrapper around Cygwin, I believe)
3. NA (doesn't fail)
4. No significant config.yml changes from the default (interestingly, I happen to be using the exact same config.yml as suryatp, who posted above and is experiencing the problem)
5. Vagrant 1.8.4, Virtual Box 5.0.24, DrupalVM cloned from Github on July 31

Like I said, it's working for me. But if anyone wants me to try anything to recreate it, just let me know and I'll give it a shot.

**Comment by stephanebelazouz** [comment] 2016-08-17 17:04
I have solved this issue by adding:
sudo: yes

behind task 
- name: Ensure the firewall is enabled and will start on boot of file
povisioning/roles/geerlingguy.firewall/tasks/main.yml

**Comment by geerlingguy** [comment] 2016-08-17 18:24
@stephanebelazouz - That's really strange, because the entire playbook should be run under the sudo user, because of the line `become: yes` at the top of the main playbook: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/playbook.yml#L3

When you add the `sudo: yes` do you get any warnings? Also, if you take it out and run `vagrant provision` again does it still succeed?

**Comment by stephanebelazouz** [comment] 2016-08-17 18:54
You right, this is make no sense  because of the become: yes...
So after another test with fresh install it's seems to work perfectly.

Thx for your job and your time.

**Comment by jpmc** [comment] 2016-08-17 19:24
Exact OS version you're using: **Windows 7 Pro SP1**
Which terminal/CLI you're using: **Cmder 160724 stable**
The step where the build fails: **"TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.]"**
Any config.yml customizations (especially which vagrant_box you're using): **Drupal core version 7, hostname , and machine_name updates.**
Versions of Vagrant, VirtualBox and Drupal VM being used:

- Vagrant 1.8.5

- VirtualBox Version 5.0.26 r108824

- Drupal VM up to commit 84e0ed145817ee7acfe7f0bd04af917bca8dedb9 (git cloned from the GitHub page)

The error I run into specifically is 

> fatal: [betterpt]: FAILED! => {"changed": false, "failed": true, "msg": "Job for firewall.service failed because the control process exited with error code. See \"systemctl status firewall.service\" and \"journalctl -xe\" for details.\n"}

**Comment by jpmc** [comment] 2016-08-17 19:29
I just destroyed and re-provisioned it and now get a new error.

> fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable firewall: rc=1 firewall.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable firewall\nupdate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}

After getting this the first time, it goes back to the control process error code message from my previous post.

**Comment by brockfanning** [comment] 2016-08-18 02:52
I tried a couple of things to recreate the problem:
1. Upgraded to Vagrant 1.8.5
2. Instead of Babun/Cygwin just ran "vagrant up" in the normal Windows cmd.exe.
Still no luck recreating it - still no errors.

**Comment by GBirch** [comment] 2016-08-18 03:26
Same problem:
Windows 10 Pro 64-bit (should be SP1, but I don't see it)
Virtualbox: 5.0.26 r108824
Vagrant: 1.8.5
Box: geerlingguy/ubuntu1604 1.0.4
config.yml and config.local.yml attached.

[drupal-vm-config.zip](https://github.com/geerlingguy/drupal-vm/files/424078/drupal-vm-config.zip)

TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [massforms8vm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable firewall: rc=1 firewall.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable firewall\nupdate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}

**Comment by GBirch** [comment] 2016-08-18 03:46
Same error with custom config removed.  If it helps, I attach the results of "vagrant provision" run after I removed the custom config.
[provisioning.txt](https://github.com/geerlingguy/drupal-vm/files/424098/provisioning.txt)

**Comment by rjgwiz** [comment] 2016-08-23 01:44
I had the same firewall errors on `vagrant up` and `vagrant provision`, running Windows 7 with the latest versions of Drupal VM/Vagrant/Virtual Box, and [https://github.com/geerlingguy/drupal-vm/issues/832#issuecomment-236153465](this comment from 832) fixed it for me:

- Find /drupalvm/provisioning/roles/geerlingguy.firewall/templates/firewall.j2
- Edit it in notepad++ and convert it to Unix format (LF)
     - Edit > EOL Conversion > UNIX Format

**Comment by suryatp** [comment] 2016-08-23 16:48
Thank you @rjgwiz . That worked like magic. Thanks a lot. Shall keep posting the progress.

**Comment by GBirch** [comment] 2016-08-25 20:42
Worked for me too.   Thanks @rjgwiz !

**Comment by GBirch** [comment] 2016-08-25 20:42
Would a .gitattributes file that forced LF checkouts resolve this problem?

**Comment by jcowher** [comment] 2016-08-30 20:51
Not sure if this host-system specific as I am OS X El Capitan (10.11.6) and I received the same error.  Works fine for me on `geerlingguy/ubuntu1404`, but not on `geerlingguy/ubuntu1604`.

**Comment by chumkui** [comment] 2016-09-02 13:34
Same for me - I tried to build on a Windows 8.1 laptop as I was travelling and got the Firewall message.  My Windows 10 desktop machine builds fine  - both are set up identically using builds of vagrant (1.8.5) and Virtual box (5.0.26).  Both are using identical build sets from our own repo.  Doing the EOF conversion to Unix worked on my Win 8.1 laptop for me... weird.

**Comment by deserted** [comment] 2016-09-05 06:44
getting the same error here, systemctl list-unit-files shows no firewall.service file, and the firewall init script in /etc/init.d gives the following error on call
`bash: /etc/init.d/firewall: /bin/sh^M: bad interpreter: No such file or directory`

Running on Windows 10 x64, fresh install with Git Bash  as the shell, error below

`
TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable firewall: rc=1 firewall.service is not a native service, redirecting to systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable firewall\nupdate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}
`

**Comment by sourabhm** [comment] 2016-09-06 23:40
Thanks @rjgwiz for the solution and the steps to apply the solution. Your solution (EOL conversion) fixed my problem. My environment was:
1. OS: Win 10 Enterprise x64
2. Shell: Cmder (running cmd.exe in admin mode)
3. Error: No error
4. Vagrant 1.8.5, VirtualBox 5.1.2, Drupal VM 3.2.1

**Comment by natgateway** [comment] 2016-09-14 03:41
I've just started playing with drupal-vm on a windows 10 machine; I'm in the process of translating a mac os vagrant setup into a windows compatible one and I ran into the same firewall error as the others here have. The EOL conversion suggested by @rjgwiz  got me past the firewall error as well, I'm on a windows 10 pro environment using powershell, virtualbox 5.1.4, vagrant 1.8.5.

**Comment by codexmas** [comment] 2016-09-14 18:34
Can also confirm that switching to ubuntu1404 allowed the build to pass the firewall error.
macOS Sierra, fresh install of vagrant, virtualbox, and ansible via brew

**Comment by geerlingguy** [comment] 2016-09-17 20:51
I've updated the top comment, and will point others with the issue there (thanks @rjgwiz!). This should help anyone running into the issue on Windows. On Mac, it could be something else... so if people keep running into this issue, we can open a new issue to investigate further.

**Closed by geerlingguy** 2016-09-17 20:51 UTC
Labels: question, windows

**Comment by Bertjuh** [comment] 2016-10-13 11:42
Hi,

With the default configuration and the previous drupal-vm version (downloaded oct 11, 2016) all is fine. This morning I downloaded the master branch again -because of release 3.4.0- and now I get this issue with the firewall. I tried the fix as suggested but those line endings are already Unix endings. So that fix does not work for this version. 

Versions:
Windows 7 (yup, I'm one of those, can't change that anytime soon i'm afraid)
Vagrant version 1.8.6
Virtualbox version 5.1.6

Any suggestions would be great! Thanks

**Comment by wturrell** [comment] 2016-10-25 10:23
**Fails** on macOS (El Capitan 10.11.6), Vagrant 1.8.6, VirtualBox 5.0.28, latest Ansible 2.3.0 devel branch, latest geerlingguy/drupal-vm (Oct 22, 1e942fb), standard /bin/bash shell.  

```
TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}

```

Re-running `vagrant provision` makes no difference.

**Fixed** after replacing Ansible 2.3.0 devel with stable version (2.1.2.0 from homebrew) followed by `vagrant provision`.

(actually it now fails at **Generate Drupal project with composer package** with a "Content-Length mismatch" error when downloading something, will create a separate issue for that one.) 

If I can help with further debugging, let me know.

**Comment by geerlingguy** [comment] 2016-10-26 19:41
@wturrell - I don't support the latest devel branch of Ansible, as there's often a lot of experimentation that goes on in there—right now around `service` module and some of it's internals—and so I like to wait to target new stable releases.

Often these bugs are either fixed by the next minor release, or in a quick followup bugfix release, so there's no use for me to try fixing it in all my roles where things are broken with HEAD. Hopefully Ansible keeps getting more stable over time as more tests are added :)

**Comment by geerlingguy** [comment] 2016-10-26 19:42
That said, this would be something that could be pursued in a bug report against Ansible core if it's reproducible on devel but not on stable 2.1.

**Comment by geerlingguy** [comment] 2016-11-01 21:14
Hmm... Now I'm hitting this with Ansible 2.2.0 :( Opening a new issue: #958

**Comment by cdmo** [comment] 2017-01-10 18:08
Using Windows 7, cmder, centos7 box.

Changing line endings made no difference.

Making sure this was in `config.yml` did:
`drupalvm_ansible_version_min: '2.1'`

Didn't work under:
`drupalvm_ansible_version_min: '2.2'`

**Comment by cdmo** [comment] 2017-01-10 18:28
There's a web of related issues here, but I thought I'd report back that my firewall errors and my postgresql errors are gone when I merged in the latest from `master`. Gracias.

**Comment by geerlingguy** [comment] 2017-01-10 19:35
Interesting, thanks for posting!

**Comment by nikolabintev** [comment] 2017-01-19 08:02
I have the same problem:

`TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [netnod]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}
	to retry, use: --limit @/Users/nbintev/Projects/netnod/provisioning/playbook.retry

PLAY RECAP *********************************************************************
netnod                     : ok=9    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

I've changed the box to: geerlingguy/ubuntu1404, and it works for me, but it doesn't solve the issue.


I'm running on:
OS: Mac OS x 10.12.2
Vagrant: 1.8.6
ansible: 2.2.0
Virtual box: 5.1.8
