### ISSUE TITLE
Timed out while connecting to the machine via SSH (the machine shows as Running in VBox)

### ISSUE THREAD

**Issue by lex0r** [geerlingguy/drupal-vm#1678] opened 2018-01-30 16:19 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (version)

### Full console output

```
c:\drupal-vm>vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Summary

So it just times out, This issue is a duplicate of once closed https://github.com/geerlingguy/drupal-vm/issues/1639 (couldn't find a way to re-open, sorry). Re-installing Vagrant/VirtualBox didn't help.

**Comment by geerlingguy** [comment] 2018-02-01 15:16
Do you have any custom or overridden configuration in a `config.yml` file? Have you changed `vagrant_ip` by chance? And are you on a network with a VPN, corporate firewall, or proxy server? Usually a timeout means there's a networking issue.

The only other thing I could think of is an older VirtualBox version. Can you find out what version of VirtualBox you're running?

**Comment by geerlingguy** [comment] 2018-02-01 15:16
Also, what version of Windows are you running?

**Comment by hissDev** [comment] 2018-02-06 22:13
No sure if it helps.. i ran into this on a ubuntu 14. when checking the network settings (UI) of the vbox image while it hangs, i check the “Cable Connect” checkbox of the two Adapters and it continues.

**Comment by lex0r** [comment] 2018-02-07 12:27
@geerlingguy It's on latest VBox.

> Do you have any custom or overridden configuration in a config.yml file? Have you changed vagrant_ip by chance? And are you on a network with a VPN, corporate firewall, or proxy server? Usually a timeout means there's a networking issue.

The answer is "no" to each of the above questions.

However, seems the issue is not present on the latest drupalvm. So, the issue happened in geerlingguy-drupal-vm-4.7.1-0-ga604401 but doesn't happen any more in geerlingguy-drupal-vm-4.8.0-0-g0ca883a. I would suggest reviewing the diff, as it might give a clue.

**Comment by Rufus13apostol** [comment] 2018-02-12 11:44
HI there,

Same issue here. I have : 

- Virtualbox Versión 5.2.6 r120293 (Qt5.6.1)
- vagrant 2.0.2
- ansible 2.4.3.0
- ubuntu 16.04
- geerlingguy/ubuntu1604

I'm running through a corporate proxy, but I could not find any configuration advice regarding this. Any insights? Here the errors:
$ **vagrant up**

Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm: flag to force provisioning. Provisioners marked to run always will still run.

==> drupalvm: Machine 'drupalvm' has a post `vagrant up` message. This is a message
==> drupalvm: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm: 
==> drupalvm: Your Drupal VM Vagrant box is ready to use!
==> drupalvm: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm.test (or http://192.168.88.88)
==> drupalvm: * You can SSH into your machine with `vagrant ssh`.
==> drupalvm: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com

$ **vagrant provision**
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.3.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    drupalvm: Running ansible-playbook...
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [drupalvm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}
	to retry, use: --limit @/home/rafav/Escritorio/Drupal_projects/Vagrant/drupal-vm-master/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=0    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by Rufus13apostol** [comment] 2018-02-12 11:47
Modification: I found the proxysettings and put it in vagrantfile, but it seems it does not work neither:
# The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.box = "geerlingguy/ubuntu1604"
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://user:pass@proxy.com:8080/"
    config.proxy.https    = "http://user:pass@proxy.com:8080/"
    vagrant plugin install vagrant-proxyconf
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

**Comment by stkrzysiak** [comment] 2018-02-20 03:04
FWIW, I had ssh issues as well. This was completely abnormal behavior for VirtualBox in my experience w/ it, and it had been a while since I did an update so I went ahead and updated VirtualBox & my extensions and everything worked. Also, prior to experiencing the SSH issue, I had issues with the box not being found(I was using vagrant 1.9.2 so I updated that as well). I followed the instructions to delete the box after the vagrant upgrade, and then ran into the SSH issue.

**Comment by RodenHirata** [comment] 2018-04-24 23:14
When I get this, I first make sure visualisation is turned on in the BIOS. Then I type "vagrant plugin uninstall vagrant-hostsupdater" and then "vagrant provision drupalvm" followed by "vagrant up" (of course). Not sure why, but the hostsupdater makes it so I can't connect via HTTP or SSH (even though I can ping it). Just remember to edit the hosts file manually from now on.

**Comment by StoppingBuck** [comment] 2018-11-28 12:51
I have the exact same issue running Arch Linux. I don't even have a custom `config.yml` but just leave the `default.config.yml` in place and don't customize anything at all.

Vagrant 2.2.1
VirtualBox: 5.2.22r126257
vagrant-hostsupdater (1.1.1.160, global)
vagrant-vbguest (0.16.0, global)
No ansible installed

The only steps to reproduce is literally
1) Run Arch Linux and install the requirements
2) Clone the drupal-vm repo
3) Follow the default instructions (i.e. just run `vagrant up`)

**Comment by geerlingguy** [comment] 2018-12-01 21:06
@StoppingBuck - Ah, good catch! So on AMD it could be a different setting. On Intel machines it's typically 'VT-x', and on most consumer-grade laptops and desktops it is disabled by default :(

I'm going to go ahead and close this issue, as there are a number of different potential fixes already listed. If you (the reader of this issue) have the same problem and find a solution though, please feel free to follow-up here!

**Closed by geerlingguy** 2018-12-01 21:06 UTC
Labels: question, windows
