### ISSUE TITLE
local.config.yml setting not respected

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#675] opened 2016-05-27 15:29 UTC
As a test, I created a local.config.yml with

`php_memory_limit: "192M"`

Reloaded the machine, and the memory limit is still 256M.

**Comment by comdico** [comment] 2016-05-27 16:50
Similarly, I set the php version to 5.6 and followed directions in wiki for Ansible but my vm is still using php 7.

**Comment by geerlingguy** [comment] 2016-05-27 17:06
@kevinquillen - A couple questions:

  - Are you on 3.0.0?
  - Did you run `vagrant provision` or `vagrant reload --provision`, or just `vagrant reload`?

**Comment by kevinquillen** [comment] 2016-05-27 17:08
Yep 3.0.0, and vagrant reload --provision

**Comment by kevinquillen** [comment] 2016-05-27 17:48
I also did vagrant reload prior to that.

**Comment by geerlingguy** [comment] 2016-05-31 03:50
Our automated tests also cover this use case, and would fail (it looks like) if the override weren't working. I just tested locally and it seems to work okay for me too... could it be that there's something missing? Can you check out an entirely new copy of Drupal VM and see if you can reproduce the issue?

**Comment by oxyc** [comment] 2016-06-01 22:03
@kevinquillen was this fixed together with https://github.com/geerlingguy/drupal-vm/issues/674?

**Comment by geerlingguy** [comment] 2016-06-02 22:33
Going to close this and hope it was fixed :)

**Closed by geerlingguy** 2016-06-02 22:33 UTC
Labels: question
