### ISSUE TITLE
Install fails on composer step: Install configured globally-required packages.

### ISSUE THREAD

**Issue by kdborg** [geerlingguy/drupal-vm#961] opened 2016-11-02 16:42 UTC
On OS X 10.11.6 (El Capitan), I'm using VirtualBox 5.1.8, the latest DrupalVM with the default configuration.  When I run vagrant up, it goes through everything fine until this line:

TASK [geerlingguy.composer : Install configured globally-required packages.] ***
failed: [drupalvm] (item={u'release': u'^0.3', u'name': u'hirak/prestissimo'}) => {"changed": true, "cmd": "COMPOSER_HOME=/home/vagrant/.composer /usr/bin/composer global require hirak/prestissimo:^0.3 --no-progress", "delta": "0:00:05.527304", "end": "2016-11-02 16:37:17.592121", "failed": true, "item": {"name": "hirak/prestissimo", "release": "^0.3"}, "rc": 1, "start": "2016-11-02 16:37:12.064817", "stderr": "Changed current directory to /home/vagrant/.composer\n./composer.json has been created\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n\nInstallation failed, deleting ./composer.json.\n\n                                            \n  [Composer\\Downloader\\TransportException]  \n  Content-Length mismatch                   \n                                            \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", "stdout": "", "stdout_lines": [], "warnings": []}

This could be related to: https://github.com/geerlingguy/drupal-vm/issues/930
I tried this with the 'php_install_recommended: no' and still got the issue.

**Comment by geerlingguy** [comment] 2016-11-02 21:09
This is a duplicate of https://github.com/geerlingguy/drupal-vm/issues/941 — note the error message:

```
[Composer\Downloader\TransportException]
Content-Length mismatch
```

See, specifically, this issue on drupal.org: https://www.drupal.org/node/2823695

**Closed by geerlingguy** 2016-11-02 21:09 UTC
Labels: duplicate

**Comment by kdborg** [comment] 2016-11-02 22:11
Sorry.

**Comment by kdborg** [comment] 2016-11-05 15:40
I do like DrupalVM.  It's a very nice system for using VMs.

I want to give you an update.  I've done three things in order to get Drupal VM up and running with the latest master:

1) To get past the prestissimo issue, I add a /home/vagrant/.composer/config.json file with the following contents:
{
  "repositories": {
    "packagist": {
      "type": "composer",
      "url": "https://packagist.org"
    }
  }
}

2) Comment out adminer so it doesn't provision.

3) Comment out the drupalconsole so it doesn't provision.

4) Don't let the machine provision via composer.
