### ISSUE TITLE
FCGI: attempt to connect to 127.0.0.1:9000 failed

### ISSUE THREAD

**Issue by christopher-hopper** [geerlingguy/drupal-vm#1996] opened 2019-12-05 05:40 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.6
VirtualBox 6.0.12r133076
ansible not installed
```

### Your OS

 - **macOS** 10.14.6

### Full console output

 

```
[Thu Dec 05 04:48:17.563833 2019] [proxy:error] [pid 8038:tid 140318494144256] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Thu Dec 05 04:48:17.564517 2019] [proxy_fcgi:error] [pid 8038:tid 140318494144256] [client 10.20.1.1:51005] AH01079: failed to make connection to backend: 127.0.0.1
```

After 

After completing provision of the machine, using the Acquia BLT recipe, 
the dashboard.drupalvm.local works fine, but the Drupal website returns an HTTP 503 error 
with the above log message shown in Apache.

Seems to be a problem with php-fpm Apache SetHandler / proxy? I mean I don't know, I'm going on some troubleshooting articles I looked at. There's also this in your issue queue:

- https://github.com/geerlingguy/ansible-role-apache-php-fpm/issues/4
- https://github.com/geerlingguy/ansible-role-apache-php-fpm/issues/7

**Comment by nikunjkotecha** [comment] 2019-12-06 17:37
It seems something changed in www.conf and regexp rules are no longer valid, we are facing this for provisions done in last couple of weeks.

**Comment by clarentinarebello** [comment] 2019-12-10 05:18
I updated the listen variable (/etc/php/7.3/fpm/pool.d/www.conf) to the direct address instead of the value that was already there as a workaround to get my box running again.

`;listen = /run/php/php7.3-fpm.sock`
`listen = 127.0.0.1:9000`

**Comment by ejanus** [comment] 2019-12-12 02:16
I've been referenced from my prior issue: https://github.com/acquia/blt/issues/3948

I've tried the above suggestion for the `listen` setting. Unfortunately, this is not solving it for me. 
Also, note, I completely re-provisioned my MacBook in order to try and see if a fresh start would help. 
I'm currently running VirtualBox 6.0.14 if that helps. Vagrant up (my Acquia BLT project fired) didn't work with 6.1 so I downgraded. 

This appears to have began within the last 5 or so weeks. 

Please refer to the issue I referenced above for my machine and other details. 

I am able to get things working on my Ubuntu 18 box.

**Comment by NJWong** [comment] 2019-12-16 23:43
The above workaround from @clarentinarebello seems to have worked for me

**Comment by danepowell** [comment] 2019-12-17 21:35
The latest version of VirtualBox is 6.0.14, you should probably update, although it seems somewhat unlikely to cause this.

What base box are you using (BLT supports several)? Have you updated the box lately and reprovisioned so that the new base box gets picked up? Have you tried completely nuking your VM (`blt vm:nuke`) and initializing a new one from BLT's default box/config.yml?

I've tried both `geerlingguy/drupal-vm` and `geerlingguy/ubuntu1604` and cannot reproduce this issue using a fresh BLT install and VM. My `www.config` is set to `listen = 127.0.0.1:9000` out of the box, so I'd assume that's desired. Furthermore, you should be getting PHP 7.2 out of the box with BLT, while the file referenced above mentions PHP 7.3. This all suggests that you aren't using the stock VM provided by BLT, or perhaps your VM config is out of date.

**Comment by dipakmdhrm** [comment] 2019-12-27 10:19
I was able to solve this by changing:

`apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>`

to 

`apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:unix:/run/php/php{{ php_version }}-fpm.sock|fcgi://{{ php_fpm_listen }}"
    </FilesMatch>`

Got the hint from here:
https://serverfault.com/questions/594020/using-proxypassmatch-for-fastcgi-results-in-connection-refused-on-port-9000

Though I am not sure what might be causing this.
I tried searching the cause and the only thing that I found that _might_ cause this would be the following change in apache version 2.4.28 (https://www.apachelounge.com/Changelog-2.4.html):

`core: Disallow multiple Listen on the same IP:port when listener buckets
     are configured (ListenCoresBucketsRatio > 0), consistently with the single
     bucket case (default), thus avoiding the leak of the corresponding socket
     descriptors on graceful restart.  [Yann Ylavic]`

But I would advise the grain & salt thingy for this.

**Comment by christopher-hopper** [comment] 2020-02-27 05:47
I think I may have been able to replicate the issue on a colleagues macOS computer. It seems that when we don't have Ansible installed on the host computer, a file at `/etc/php/7.3/fpm/pool.d` doesn't get created properly. Instead, a file is created locally with a jinja2 variable name in it. The variable isn't replaced in the path name.

When we installed Ansible on the host macOS computer, the provisioning finishes correctly and the proper paths and files are modified.

**Comment by christopher-hopper** [comment] 2020-02-27 06:06
I guess this is a problem with one of the following:

- The way Ansible is installed on the guest VM when you don't have Ansible on the host
- The Jinja2 variable substitution syntax used here for `{{ php_fpm_conf_path }}/pool.d`

Perhaps one isn't compatible with the other? I couldn't find an obvious problem in the geerlingguy/ansible-role-php code:

https://github.com/geerlingguy/ansible-role-php/search?q=php_fpm_conf_path

**Comment by christopher-hopper** [comment] 2020-02-27 06:15
Could be related to this:
https://github.com/ansible/ansible/issues/64169 

When installed on the host macOS computer I get Ansible 2.7.10. 

```
# ansible --version
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/chopper/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]

# pip --version
pip 19.3.1 from /Users/chopper/Library/Python/3.7/lib/python/site-packages/pip (python 3.7)

# python --version
Python 3.7.6
```

**Comment by geerlingguy** [comment] 2020-02-27 15:48
@christopher-hopper - Good sleuthing; I may just need to tag a new release of Drupal VM with all the latest role updates (which may solve this issue by using a 2.9.x-compatible method). There have been a few and I've just put off tagging a release in case I wanted to make any larger changes.

Related: https://github.com/geerlingguy/drupal-vm/issues/2015

**Comment by geerlingguy** [comment] 2020-02-27 18:06
I believe this should be fixed, so I'm going to close this issue (upgrade to 5.1.1 to make sure you're running all the latest code).

**Closed by geerlingguy** 2020-02-27 18:06 UTC
