### ISSUE TITLE
Provisioning sometimes fails on update apt cache task

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1038] opened 2016-12-06 21:22 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox
5.0.26r108824
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.1)

### Summary

Lately, when doing a vagrant up, or reload provision, I get this error:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [pncb]

TASK [Define config_dir.] ******************************************************
skipping: [pncb]

TASK [include_vars] ************************************************************
ok: [pncb] => (item=/Users/kevinquillen/Servers/pncb.org/tools/drupalvm/config.yml)

TASK [include] *****************************************************************
included: /Users/kevinquillen/Servers/pncb.org/tools/drupalvm/provisioning/tasks/init-debian.yml for pncb

TASK [Update apt cache if needed.] *********************************************
fatal: [pncb]: FAILED! => {"changed": false, "failed": true, "msg": "Could not fetch updated apt files"}
	to retry, use: --limit @/Users/kevinquillen/Servers/pncb.org/tools/drupalvm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
pncb                       : ok=3    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Immediately retrying the command works. Any thoughts as to what can cause this?

**Comment by geerlingguy** [comment] 2016-12-06 22:31
@kevinquillen - It seems like your version of VirtualBox is out of date; can you upgrade to VirtualBox 5.1.10 (or later) and try again?

**Comment by geerlingguy** [comment] 2016-12-06 22:32
(Also might want to upgrade to Ansible 2.2.x too).

**Comment by oxyc** [comment] 2017-02-28 22:17
@kevinquillen are you still having these issues or can we close this issue?

**Comment by geerlingguy** [comment] 2017-02-28 23:17
And upgrade to Vagrant 1.9.2 :)

Closing for now, we can re-open if you find it still happening after getting upgraded.

**Closed by geerlingguy** 2017-02-28 23:17 UTC
Labels: question

**Comment by christinevk** [comment] 2017-03-01 20:50
I'm getting the same error message (after hanging for 15 minutes or so), but not on 'vagrant up', only on 'vagrant provision'.  Ansible is 2.2.1, VB is 5.1.14 and vagrant is 1.9.2.

**Comment by IchristineI** [comment] 2017-03-01 21:06
This might be the cause of it: "the machine <machinename> is already locked for a session (or being unlocked)" but I can't destroy the session.

**Comment by IchristineI** [comment] 2017-03-02 17:47
Came back to it today and it was unlocked again and 'vagrant provision' worked.  Not sure in the future how to gracefully destroy if vagrant manager can't destroy the session itself.  Sorry to hop on this thread, hoping this can be helpful to someone who has the same issue.

**Comment by simesy** [comment] 2017-05-17 00:55
See to be getting this with a new machine running.
```
vboxmanage 5.1.22r115126
ansible 2.3.0.0
Vagrant 1.9.4
```

**Comment by thom8** [comment] 2017-05-17 02:39
@simesy this is usually due to a networking issue, you may not have access to the apt repo from your network. try `vagrant ssh` then `sudo apt-get update` to see if it works.

**Comment by simesy** [comment] 2017-05-17 02:49
When it failed we managed to get past the issue by doing `sudo apt-get update` in the VM. It's weirdly intermittent. I have another error to paste... just getting it from the dev.

**Comment by thom8** [comment] 2017-05-17 03:12
> weirdly intermittent

So most likely going to be network issues, you should be able to consistently replicate it by disconnecting and running `vagrant provision`

**Comment by simesy** [comment] 2017-05-17 03:45
Yes but does that explain why `apt-get update` works?

For the record:
```
TASK [Add repository for PHP versions (Ubuntu).] *******************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_kU5AEY/ansible_module_apt_repository.py\", line 565, in <module>\r\n    main()\r\n  File \"/tmp/ansible_kU5AEY/ansible_module_apt_repository.py\", line 553, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 454, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: E:Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/a0645de208f8bb005d4a3764253b3230209ca29ed2b0fb0acd114ee52b395b19  Hash Sum mismatch, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by geerlingguy** [comment] 2017-05-17 03:52
@simesy - Often things like `Hash Sum mismatch` mean some upstream mirror is currently syncing... I have hit this many times with `yum`/`dnf`, but seemingly not as often with `apt` under Ubuntu.

**Comment by thom8** [comment] 2017-05-17 03:56
Yep, last time I ran into `Has Sum mismatch` it was actually my ISP cache, worked fine on a mobile connection and fixed itself overnight when the cache cleared..

**Comment by marcelovani** [comment] 2021-09-17 20:39
Upgrading Ansible worked for me
