### ISSUE TITLE
Build the Virtual Machine on windows failed

### ISSUE THREAD

**Issue by scottwan** [geerlingguy/drupal-vm#504] opened 2016-03-07 13:13 UTC
Build the Virtual Machine on Windows failed, message as below:

==> drupalvm: TASK [geerlingguy.mysql : Update apt cache if MySQL is not yet ins
talled.] *****
==> drupalvm: fatal: [localhost]: FAILED! => {"changed": false, "failed": true,
"msg": "Could not fetch updated apt files"}
==> drupalvm:   to retry, use: --limit @/vagrant//provisioning/playbook.retry
==> drupalvm:
==> drupalvm: PLAY RECAP *******************************************************
**************
==> drupalvm: localhost                  : ok=51   changed=0    unreachable=0
 failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by geerlingguy** [comment] 2016-03-07 13:42
Do you happen to be on a corporate network with a proxy?

**Comment by scottwan** [comment] 2016-03-07 14:54
Yes, it is, but it is same when I turned off proxy and run "vagrant up" and "vagrant provision" again.

**Comment by geerlingguy** [comment] 2016-03-21 01:48
It seems like the apt repos simply can't be reached; can you log in with `vagrant ssh` then inside the VM manually run `sudo apt-get update` and see what it says?

**Comment by scottatdrake** [comment] 2016-03-31 00:45
I received the same message on OSX. Home network, no proxy. Here is the end of of the output of hte `sudo apt-get update` command. 

```
Fetched 1,085 kB in 10s (101 kB/s)
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-i386/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by kaba** [comment] 2016-04-01 08:45
I had this problem also in OSX, but it disappeared when I changed my country in my VPN.

**Comment by geerlingguy** [comment] 2016-04-04 22:29
This seems like a network or upstream apt/distro issue... I'm going to close this particular issue as I can't reproduce it, but please leave any more notes/clues/fixes here for the benefit of others who may run into the issue.

**Closed by geerlingguy** 2016-04-04 22:29 UTC
Labels: question, windows
