### ISSUE TITLE
ansible-galaxy fails during install for PHP 5.6.

### ISSUE THREAD

**Issue by WiseUA** [geerlingguy/drupal-vm#974] opened 2016-11-07 15:33 UTC
Hi, I￼ execute  `vagrnt up` and see this error :
TASK [Install postfix so Drupal can send emails.] ******************************
ok: [inf]

TASK [Add repository for PHP 5.5.] *********************************************
skipping: [inf]

TASK [Add repository for PHP 5.6.] *********************************************
fatal: [inf]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}
	to retry, use: --limit @/home/developer/projects/xxx/provisioning/playbook.retry

PLAY RECAP *********************************************************************
inf                        : ok=5    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Yesterday everything worked!**

**Comment by geerlingguy** [comment] 2016-11-07 15:45
See related: https://github.com/geerlingguy/drupal-vm/issues/971

It looks like Ondrej's PPA has deprecated and removed the php5-5.6 repo entirely, so the updates are here:

  - https://github.com/geerlingguy/drupal-vm/commit/e7f01690dc70322797c9eb5cee5959ed0b154f62
  - https://github.com/geerlingguy/ansible-role-php/issues/158

And I'm going to mark this as a duplicate of https://github.com/geerlingguy/drupal-vm/issues/971

**Closed by geerlingguy** 2016-11-07 15:45 UTC

**Comment by WiseUA** [comment] 2016-11-07 16:05
Thank you! It's works.
