### ISSUE TITLE
Drupal VM Docker 'install-drupal' command fails to install Drupal

### ISSUE THREAD

**Issue by hmartens** [geerlingguy/drupal-vm#1692] opened 2018-02-10 08:47 UTC
### Issue Type
Support Request

### Your Environment

Running Docker on Macos High Sierra

### Your OS
 - **macOS** high sierra

### Summary

I installed Docker on my mac. 

Then I installed Drupalvm with the command:
`docker run -d -p 80:80 -p 443:443 --name=drupalvm --privileged geerlingguy/drupal-vm`

I added this in my hosts file:

> 192.168.89.89  drupalvm.test

I then ran this command:
`sudo ifconfig lo0 alias 192.168.89.89/24`

Then I try to run this command:
`docker exec drupalvm install-drupal`

But it then says:

> "Downloading Drupal 8.4.x
> The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:"

Then I tried to run it with this command:
`docker container run docker exec drupalvm install-drupal`

That seems to give more results as it seems to be downloading and installing stuff but then it gives me an error:

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

All I want for now is to run a standard drupal installation in my docker drupalvm. After this I will attend to get our project's Acquia codebase to run in there.

**Comment by geerlingguy** [comment] 2018-02-14 21:39
(Ignore the above commits—I mis-attributed them to this issue and don't want to break commit history by amending).

I'll take a look; the problem is that when I shifted all the Drush functionality to use Drush Launcher by default, I didn't test out the docker install-drupal command. It will need to be changed at least a little to work correctly now that drush is not able to bootstrap itself (via a globally installed version) by default.

**Comment by i-bajrai** [comment] 2018-02-26 18:33
I am experiencing this as well, I will try to figure out a work around and report back.

**Comment by geerlingguy** [comment] 2018-03-01 20:51
Pasting full command output here:

```
$ docker exec drupalvm install-drupal
Downloading Drupal 8.4.x
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.
```

One option is we could still install Drush globally on the Docker image. Another option is to update the `install-drupal` script to first install Drush via Composer... then install Drupal. Or set up the Drupal codebase using Git + Composer (or just Composer)...

**Comment by geerlingguy** [comment] 2018-03-01 22:09
Using composer:

```bash
#!/bin/bash
#
# Install a Drupal site with Drush.
#
# Usage:
#   install-drupal [version]
# [version] is optional, defaults to 8.x-dev. Try 7.x-dev, 7.55, 8.4.2, etc.

# Exit on any individual command failure.
set -e

# Setup.
DRUPAL_VERSION="${1:-8.x-dev}"
PROJECT_PATH='/var/www/drupalvm'

# Create Drupal project directory.
mkdir -p $PROJECT_PATH

# Create a Drupal project.
echo "Downloading Drupal $DRUPAL_VERSION"
cd $PROJECT_PATH
composer create-project drupal-composer/drupal-project:$DRUPAL_VERSION drupal --stability dev --no-interaction

# Install Drupal with Drush.
echo "Installing Drupal"
drush si standard --root=$PROJECT_PATH/web -y \
  --db-url='mysql://drupal:drupal@localhost/drupal' \
  --site-name='Drupal VM' \
  --account-name=admin --account-pass=admin

# Set appropriate permissions.
chown -R www-data:www-data $PROJECT_PATH
```

This process takes many minutes, though... kind of the antithesis to 'get up and running quickly'.

I'm going to test replacing the global drush launcher install with a drush 8.x composer global install, and see how that goes.

**Comment by geerlingguy** [comment] 2018-03-01 22:16
Meh... I'm thinking about maintainability—it seems like the hacky way of keeping around a Drush 8.x version and replacing drush launcher is probably not going to work 5 years from now, whereas using composer alone should _probably_ continue working... therefore sticking with the above (modified a bit for usability).

**Comment by geerlingguy** [comment] 2018-03-01 22:46
See above commit for a fix: https://github.com/geerlingguy/drupal-vm/commit/50300e4b63714de47b7a51660f68443e53502e7b

**Comment by geerlingguy** [comment] 2018-03-01 23:20
Merged! It should start working next time the Docker image is pushed (in a few min).

**Closed** 2018-03-01 23:20 UTC
Labels: bug, docker
