### ISSUE TITLE
Timed out while connecting to the machine via SSH (the machine shows as )

### ISSUE THREAD

**Issue by lex0r** [geerlingguy/drupal-vm#1677] opened 2018-01-30 16:19 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (version)

### Full console output

```
c:\drupal-vm>vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Summary

So it just times out, This issue is a duplicate of once closed https://github.com/geerlingguy/drupal-vm/issues/1639 (couldn't find a way to re-open, sorry).

**Comment by geerlingguy** [comment] 2018-01-30 19:25
Looks like this is a duplicate of #1678, so closing this one.

**Closed by geerlingguy** 2018-01-30 19:25 UTC
