### ISSUE TITLE
Vagrant 1.8.x failures with Windows 10

### ISSUE THREAD

**Issue by nick-vanpraet** [geerlingguy/drupal-vm#361] opened 2015-12-25 16:51 UTC
Host: Windows 10
Latest Vagrant
Latest VirtualBox (test build 5.0.x revision 104829 - see https://www.virtualbox.org/ticket/13665 bottom)

When I run `vagrant up`, it errors out

```
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1404' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1404'
    drupalvm: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1404
==> drupalvm: Adding box 'geerlingguy/ubuntu1404' (v1.0.7) for provider: virtualbox
    drupalvm: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1404/versions/1.0.7/providers/virtualbox.box
    drupalvm: Progress: 100% (Rate: 3711k/s, Estimated time remaining: --:--:--)    drupalvm:
==> drupalvm: Successfully added box 'geerlingguy/ubuntu1404' (v1.0.7) for 'virtualbox'!
==> drupalvm: Importing base box 'geerlingguy/ubuntu1404'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => C:/Users/Nick/sandbox/drupal-vm-master
    drupalvm: /var/www/drupalvm => C:/wamp/www/sandbox
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-galaxy...
Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/bin/ansible-galaxy", line 765, in execute_install
    f = open(role_file, 'r')
IOError: [Errno 2] No such file or directory: 'c:/vagrant/provisioning/requirements.yml'
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

If I try to continue, the following error occurs

```
$ vagrant provision
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* `playbook` does not exist on the guest: c:/vagrant/provisioning/playbook.yml
* `galaxy_role_file` does not exist on the guest: c:/vagrant/provisioning/requirements.yml
```

It correctly starts executing the ansible_local after detecting the host doesn't have it, but for some reason it adds "c:/" to the path, as if it was still searching the host instead of the guest.

I'm a total noob when it comes to VMs, Vagrant and I'd never even heard of Ansible before this afternoon, so if you need any more info ask away and I'll do my best to provide it.

The vagrant server is up and running, I can ping it and ssh into it. But the setup can't go beyond the ansible part.

**Comment by geerlingguy** [comment] 2015-12-26 04:23
You might want to stick to Drupal VM version [2.1.2](https://github.com/geerlingguy/drupal-vm/releases/tag/2.1.2) right now (and maybe also download/downgrade Vagrant to 1.7.x instead of 1.8.0.

The 1.8.0 release had a few Windows quirks, and until 1.8.1 is released I'm going to hold off on releasing a new version of Drupal VM.

It looks like the above issue is that the Vagrant folder share isn't being configured/mounted correctly, thus the Linux guest and Ansible local provisioner isn't finding the playbook that's supposed to be inside the VM. I'm going to do some more testing on Windows 10 myself after Christmas, hopefully I'll find some way to get things working with Vagrant 1.8.0.

**Comment by geerlingguy** [comment] 2015-12-26 06:15
I'm updating the title and generalizing this issue based on feedback from #360 pointing to some bugs in Vagrant 1.8.x (e.g. https://github.com/mitchellh/vagrant/issues/6733).

**Comment by illepic** [comment] 2015-12-26 09:48
Looks like I'm back up and running on Vagrant 1.8.1 and Windows 10 by doing the following:

1. Uninstall Vagrant and VirtualBox
2. Restart Windows
3. Reinstall Vagrant 1.8.1 and VirtualBox 5.0.12
4. Restart Windows

None of my `vagrant up`s fail anymore.

Which filesystem are you using? Even though I'm on Windows, I'm using the default NFS filesystem (if that matters).

**Comment by illepic** [comment] 2015-12-26 21:34
Rolling back to:

1. [Vagrant 1.74](https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4.msi)
2. [VirtualBox 5.0.10](http://download.virtualbox.org/virtualbox/5.0.10/VirtualBox-5.0.10-104061-Win.exe)
3. [Drupal VM 2.1.2](https://github.com/geerlingguy/drupal-vm/tree/2.1.2)

The `geerlingguy/centos7` box simply no longer boots with a `config.yml` [that worked prior](https://gist.github.com/illepic/b1d421d636c4f2ddac13).

The [full debug is here](https://gist.github.com/illepic/5affd13b3e7811afbb66).

The only reason I'm opening this up on the Drupal VM project and not the Vagrant project is that all the tools are in a prior working state as of a couple weeks ago (Vagrant 1.7.4, VirtualBox 5.0.10, Drupal VM at tag 2.1.2), leaving the CentOS7 box outstanding factor. I think?

**Comment by geerlingguy** [comment] 2015-12-26 21:55
Strange... I haven't touched or rebuilt the centos7 box since a few days after the release of VirtualBox 5.0.10, and any configuration that worked with that combo should still be working now—are you 100% sure you're on Drupal VM 2.1.2?

One recent change in Drupal VM (https://github.com/geerlingguy/drupal-vm/commit/27dca1678fc577e49bdd8c3f5d675609360d6560) would possibly cause issues with older versions of Vagrant on Windows 10 (but _shouldn't_!), but that's not in the 2.1.2 release.

**Comment by itsgreggmarshall** [comment] 2016-01-02 12:21
I'm also having issues with Windows 10, Vagrant 1.8.1, VirtualBox 5.0.10r104061 and Drupal VM 2.1.2 release using the example config and make files (renamed).  It's getting quite a ways but fails at installing Drupal:

==> drupalvm: TASK: [Install Drupal with drush.] ********************************************
==> drupalvm: failed: [localhost] => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.875019", "end": "2016-01-01 18:11:39.167328", "rc": 255, "start": "2016-01-01 18:11:38.292309", "warnings": []}
==> drupalvm: stderr: require(/var/www/drupalvm/drupal/vendor/guzzlehttp/guzzle/src/functions_include.php):  [warning]
==> drupalvm: failed to open stream: No such file or directory autoload_real.php:54
==> drupalvm: PHP Fatal error:  require(): Failed opening required '/var/www/drupalvm/drupal/vendor/guzzlehttp/guzzle/src/functions_include.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/drupalvm/drupal/vendor/composer/autoload_real.php on line 54
==> drupalvm: Drush command terminated abnormally due to an unrecoverable error.       [error]
==> drupalvm: Error: require(): Failed opening required
==> drupalvm: '/var/www/drupalvm/drupal/vendor/guzzlehttp/guzzle/src/functions_include.php'
==> drupalvm: (include_path='.:/usr/share/php:/usr/share/pear') in
==> drupalvm: /var/www/drupalvm/drupal/vendor/composer/autoload_real.php, line 54
==> drupalvm:
==> drupalvm: FATAL: all hosts have already failed -- aborting
==> drupalvm:
==> drupalvm: PLAY RECAP ********************************************************************
==> drupalvm:            to retry, use: --limit @/root/playbook.retry
==> drupalvm:
==> drupalvm: localhost                  : ok=162  changed=86   unreachable=0
 failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Before that the attached failures occurred (I put them in a file to keep this comment more manageable, the entire output string is in the log file, just in case it is useful).
[drupalvm_errors.txt](https://github.com/geerlingguy/drupal-vm/files/76217/drupalvm_errors.txt)
[drupalvm_log.txt](https://github.com/geerlingguy/drupal-vm/files/76218/drupalvm_log.txt)

**Comment by itsgreggmarshall** [comment] 2016-01-02 16:13
In my case downgrading to Vagrant 1.7.4 did not help at all.

**Comment by geerlingguy** [comment] 2016-01-02 21:48
Taking a look now. So far I'm unable to replicate just with the makefile changes, but I'm rerunning everything from scratch a couple more times.

@itsgreggmarshall - Can you completely delete the 'drupal' folder (wherever it's being installed on your host) and try provisioning again?

**Comment by itsgreggmarshall** [comment] 2016-01-03 03:03
@geerlingguy That solved the problem, thanks.

**Comment by geerlingguy** [comment] 2016-01-03 03:16
Okay, in this case... I'm thinking the main issues recounted in here are somewhat related to other open issues, and also somewhat resolved by the latest updates to Vagrant and VirtualBox for Windows. I'm also planning on building new base box versions with the latest guest additions ASAP, so that won't be an issue.

Closing this issue tentatively.

**Closed by geerlingguy** 2016-01-03 03:16 UTC
Labels: question, windows

**Comment by RuJohnson** [comment] 2016-01-07 21:58
I am getting the first post's problem on Windows 7, Vagrant 1.8.1, VirtualBox 5.0.10, DrupalVM latest. When I use Vagrant 1.7.x, VirtualBox 5.0.10, and DrupalVM 2.1.2 then everything works fine. If you want me to test on Windows in the future, please let me know. Thank you

**Comment by justinlevi** [comment] 2016-01-25 18:59
I can confirm that downgrading to the following solves the issue for me:  
* Vagrant 1.8.1, 
* DrupalVM 2.1.2
* VirtualBox Version 5.0.14 r105127

Thanks to @itsgreggmarshall for the details :+1:

**Comment by geerlingguy** [comment] 2016-01-25 19:17
@justinlevi - Thanks for posting that! Hopefully when Vagrant 1.8.2 is released, everything will work out of the box again.

**Comment by justinlevi** [comment] 2016-01-25 20:31
Running into a new issue now that I'm trying to debug. Seems that apache is not rendering PHP files correctly. I'm trying to troubleshoot further but everything seems to be working as expected. Will create a new issue and report back on what I find. 

I'm trying to find where
`LoadModule php...` is getting called but I'm not sure what file I should find this in. Doesn't seem to be a httpd.conf file and can't seem to find that anywhere? 

Any ideas?

**Comment by geerlingguy** [comment] 2016-01-25 21:04
@justinlevi - Please see the release notes: https://github.com/geerlingguy/drupal-vm/releases/tag/2.2.1

If you would like to revert back to using mod_php instead of FPM, you can do so by destroying your VM, then following the instructions above the php FPM settings in example.config.yml: https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L202-L204

**Comment by itsgreggmarshall** [comment] 2016-01-25 21:27
I applied the two patches referenced in #372 and got a working VM.

My patched provisioner for ansible that is located at C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\provisioners is attached.
[ansible.zip](https://github.com/geerlingguy/drupal-vm/files/103996/ansible.zip)
