### ISSUE TITLE
How to make Drupal 8 Update Manager work with Vagrant/DrupalVM

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#879] opened 2016-08-23 13:54 UTC
When I click "Install New Module" and fill in the link for a module that I copied from drupal.org I get
"Failed to connect to the server. The server reports the following message: Cannot connect to FTP Server, check settings For more help installing or updating code on your server, see the handbook. WARNING: You are not using an encrypted connection, so your password will be sent in plain text. Learn more.
To continue, provide your server connection details" after I click Install.

I'm running D8 under Vagrant/DrupalVM. I entered my login ID & password that I use to login as admin on D8.

**Comment by geerlingguy** [comment] 2016-08-27 03:05
Hmm... to be honest, I've never used the Update Manager system in Drupal to update a module—I always download and place the module in the directory, use Drush, or use Composer to manage the codebase.

I might try it out and see if there's a simple fix or something like that.

**Comment by ColumbiaBlooms** [comment] 2016-08-27 14:44
I had a similar problem using UwAmp. The solution is below. Maybe there's a similar problem with DrupalVM?

As you know, I am a newbie. Please explain why the below fixed the problem in UwAmp and what's going on. In other words, what is the context? I often find fixes like this, but no general explanation to help me learn Drupal. Thanks!

Found the solution at https://www.drupal.org/node/2654474#comment-11553625 

In my case I had to add a "certs" folder to C:\UwAmp\bin\apache\conf\ then download the cacert.pem to that certs folder. I also had to add "curl.cainfo = C:\UwAmp\bin\apache\conf\certs\cacert.pem" to my php.ini file using the UwAmp GUI.

**Comment by geerlingguy** [comment] 2016-09-29 02:17
h2. Steps to reproduce

  1. Fresh download of Drupal VM (installs latest D8 version).
  2. `vagrant up` and wait
  3. `cd` into `drupal` dir and run `composer require drupal/honeypot:8.1.22` (old release)
  4. `drush @drupalvm.drupalvm.dev en -y honeypot update` to enable Honeypot and Update Status module
  5. `drush @drupalvm.drupalvm.dev uli` to log into site's UI
  6. Visit `/admin/reports/updates` to see list of available updates.
... (ongoing)

**Comment by geerlingguy** [comment] 2016-09-29 02:39
So... I guess the problem is Drupal VM doesn't install any kind of FTP system (since it's a lot less secure than SFTP, and uploading modules via FTP is not the best way to update Drupal or contrib projects—rather, the machine provides both Composer-based and Drush make-based install methods, both of which make it a lot easier to manage contrib modules (just increment the required version number).

Alternatively, since Drupal VM installs and configures Drush, updating a module is as easy as `drush @[alias-goes-here] dl modulename`, and that would be a better option than the update manager...

I'm going to close this issue, as the Update Manager works for all other aspects (listing updates, showing current versions, security releases, etc.), just not the FTP upload; I won't be adding an FTP server to Drupal VM as it's an insecure manner of module management and there are multiple other ways of dealing with updates that are both faster and more secure.

Someday it may be possible to use Update Manager in a more secure fashion—but I'm not getting my hopes up too much... look at all the issues in that queue: https://www.drupal.org/project/issues/drupal?text=update+ftp

**Closed by geerlingguy** 2016-09-29 02:39 UTC
Labels: question

**Comment by steveansell** [comment] 2019-11-14 15:56
This  feature request is still something that would be extremely useful.

**Comment by wdseelig** [comment] 2020-05-16 20:19
Does this mean that update.php asks Drupal to use ftp to "push" the new module down to the requesting system, whereas Drush, operating from the receiving system, "pulls" it in?
