### ISSUE TITLE
Slow gulp watch

### ISSUE THREAD

**Issue by subhojit777** [geerlingguy/drupal-vm#1154] opened 2017-02-04 18:13 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.2)

### Full console output

N/A

### Summary

The gulp watch trigger is very slow (almost dead) when I edit the file from host machine. Sometimes it takes around 1-2 minutes to trigger the watch, and sometimes it does not gets triggered.

If I am editing the file from the VM itself, the trigger is quick.

I have tried using the mount options as given here https://github.com/gulpjs/gulp/issues/448 but it is not working for me. Any idea how it can be fixed?

**Comment by geerlingguy** [comment] 2017-02-04 18:43
@subhojit777 - I'm on a similar environment (just using 10.12.3), and am using the configuration included with Acquia's Cog theme (as a subtheme), and triggers are fired within a few _ms_ of any file save.

Are you running the `gulp watch` command inside the VM, or outside. I've found that if I'm editing files outside the VM on the host, it works most reliably to run `gulp` outside the VM as well. If editing inside the VM, run `gulp` inside.

It sounds like something is delaying the file write operation inside the VM maybe.

**Comment by subhojit777** [comment] 2017-02-04 20:41
@geerlingguy 

> I'm on a similar environment (just using 10.12.3), and am using the configuration included with Acquia's Cog theme (as a subtheme), and triggers are fired within a few ms of any file save.

Jeff, are you running the `gulp watch` inside host?

> Are you running the gulp watch command inside the VM, or outside.
I am running the `gulp watch` inside VM and editing the file in host.

This issue https://github.com/gulpjs/gulp/issues/448 asks to try editing the file in VM and execute `gulp watch`, I tried that and the response was instantaneous.

I haven't tried, but I am pretty sure that the `gulp watch` response when executed inside host will be quick.

**Comment by subhojit777** [comment] 2017-02-06 06:00
As a workaround, I am running `gulp watch` inside the host, and the `watch` is triggered in an instant (as expected).

It would be great if the issue is fixed in the VM itself.

**Comment by subhojit777** [comment] 2017-02-06 06:03
Appreciate the quick response 👍 Thank you for this great tool.

**Comment by oxyc** [comment] 2017-02-08 14:10
Another option would be to use eg `gulp-watch` where you can pass `usePolling` to `chokidar`.

https://github.com/floatdrop/gulp-watch/issues/213#issuecomment-169238160

**Comment by oxyc** [comment] 2017-02-28 22:13
As this issue has a few workarounds mentioned and there's not really any way to fix the cause on our side, I'll close this issue.

**Closed by oxyc** 2017-02-28 22:13 UTC
Labels: question
