### ISSUE TITLE
Drupal VM freeze after time in Idle using WinNFSd 

### ISSUE THREAD

**Issue by daje4197** [geerlingguy/drupal-vm#2132] opened 2021-01-19 11:23 UTC
Hallo @geerlingguy, 
do u have a solution for my Problem?
im pretty new to Ubuntu and dont know what to do.
every time i use "vagrant up" its loads a lot more that by my friend.
i suggest it has to do something with the WinNFSd but i dont know how to fix it
can you help me ? 
Regards

=====================================================
WinNFSd 2.4.0 [5f7f224]
Network File System server for Windows
Copyright (C) 2005 Ming-Yang Kao
Edited in 2011 by ZeWaren
Edited in 2013 by Alexander Schneider (Jankowfsky AG)
Edited in 2014 2015 by Yann Schepens
Edited in 2016 by Peter Philipp (Cando Image GmbH), Marc Harding
=====================================================
Path #1 is: C:/Drupalvmv2, path alias is: /C/Drupalvmv2
Path C:/Drupalvmv2 with path alias /C/Drupalvmv2 already known
Portmap daemon started
NFS daemon started
Mount daemon started
Listening on 0.0.0.0
Type 'help' to see help

Path C:/Drupalvmv2 with path alias /C/Drupalvmv2 already known
Path C:/Drupalvmv2 with path alias /C/Drupalvmv2 already known
Path C:/Drupalvmv2 with path alias /C/Drupalvmv2 already known
Path C:/Drupalvmv2 with path alias /C/Drupalvmv2 already known

λ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Checking if box 'geerlingguy/drupal-vm' version '2.0.10' is up to date...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
[drupalvm] GuestAdditions seems to be installed (6.1.16) correctly, but not running.
update-initramfs: Generating /boot/initrd.img-4.15.0-112-generic
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 4.15.0-112-generic.
update-initramfs: Generating /boot/initrd.img-4.15.0-112-generic
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
Restarting VM to apply changes...
==> drupalvm: Attempting graceful shutdown of VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
==> drupalvm: Machine booted and ready!
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit nfs mounting file.
[NFS] Status: halted
[NFS] Start: started
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm: flag to force provisioning. Provisioners marked to run always will still run.
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test

==> drupalvm: Machine 'drupalvm' has a post `vagrant up` message. This is a message
==> drupalvm: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm:
==> drupalvm: Your Drupal VM Vagrant box is ready to use!
==> drupalvm: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm.test (or http://192.168.88.88)
==> drupalvm: * You can SSH into your machine with `vagrant ssh`.
==> drupalvm: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com

C:\Drupalvmv2
λ

**Comment by geerlingguy** [comment] 2021-01-19 18:01
Marking as duplicate of https://github.com/geerlingguy/drupal-vm/issues/2126

**Closed by geerlingguy** 2021-01-19 18:01 UTC
Labels: question, upstream, vagrant, windows
