### ISSUE TITLE
Variable lost after inspection in debugger

### ISSUE THREAD

**Issue by penance316** [geerlingguy/drupal-vm#1050] opened 2016-12-13 12:18 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.1
VirtualBox 5.0.14r105127
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)

### Full console output

 $node->field_price
 [7]

 $node->field_price
 NULL

### Summary

I am unsure if this is expected behaviour as I am relatively new to the environment but every time I inspect a variable in the IDEA/PHPStorm console the 2nd time I inspect it seems to have been set to null.

 $node->field_price
 [7]

 $node->field_price
 NULL

Setup: Intellij IDEA, Xdebug, DrupalVM, Drupal 8, PHP 5.3

Perhaps this is a drupal/php issue i am not sure but i dont get the issue when running plain old php.

Any help is greatly appreciated.

**Comment by geerlingguy** [comment] 2016-12-16 17:30
@penance316 - This sounds more like an Xdebug/PHPStorm issue than something able to be fixed by Drupal VM... but can you give any more details on the exact steps to reproduce, so maybe someone else can see if they can reproduce the issue?

**Comment by geerlingguy** [comment] 2016-12-28 17:05
Closing this for now - please reopen if you can trace it any further or give a verifiable set of steps to reproduce. Since I can't reproduce the issue, and haven't seen it before, it might be something project-specific. (Also, especially if it's Drupal Commerce-related... that could have something to do with it?).

**Closed by geerlingguy** 2016-12-28 17:05 UTC
Labels: question
