### ISSUE TITLE
Issue with Drupal 8's run-test.sh script

### ISSUE THREAD

**Issue by jasonpartyka** [geerlingguy/drupal-vm#198] opened 2015-08-14 19:51 UTC
Hi,

I'm having difficulty running some tests locally using your Vagrant configuration. It's not reporting test results failure and I am getting different reports when I run the tests in CLI versus browser. I've documented a lot of the issues here:

https://www.drupal.org/node/2505499#comment-10222443

Not sure if it is related to your vagrant configuration or an issue with my code, but YesCT and xjm thinks they may be (but don't hold them to that :-) )

**Comment by geerlingguy** [comment] 2015-08-14 19:56
I'll take a look. It _could_ be a file permissions issue, if some of the tests are trying to save/change files on the filesystem.

Can you add 'steps to reproduce' (e.g. build Drupal VM with a Drupal 8 site, log in, run command `xyz`, observe error) so I can do the same thing and see what happens, and dig into it?

**Comment by geerlingguy** [comment] 2015-08-26 13:50
To reproduce:

  1. Boot Drupal VM with a Drupal 8 site.
  2. Vagrant SSH to log in.
  3. `cd /var/www/drupal`
  4. `php core/scripts/run-tests.sh --all`

I'm doing a test run now.

**Comment by geerlingguy** [comment] 2015-08-27 02:47
Notable portions of the results:

```
$ php core/scripts/run-tests.sh --all

Drupal test run
---------------

All tests will run.

Test run started:
  Wednesday, August 26, 2015 - 13:49

Test summary
------------
...
FATAL Drupal\system\Tests\Cache\ApcuBackendUnitTest: Found no database prefix for test ID 96. (Check whether setUp() is invoked correctly.)Drupal\system\Tests\Cache\BackendChainUnitTest               149 passes
Drupal\config\Tests\ConfigFormOverrideTest                    16 passes   2 fails
Drupal\config\Tests\DefaultConfigTest                        257 passes   1 fails
Drupal\system\Tests\DrupalKernel\ContainerRebuildWebTest      15 passes   2 fails
Drupal\system\Tests\File\DirectoryTest                        37 passes   2 fails   1 exceptions
Drupal\system\Tests\File\RemoteFileDirectoryTest              37 passes   2 fails   1 exceptions
Drupal\system\Tests\Installer\InstallerExistingDatabaseSetti   9 passes   9 fails   1 exceptions
Drupal\system\Tests\Module\InstallUninstallTest              1547 passes   8 fails
Drupal\node\Tests\NodeCacheTagsTest                          379 passes   4 fails   2 exceptions
Drupal\KernelTests\KernelTestBaseTest                         10 passes   1 fails
Drupal\rest\Tests\Views\StyleSerializerTest                  207 passes   2 fails
...
Test run duration: 6 hours 29 min
```

(That was with the tests run with Drupal running inside an NFS share).

**Comment by geerlingguy** [comment] 2015-08-27 02:55
If I move the site root out from the shared NFS directory, into a location like `/tmp/drupal`, and rerun the tests, I get thousands of exceptions, so it seems it could be related to where the site is living on the filesystem.

I just re-ran core tests on the NFS share again, and only the few exceptions noted in the comment above occurred again, so both scenarios are easily reproducible.

**Comment by geerlingguy** [comment] 2015-08-27 03:29
I also ran `$ php core/scripts/run-tests.sh --class "Drupal\config\Tests\ConfigFormOverrideTest"` (to re-run the config tests and see if the failure was reproducible), and got `2 fails` again. So running it with XML output, I get:

```
    <testcase classname="Drupal\config\Tests\ConfigFormOverrideTest" name="testFormsWithOverrides()">
        <failure type="failure" message="Other">Page title &amp;#039;Site information | Drupal&amp;#039; is equal to &amp;#039;Site information | Site name global conf override&amp;#039;.</failure>
    </testcase>
...
    <testcase classname="Drupal\config\Tests\ConfigFormOverrideTest" name="testFormsWithOverrides()">
        <failure type="failure" message="Other">Page title &amp;#039;Site information | Drupal&amp;#039; is equal to &amp;#039;Site information | Site name global conf override&amp;#039;.</failure>
    </testcase>
```

If I run the test directly in the Simpletest UI, I get a green '18 passes'.

I checked file permissions on settings.php, even set them to 777 so anyone could write to the file, but those two fails still happened, and I'm not sure why.

But at least most tests pass through CLI :)

**Comment by geerlingguy** [comment] 2015-08-27 03:33
@jasonpartyka - It definitely seems to be some sort of permissions or user-based issue, but running with or without `sudo` seems to not have made a difference. I'm going to try to run as the web user too (`www-data`) and see what happens.

**Comment by geerlingguy** [comment] 2015-08-27 03:57
Even running as same user Apache uses (which works via the web simpletest runner), I'm getting the same fails (used command: `$ sudo -u www-data php /var/www/drupal/core/scripts/run-tests.sh --class "Drupal\config\Tests\ConfigFormOverrideTest"`).

**Comment by geerlingguy** [comment] 2015-08-27 04:04
And additionally, when I run using SQLite with the site not actually running (Installed support with `apt-get install -y sqlite php5-sqlite`), I get an additional number of fails and exceptions.

**Comment by esclapes** [comment] 2016-02-19 09:10
I am also finding false negatives when running some module tests with run-test.sh. Any idea where to start debugging?

**Comment by geerlingguy** [comment] 2016-02-23 23:12
Taking a look at this now. I'm wondering if it's related to file permissions/using a synced folder as the folder from which the `run-tests.sh` script is run. I'm going to test it installing Drupal inside VM, and outside (in the default synced folder) and see if that makes any difference.

Note that running tests within Drupal's GUI seems to work in my limited testing. Might also be good to see if all core tests pass if run from within the web interface.

**Comment by geerlingguy** [comment] 2016-02-24 03:32
Forgot to set better resource limits in the VM, so restarting with the following tests:

| Test | Drupal install location | Result |
| ---- | -------------------- | ------ |
| `php core/scripts/run-tests.sh --concurrency 4 --all` | NFS share | - |
| `php core/scripts/run-tests.sh --concurrency 4 --all` | VM native | - |

**Comment by geerlingguy** [comment] 2016-02-24 05:00
Running all the tests via NFS share, so far all green... maybe this is not an issue anymore? I ran into a few 'data in message table too long / right truncated' MySQL errors for the `simpletest` table... but those seem to be unrelated, and the messaging is still showing all passes.

**Comment by esclapes** [comment] 2016-02-24 13:28
Hy @geerlingguy, thanks for looking into this. I updated the box, and provisioned again with 2.3.1. 

At the end, I believe the errors I was getting where caused by missing composer dependencies in the installed contrib modules. It was a good oportunity to keep up to date with new development over here.

**Comment by geerlingguy** [comment] 2016-02-24 16:28
Hmm... still got a few errors when running through the NFS share... will run inside the VM's filesystem and see how that goes.

**Comment by geerlingguy** [comment] 2016-02-24 16:52
I'm going to close this issue—after exhaustive testing, it seems that everything runs fine in the web UI but not in the terminal, and I'm 99% sure after debugging a few of the specific failing tests that it has to do with file directory permissions/simpletest—all the exceptions I could track on the command line (which didn't occur when running the same tests in the UI) were permissions-related, usually with `mkdir()`.

**Closed by geerlingguy** 2016-02-24 16:52 UTC
Labels: question

**Comment by geerlingguy** [comment] 2017-06-15 04:38
So, just to add a bit more color, after I have spent the last couple hours digging into this again... it looks like when running the tests from the CLI, the creation of the `files/php/twig` directory is what fails time after time. I was checking what `mkdir()` was attempting, and it looks like:

```
sites/simpletest/29971530/files/php/twig
sites/simpletest/29971530/files/php
```

(Where `29971530` is the test ID).

Potentially related:

  - [Long Twig cache directories can cause failures on some filesystems](https://www.drupal.org/node/2606772)
  - [file_put_contents(sites/default/files/php/twig/.htaccess): failed to open stream: Permission denied](https://www.drupal.org/node/2856554)

Trying to see what's really happening here.

**Comment by geerlingguy** [comment] 2017-06-16 03:22
Success! At least inside the Drupal VM Docker container. I was trying to use `--verbose` to do some debugging... and as it turns out I had to do the following to make it actually work:

  - _Don't_ use `--verbose`; it causes mkdir and file write operations that fail, even if I run tests as root.
  - _Do_ run tests as the web user (in my case, `www-data` on Ubuntu).

So to summarize:

```
# This didn't work, had test passes but tons of exceptions:
php /var/www/drupalvm/drupal/web/core/scripts/run-tests.sh --verbose --module honeypot --url http://local.drupalhoneypot.com/

# This did work (and is in use now):
sudo -u www-data php /var/www/drupalvm/drupal/web/core/scripts/run-tests.sh --verbose --module honeypot --url http://local.drupalhoneypot.com/
```

**Comment by geerlingguy** [comment] 2017-06-16 03:27
Well, strangely, even if I use `--verbose` on Travis CI builds inside the same Docker container... the build passes. So I guess maybe try to run the script with an absolute path as the `www-data` user? That might be the trick.
