### ISSUE TITLE
Drupal Scaffold only works as root user

### ISSUE THREAD

**Issue by web-assistant** [geerlingguy/drupal-vm#1795] opened 2018-07-01 15:02 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
VirtualBox 5.2.6 
ansible 2.3.1.0
```

### Your OS

 - **Windows** (version)

### Summary

I am using `composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction` to create a Drupal project. The [scaffold files](https://github.com/drupal-composer/drupal-scaffold) never get created unless I'm logged in as the root user - both when installing and updating. Any ideas what I'm doing wrong? I've already tried everything in the thread [Missing folders and files](https://github.com/drupal-composer/drupal-project/issues/282), including running composer update.

This is also the case when running it manually by using the command `composer drupal:scaffold`, again it only works when logged in as root user via `sudo su`

My composer.json file is:
```
{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer/installers": "^1.2",
        "cweagans/composer-patches": "^1.6",
        "drupal-composer/drupal-scaffold": "^2.5",
        "drupal/console": "^1.0.2",
        "drupal/core": "~8.5.3",
        "drush/drush": "^9.0.0",
        "vlucas/phpdotenv": "^2.4",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3"
    },
    "require-dev": {
        "webflo/drupal-core-require-dev": "~8.5.3"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ],
        "files": ["load.environment.php"]
    },
    "scripts": {
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "@composer drupal:scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "@composer drupal:scaffold",
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/Commands/{$name}": ["type:drupal-drush"]
        },
        "drupal-scaffold": {
            "initial": {
                ".editorconfig": "../.editorconfig",
                ".gitattributes": "../.gitattributes"
            }
        }
    }
}
```

**Comment by geerlingguy** [comment] 2018-08-08 05:08
That's really strange—the same command is used when creating the default Drupal VM setup, though with a much different composer setup (no custom composer.json file)...

https://github.com/geerlingguy/drupal-vm/blob/93ddfe408c106b43eb972e6fd5be413fee92d18f/provisioning/roles/geerlingguy.drupal/tasks/build-composer-project.yml#L8-L16

**Comment by web-assistant** [comment] 2018-10-02 09:20
I get the error:

  [Exception]                                                                                                      
  Failed to download https://cgit.drupalcode.org/drupal/plain/web.config, https://cgit.drupalcode.org/drupal/plain/update.php, https://cgit.drupalcode.org/drupal/plain/sites/example.sites.php, https://cgit.drupalcode.org/drupal/plain/sites/example.settings.local.php, https://cgit.drupalcode.org/drupal/plain/sites/development.services.yml, https://c  
  git.drupalcode.org/drupal/plain/sites/default/default.settings.php, https://cgit.drupalcode.org/drupal/plain/sites/default/default.services.yml, https://cgit.drupalcode.org/drupal/plain/robots.txt, https://cgit.drupalcode.org/drupal/plain/index.php, https://cgit.drupalcode.org/drupal/plain/.htaccess     

If I switch to root user and run the command, it works fine. Very strange.

**Comment by geerlingguy** [comment] 2018-12-28 23:34
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!

**Closed by geerlingguy** 2018-12-28 23:34 UTC
Labels: question

**Comment by MPParsley** [comment] 2019-03-14 15:55
We're seeing the same error in our deployment.
Might be due to a server issue (cfr https://www.drupal.org/project/infrastructure/issues/2768583).


If we change our user agent it works, seems like we're blocked 😮by cgit.drupalcode.org

curl_setopt($_h, CURLOPT_USERAGENT, 'curl/7.64.0');
