### ISSUE TITLE
php proc_open doesn't work properly with the apache user.

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#1372] opened 2017-05-16 17:31 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.04)

### Summary

After switching to the centos7 box the environment indicator stopped working with git. I traced it down to something with the centos7 shell and the apache user. If I ran commands as the user by force it would work.

So from the vagrant box logged in as vagrant: *<edited>*
```
$ sudo su - -s '/bin/bash' -c 'which git' apache
```

Would work, but I couldn't actually switch over to the apache user. When I tried to run the same command in a php script from the browser the response would be null. When I ran the script with drush, it would work. Drush was using the vagrant user and accessing the script in the browser used the apache user. Everything is set to defaults (for Drupal 7). I switched nothing but the box back to ubuntu1604 and everything works.

**Comment by geerlingguy** [comment] 2017-05-16 19:52
So... what exactly is the issue—e.g. what are you trying to do that's not working? Is it the Environment Indicator module that's not working correctly under `centos7`?

**Comment by frob** [comment] 2017-05-16 20:10
Right, the environment indicator normally shows which git tag/branch is currently checked out. My workflow depends on this functionality. This works on ubuntu1604 but not on centos7. I can work around this by using ubuntu, but I would like this to work with centos7 as that is what we are running in production.

**Comment by geerlingguy** [comment] 2017-05-16 20:15
@frob - Can you point out where the Environment Indicator's logic is that requires this functionality to work a certain way? I haven't used it in a few years, and don't know what it's trying to do. But it's highly likely that it's something where CentOS 7's more secure / SELinux-protected paths are preventing the access, and it might be hard if EI is trying to do something like scan filesystem directories outside the apache docroot...

If you can provide some snippet of code to reproduce the error, that would be even better :) (just because I won't likely have the time to build a Drupal site, install and learn how to configure Environment Indicator, etc.)—I basically need a set of 'steps to reproduce', otherwise I don't know if any changes I make are helpful or not.

**Comment by frob** [comment] 2017-05-16 20:16
Sure, I'll have it within the hour.

**Comment by frob** [comment] 2017-05-16 20:32
This is the block that I was using to debug. Ripped off straight from the environment module, kicking and screaming.

```php
<?php
  $command = "whoami";
  $process = proc_open(
    $command,
    array(
      // STDIN.``
      0 => array("pipe", "r"),
      // STDOUT.
      1 => array("pipe", "w"),
      // STDERR.
      2 => array("pipe", "w"),
    ),
    $pipes
  );
  if ($process === FALSE) {
    die();
  }
  $stdout = stream_get_contents($pipes[1]);
  $stderr = stream_get_contents($pipes[2]);
  fclose($pipes[1]);
  fclose($pipes[2]);
  proc_close($process);
  var_dump($stderr);
  var_dump($stdout);

var_dump($database_suffix);
```

**Comment by oxyc** [comment] 2017-06-02 13:52
What the...

**Comment by frob** [comment] 2017-06-02 14:56
I realized I left the command as whoami, git status is the command that was causing issues. Sorry about that.

**Comment by oxyc** [comment] 2017-06-03 18:50
First off, this feature was removed upstream so it's not really an issue anymore. https://www.drupal.org/node/2636670

---

But now to debugging the issue. So the problem is that PATH is not set for which (reproducable with `env -u PATH which git`.

The issue is that php-fpm by default doesn't export the PATH variable, so child/external processes without a shell (`which` through apache user) wont havent access to it. There is however a PATH variable available, but as it's not exported child processes wont have access to it. I'm not sure if Debian does this differently or why it worked on Ubuntu. Might just be that `which` is weird on RedHat, it's pretty 

/etc/php-fpm.d/www.conf
```
; Clear environment in FPM workers
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
;clear_env = no

....

; Pass environment variables like LD_LIBRARY_PATH. All $VARIABLEs are taken from
; the current environment.
; Default Value: clean env
;env[HOSTNAME] = $HOSTNAME
;env[PATH] = /usr/local/bin:/usr/bin:/bin
;env[TMP] = /tmp
;env[TMPDIR] = /tmp
;env[TEMP] = /tmp
```

You can check which variables are exported by httpd with `proc_open('export -p')`

```
export HOME="/usr/share/httpd"
export OLDPWD
export PWD="/var/www/drupalvm/drupal/web"
export SHLVL="1"
export USER="apache" 
```

Some alternative fixes:

- Skip `which` because it sucks and is very unreliable across platforms. `command -v` would fix the issue as it's a builtin.
- edit `www.conf` and uncomment `env[PATH] = /usr/local/bin:/usr/bin:/bin`
- export the PATH before running which in `proc_open`: `proc_open('export PATH; which git')`

**Comment by oxyc** [comment] 2017-06-03 18:52
I'll close this as this was bad practice by the module to begin with and they've since removed the feature.

**Closed by oxyc** 2017-06-03 18:52 UTC
Labels: question

**Comment by frob** [comment] 2017-06-14 22:31
@oxyc Thank you for your detailed explanation. At least now I can fix this.

@oxyc can you elaborate a bit? What part of this is bad practice? And when did they remove this feature? Last I checked the code they [still have it](http://cgit.drupalcode.org/environment_indicator/tree/environment_indicator.module#n663).

**Comment by oxyc** [comment] 2017-06-14 23:16
> At least now I can fix this.

👍 

> What part of this is bad practice?

As the author says in the comment I link below, it's probably not a good idea to execute OS commands. Also `which` should apparently not be used with along with `php-fpm`. The PATH issue is not something specific to Drupal VM. It's better to use a builtin that doesn't fork, such as `command -v`.

> And when did they remove this feature? Last I checked the code they still have it.

Ah it seems it was dropped from the D8 version only https://www.drupal.org/node/2636670
