### ISSUE TITLE
Vagrant Virtualbox NFS / mounting issues

### ISSUE THREAD

**Issue by enapthine** [geerlingguy/drupal-vm#66] opened 2015-04-06 08:15 UTC
Ran into issues when mounting shares (NFS & not), eventually discovered was caused by differing VirtualboxGuestAdditions that wasn't being detected. Not specifically DrupalVM related, but worth documenting. This could be related to earlier bug report regarding NFS shares also, as it stalls at the same location.

Resolved with installing vbguest plugin via:

```vagrant plugin install vagrant-vbguest```

**Comment by stefanruijsenaars** [comment] 2015-04-06 14:15
I think I may have mounting issues as well, I am running into this issue: https://www.drupal.org/node/2234229

I wonder if replacing NFS with this could help? http://wolfgangziegler.net/auto-rsync-local-changes-to-remote-server#comments

**Comment by geerlingguy** [comment] 2015-04-06 14:26
@stefanruijsenaars - I've hit that issue as well, but not with Drupal VM: https://www.drupal.org/node/2234229#comment-9744087

You can always switch to rsync if you would rather try that sync method, but with the out-of-the-box configuration, the Drupal install will be written over if you put files into your local folder that's synced inside the VM.

To use rsync, just set the `type` of the synced folder to `rsync`. I'm hoping Vagrant will someday add two-way rsync out of the box, though!

@enapthine - I think I may add a Wiki page with NFS common problems and fixes; enough people have trouble with shared folders of all varieties, and simply keeping my VirtualBox boxes up to date isn't enough all the time (I hate how VirtualBox seems to cause problems every other version upgrade!)

**Comment by stefanruijsenaars** [comment] 2015-04-06 14:31
@geerlingguy  I think the solution in the link actually bypasses Vagrant synced folders completely, it's a script by fago that watches a directory for changes using inotify-tools and rsyncs the changes to a remote system via SSH. Supposedly it should be faster than NFS, see https://github.com/drunomics/syncd

**Comment by stefanruijsenaars** [comment] 2015-04-06 14:40
I reckon this is some kind of problem with permissions, now I had a Simpletest fail because it couldn't create a directory :)

**Comment by stefanruijsenaars** [comment] 2015-04-06 18:24
Which I fixed by adding the following to the synced folders section in the Vagrantfile:

    owner: "vagrant",
    group: "www-data",
    mount_options: ["dmode=775,fmode=664"]

**Comment by geerlingguy** [comment] 2015-04-23 21:03
I think I may just set up a Wiki page discussing NFS and Synced Folder troubleshooting, and we can work on adding relevant examples/fixes in there. It seems like half or more of the issues reported so far on this project have to do with synced folders.

Hopefully, someday, Vagrant will support out-of-the-box two-way rsync!

**Comment by geerlingguy** [comment] 2015-04-23 21:10
See: https://github.com/geerlingguy/drupal-vm/wiki/Syncing-Folders

**Closed by geerlingguy** 2015-04-23 21:10 UTC
Labels: question

**Comment by iainhouston** [comment] 2016-02-13 16:16
It seems that `root` can write to the sync'd folders but `vagrant` can't. Is that the intended behaviour?
