### ISSUE TITLE
Synced folder owner/group either admin / 1000 / solr but not vagrant

### ISSUE THREAD

**Issue by pdenooijer** [geerlingguy/drupal-vm#1170] opened 2017-02-15 14:25 UTC
### Issue Type
 - Bug Report

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.1.0
```

### Your OS
 - **Linux** (Fedora 25)

### Full console output
Example:
```
vagrant@beta:/var/www/drupalvm$ ls -la
total 660
drwxrwxr-x 20 solr solr   4096 Feb 15 13:56 .
drwxr-xr-x  5 root root   4096 Feb 15 13:34 ..
-rw-rw-r--  1 solr solr   8280 Jan  4 09:18 build-pre-commit.xml
-rw-rw-r--  1 solr solr   8877 Feb  6 09:29 build.xml
drwxrwxr-x  4 solr solr   4096 Jan  4 09:18 ci
-rw-rw-r--  1 solr solr   7850 Feb 15 12:36 composer.json
-rw-rw-r--  1 solr solr 410655 Feb 15 12:36 composer.lock
drwxrwxr-x  2 solr solr   4096 Feb 15 13:47 config
drwxrwxr-x  3 solr solr   4096 Jan 25 13:47 console
drwxrwxr-x  3 solr solr   4096 Jan 24 09:18 designs
drwxrwxr-x  3 solr solr   4096 Jan  4 09:18 doc
drwxrwxr-x  4 solr solr   4096 Jan  4 09:18 docker
-rw-rw-r--  1 solr solr   1667 Jan  4 09:18 docker-compose-ci.yml
-rw-rw-r--  1 solr solr   2404 Jan  4 09:18 docker-compose-dev.yml
-rw-rw-r--  1 solr solr   1211 Jan 20 15:17 docker-compose.yml
drwxr-xr-x  8 solr solr   4096 Feb 15 12:36 docroot
drwxrwxr-x  3 solr solr  73728 Feb 15 12:29 drupal-cm
drwxrwxr-x  8 solr solr   4096 Feb 15 13:56 .git
-rw-rw-r--  1 solr solr    322 Feb  9 12:44 .gitignore
drwxrwxr-x  3 solr solr   4096 Feb 15 13:57 .idea
-rw-rw-r--  1 solr solr   5716 Jan  4 09:09 .jshintrc
-rw-rw-r--  1 solr solr   1331 Jan  4 09:18 Makefile
drwxrwxr-x  6 solr solr   4096 Feb  7 08:35 modules
drwxrwxr-x  2 solr solr   4096 Feb  7 08:35 patches
drwxrwxr-x  2 solr solr   4096 Feb 13 09:56 provision
drwxrwxr-x  5 solr solr   4096 Jan 20 11:18 qa
-rw-rw-r--  1 solr solr   1182 Jan  4 09:09 qa-tools.json
-rw-rw-r--  1 solr solr   6575 Feb  8 14:41 README.MD
drwxrwxr-x  3 solr solr   4096 Jan  4 09:09 scripts
-rw-rw-r--  1 solr solr    193 Feb 15 13:56 test-scripts
drwxrwxr-x  6 solr solr   4096 Jan  4 09:18 themes
-rw-rw-r--  1 solr solr   4638 Feb  7 08:35 .travis.yml
-rw-rw-r--  1 solr solr  15788 Jan 17 14:18 user-export.sql.gz
drwxrwxr-x  4 solr solr   4096 Feb 15 13:27 .vagrant
-rw-rw-r--  1 solr solr    544 Feb 13 09:55 Vagrantfile
drwxrwxr-x 70 solr solr   4096 Feb 15 12:36 vendor
```

### Summary
It seems the shared drupal-vm folder owner and group doesn't get changed to vagrant, when you don't select one of the build options. We use an ant database import script to provision our Drupal installation. Depending on if I either turn on the solr installed_extra or not the shared folder user/owner is either solr or admin/1000 when not.

[config.yml](https://gist.github.com/pdenooijer/de87187aff02e54619bba5def16cf60e)

**Comment by geerlingguy** [comment] 2017-02-17 19:30
I'm thinking this is related to https://github.com/geerlingguy/drupal-vm/issues/1016

See, specifically https://github.com/geerlingguy/drupal-vm/issues/1016#issuecomment-266808076

**Comment by pdenooijer** [comment] 2017-02-20 10:18
Yeah, it seems he had the same problem. Could you test it without specifying a build option? I guess that's the culprit of the problem.

**Comment by oxyc** [comment] 2017-02-23 13:19
This is most likely because the user on your host computer has UID 1000, which just so happens to become the UID of the solr user within the VM. With NFS the UID/GID is synced as is, and on osx that resolves to 501:dialout for most. On linux I guess it's 1000:1000.

You can fix it by using the [vagrant-bindfs plugin](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors).

**Comment by oxyc** [comment] 2017-02-28 20:25
I'm pretty sure the issue is identical UIDs as both reported instances was using Linux. @geerlingguy  can we close this? or should we add something to the docs?

**Comment by geerlingguy** [comment] 2017-02-28 23:06
I'd say close it... it seems to be somewhat of an edge case, and Google searches should hopefully lead people back to these issues, where there's a solution mentioned in the comments. Thanks!

**Closed by geerlingguy** 2017-02-28 23:06 UTC
Labels: question

**Comment by pdenooijer** [comment] 2017-03-03 12:51
I tried to use the bindfs plugin with a Vagrant.local file following the guide, but this didn't work for me 😞. Could I try something else or did I do something wrong trying to get it to work? I don't really understand why some people don't have this problem (neither did I in de past) and I do.
