### ISSUE TITLE
Creating Solr cores error using Solr 6.3.0

### ISSUE THREAD

**Issue by jvdschraaf** [geerlingguy/drupal-vm#1054] opened 2016-12-16 15:19 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.0
VirtualBox 5.0.30r112061
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.1)

### Full console output

```
TASK [geerlingguy.solr : Create configured cores.] ****************************
FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/tmp/ansible-tmp-1481900820.94-59098680901664/': Operation not permitted\nchown: changing ownership of '/tmp/ansible-tmp-1481900820.94-59098680901664/command.py': Operation not permitted\n). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

### Summary

Using Ubuntu 16.04 as box.

I tried installing Solr 6 using the Drupal VM; when installing I noticed that you can't create the cores with the root user. Thankfully this was already fixed in the new V4 of Drupal VM.

After updating to this new version I got the above error.

The fix is actually quite simple; you need to install the "acl" package in the VM. However, installing Solr is done before executing the "extra_packages". Because of this, as of right now I don't know how to fix this issue other than create a pre-provisioning script to install the acl package.

**Comment by geerlingguy** [comment] 2016-12-16 16:25
Hmm, this looks like there's something else potentially non-default, but I'll try to reproduce the issue locally. Besides adding `solr` to `installed_extras`, are there any other changes you've made to your Drupal VM configuration?

**Comment by geerlingguy** [comment] 2016-12-16 16:56
Ah, can reproduce the issue on 16.04. http://stackoverflow.com/a/36681626/100134

**Comment by geerlingguy** [comment] 2016-12-16 17:27
Fixed via latest Solr role (see above commit).

**Closed** 2016-12-16 17:27 UTC
Labels: question

**Comment by oxyc** [comment] 2017-05-05 12:47
Just ran into this same error when changing the composer global package user.

**Comment by geerlingguy** [comment] 2017-05-06 03:23
@oxyc - Hmm... using the latest version of Drupal VM?

**Comment by oxyc** [comment] 2017-05-06 13:42
No the project is a bit outdated. I'll try updating
