### ISSUE TITLE
vagrant up command hangs at "Mounting NFS shared folders...

### ISSUE THREAD

**Issue by wonder95** [geerlingguy/drupal-vm#2054] opened 2020-06-17 20:42 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.9
VirtualBox 6.1.8r137981
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/steve/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.9/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
```

### Your OS
 - **macOS** 10.15.5

### Full console output

```
steve@Steves-MBP dixon-d8 % vagrant up --provision
Bringing machine 'dixon-d8' up with 'virtualbox' provider...
==> dixon-d8: Checking if box 'geerlingguy/ubuntu1804' version '1.1.6' is up to date...
==> dixon-d8: Clearing any previously set forwarded ports...
==> dixon-d8: Clearing any previously set network interfaces...
==> dixon-d8: Preparing network interfaces based on configuration...
    dixon-d8: Adapter 1: nat
    dixon-d8: Adapter 2: hostonly
==> dixon-d8: Forwarding ports...
    dixon-d8: 22 (guest) => 2222 (host) (adapter 1)
==> dixon-d8: Running 'pre-boot' VM customizations...
==> dixon-d8: Booting VM...
==> dixon-d8: Waiting for machine to boot. This may take a few minutes...
    dixon-d8: SSH address: 127.0.0.1:2222
    dixon-d8: SSH username: vagrant
    dixon-d8: SSH auth method: private key
==> dixon-d8: Machine booted and ready!
[dixon-d8] GuestAdditions 6.1.8 running --- OK.
==> dixon-d8: Checking for guest additions in VM...
==> dixon-d8: [vagrant-hostsupdater] Checking for host entries
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 dixon-d8.local
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 192.168.88.171 dixon-d8.local www.dixon-d8.local dixon-aus.local dixon-can.local
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 adminer.dixon-d8.local
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 xhprof.dixon-d8.local
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 pimpmylog.dixon-d8.local
==> dixon-d8: [vagrant-hostsupdater]   found entry for: 192.168.88.171 dashboard.dixon-d8.local
==> dixon-d8: Setting hostname...
==> dixon-d8: Configuring and enabling network interfaces...
==> dixon-d8: Exporting NFS shared folders...
==> dixon-d8: Preparing to edit /etc/exports. Administrator privileges will be required...
==> dixon-d8: Mounting NFS shared folders...
==> dixon-d8: Waiting for cleanup before exiting...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,actimeo=2 192.168.88.1:/System/Volumes/Data/Users/steve/Sites/ut/dixon-d8 /var/www/dixon-d8

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out
```
### Summary

I have been attempting to use DrupalVM on a D8 project for the past 3 three weeks, and I continually run into where something will corrupt Vagrant, and I can't get it to come back up with `vagrant up`, because it hangs at `Mounting NFS shared folders...`.

 The last time, I had to completely reinstall everything from scratch (re-clone the git repo, composer install, provision, etc)  to get it up and running again, but I can't afford to do that this time because it crashed in the middle of work I was doing and hadn't exported yet. 

I've checked everything I can think of that might affect this (my drive isn't encrypted, no bad entries in `/export/host` and `/etc/export`, I've restarted the `nfsd` service on my mac, etc), but nothing works. Everything hung when accidentally I ran a `drush pm:enable` command inside vagrant for a module that already existed, but I can't see why that would cause so many problems.

Is there anything else I can do to get my image up and running again?

**Comment by geerlingguy** [comment] 2020-06-17 22:25
Marking as dupe of https://github.com/geerlingguy/drupal-vm/issues/2055

**Closed by geerlingguy** 2020-06-17 22:25 UTC
Labels: duplicate
