### ISSUE TITLE
Class DOMDocument does not exist error

### ISSUE THREAD

**Issue by jasloe** [geerlingguy/drupal-vm#1910] opened 2019-03-08 20:58 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.4
VirtualBox 5.2.2r119230
ansible 2.7.8
  config file = None
  configured module search path = ['/Users/jasonloeffler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 23 2018, 20:24:19) [Clang 9.0.0 (clang-900.0.39.2)]
```

### Your OS
 - **macOS**  10.12.6

### Full console output

fatal: [local-[redacted]]: FAILED! => {"changed": true, "cmd": ["drush", "site-install", "standard", "-y", "--root=/var/www/drupal/web", "--site-name=[redacted]", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.344140", "end": "2019-03-08 20:31:48.074033", "msg": "non-zero return code", "rc": 1, "start": "2019-03-08 20:31:47.729893", "stderr": " [preflight] Class DOMDocument does not exist\n [error]  Drush command terminated abnormally due to an unrecoverable error. ", "stderr_lines": [" [preflight] Class DOMDocument does not exist", " [error]  Drush command terminated abnormally due to an unrecoverable error. "], "stdout": "", "stdout_lines": []}

### Summary
Receiving the following output following vagrant up on local workstation. Running vagrant provision a second time successfully builds the vm and Drupal instance. Ideas?

**Comment by jnettik** [comment] 2019-03-28 18:34
I have the same issue. Adding the following to my `config.yml` file fixes it. Feels like this should need to be an extra step though.

```
php_packages_extra:
  - "php{{ php_version }}-xml"

**Comment by jasloe** [comment] 2019-03-29 21:42
@jnettik Thanks very much. Your fix worked for me.

**Comment by geerlingguy** [comment] 2019-03-31 03:37
This is very strange—unless you override the `php_packages` list manually, you should always have the `php-xml` extension installed and available, as it's in the default set from this role: https://github.com/geerlingguy/ansible-role-php-versions/blob/master/vars/Debian.yml

I can't reproduce the issue on a default VM or in a few other instances I'm running locally, so closing for now.

**Closed by geerlingguy** 2019-03-31 03:37 UTC
Labels: question

**Comment by jnettik** [comment] 2019-04-01 15:34
Interesting. In my case, that would apply. I've ran into issues where I need to add `- "php{{ php_version }}-bcmath"` to the `php_packages`. So adding additional PHP Packages prevents the other packages from being installed? Meaning to add new packages, we need to redefine the entire list again? Newly defined packages aren't just added to the default (necessary) list?

**Comment by geerlingguy** [comment] 2019-04-02 02:46
@jnettik yes; variables in Ansible are not additive—if you define `php_packages` you have to add the entire existing list, plus any additional ones you'd like to add. That's why for some roles (like the PHP role) I have a `php_packages_extra` variable so you can just tack on extras there (if you don't need to modify the default list), then the role combines the two lists.
