### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_SSL_CA

### ISSUE THREAD

**Issue by jesrig** [geerlingguy/drupal-vm#1039] opened 2016-12-08 15:58 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS

 - **Windows** (version)

### Full console output

https://gist.github.com/jesrig/d7979d21f0966e698dd84fe8e8415014

### Summary

I'm running into the following error when trying to set up a new vagrant box:

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [ecmag]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:04.792839", "end": "2016-12-08 15:49:45.713770", "failed": true, "rc": 255, "start": "2016-12-08 15:49:40.920931", "stderr": "PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_SSL_CA' in /usr/local/share/drush/lib/Drush/Sql/Sqlmysql.php on line 56\nDrush command terminated abnormally due to an unrecoverable error.       [error]\nError: Undefined class constant 'MYSQL_ATTR_SSL_CA' in\n/usr/local/share/drush/lib/Drush/Sql/Sqlmysql.php, line 56", "stdout": "\nFatal error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in /usr/local/share/drush/lib/Drush/Sql/Sqlmysql.php on line 56", "stdout_lines": ["", "Fatal error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in /usr/local/share/drush/lib/Drush/Sql/Sqlmysql.php on line 56"], "warnings": []}

Here is my config.yml

```
---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1404, geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: ecmag.dev
vagrant_machine_name: ecmag
vagrant_ip: 192.168.88.88

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/ecmag
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

# Minimum required versions.
drupalvm_vagrant_version_min: '1.8.5'
drupalvm_ansible_version_min: '2.1'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
drupalvm_database: mysql

# Set this to 'false' if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_makefile: false
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
drush_make_options: "--no-gitinfofile"

# Set 'build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
build_composer: false
drupal_composer_path: "{{ config_dir }}/drupal.composer.json"
drupal_composer_install_dir: "/var/www/ecmag"
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
build_composer_project: false
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Required Drupal settings.
drupal_core_path: "{{ drupal_composer_install_dir }}"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Settings for installing a Drupal site if 'install_site:' is 'true'.
drupal_major_version: 8
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin

# Additional arguments or options to pass to `drush site-install`.
drupal_site_install_extra_args: []

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []
  # - name: "Drupal Cron"
  #   minute: "*/30"
  #   job: "drush -r {{ drupal_core_path }} core-cron"

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: true

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ dashboard_install_dir }}"
          DirectoryIndex index.html

apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"

nginx_remove_default_vhost: true
nginx_ppa_use: true

# MySQL databases and users.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ drupal_db_name }}"

postgresql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    db: "{{ drupal_db_name }}"
    priv: "ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  - varnish
  - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

drush_version: "8.1.8"
drush_keep_updated: true
drush_composer_cli_options: "--prefer-dist --no-interaction"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false

# PHP Configuration. Currently-supported versions: 5.6, 7.0.
# To use 5.6, see: http://docs.drupalvm.com/en/latest/other/php-56/
php_version: "5.6"
php_install_recommends: no
php_packages:
  - php5.6
  - php5.6-apcu
  - php5.6-mcrypt
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-sqlite3
  - php5.6-xml
  - php5.6-mbstring
  - libpcre3-dev
php_conf_paths:
  - /etc/php/5.6/fpm
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli
php_extension_conf_paths:
  - /etc/php/5.6/fpm/conf.d
  - /etc/php/5.6/apache2/conf.d
  - /etc/php/5.6/cli/conf.d
php_fpm_daemon: php5.6-fpm
php_fpm_conf_path: "/etc/php/5.6/fpm"
php_fpm_pool_conf_path: "/etc/php/5.6/fpm/pool.d/www.conf"
php_mysql_package: php5.6-mysql


# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts: []
post_provision_scripts: []
  # - "../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ drupalvm_user }}"
ruby_install_gems: []

# Varnish Configuration (if enabled above).
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

# Solr Configuration (if enabled above).
solr_version: "5.5.2"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.53.0

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts
#ssh_home: "{{ drupal_core_path }}"
```

**Comment by geerlingguy** [comment] 2016-12-08 17:17
@jesrig - It looks like maybe your provisioning failed at least once, and PHP hasn't had a chance to restart. Can you run `vagrant reload --provision` and see if it passes?

**Comment by jesrig** [comment] 2016-12-08 17:56
@geerlingguy Nope, dies at the same place. I had actually done a full vagrant destroy before I had hit my above issue so I wasn't expecting it to pass.

**Comment by geerlingguy** [comment] 2016-12-09 14:55
@jesrig - In your `config.yml`, did you override the `php_mysql_package` as listed in the docs page? http://docs.drupalvm.com/en/latest/other/php-56/

If so, that package should be installed during provision.

**Comment by jesrig** [comment] 2016-12-09 14:58
@geerlingguy 
Yes, these are my settings:

# PHP Configuration. Currently-supported versions: 5.6, 7.0.
# To use 5.6, see: http://docs.drupalvm.com/en/latest/other/php-56/
php_version: "5.6"
php_install_recommends: no
php_packages:
  - php5.6
  - php5.6-apcu
  - php5.6-mcrypt
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-sqlite3
  - php5.6-xml
  - php5.6-mbstring
  - libpcre3-dev
php_conf_paths:
  - /etc/php/5.6/fpm
  - /etc/php/5.6/apache2
  - /etc/php/5.6/cli
php_extension_conf_paths:
  - /etc/php/5.6/fpm/conf.d
  - /etc/php/5.6/apache2/conf.d
  - /etc/php/5.6/cli/conf.d
php_fpm_daemon: php5.6-fpm
php_fpm_conf_path: "/etc/php/5.6/fpm"
php_fpm_pool_conf_path: "/etc/php/5.6/fpm/pool.d/www.conf"
php_mysql_package: php5.6-mysql

**Comment by geerlingguy** [comment] 2016-12-09 15:19
So... this is weird—I noticed in your [full console output](https://gist.github.com/jesrig/d7979d21f0966e698dd84fe8e8415014) that MySQL was never installed at all. Neither the `geerlingguy.mysql` nor `geerlingguy.php-mysql` role was run, even though it looks like you have `drupalvm_database: mysql` set in your `config.yml`.

Those two roles _have_ to run before the `geerlingguy.drush` role (which is where the failure occurs in your output); but I didn't even notice them run _or_ skipped in your playbook output. See: https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/playbook.yml#L58-L59

Do you know if you might have modified the `playbook.yml` file and removed or reordered some of the role includes? Or is anything else in your version of Drupal VM modified besides the `config.yml`?

**Comment by jesrig** [comment] 2016-12-09 15:23
@geerlingguy the only modifications I made were in this config.yml file, which is listed above. I did not modify `playbook.yml` or any other drupalvm file.

**Comment by geerlingguy** [comment] 2016-12-09 15:52
@jesrig - Can you also check what version of VirtualBox you have installed?

I'll do some more testing on my Windows laptop to see if something about Windows might be breaking things, but as of two days ago, all the defaults were confirmed working.

**Comment by jesrig** [comment] 2016-12-09 15:58
@geerlingguy I have Virtual box 5.1.6

**Comment by geerlingguy** [comment] 2016-12-09 16:22
@jesrig - On my Windows 10 laptop, I did the following (using cmder and also replicated in Cygwin):

```
$ git clone https://github.com/geerlingguy/drupal-vm.git
$ touch config.yml

# (Paste in the exact config.yml you have above)

$ vagrant up
```

After about 10 minutes, everything was running, and it showed that the entire setup process worked fine... it also showed the `geerlingguy.mysql` tasks running before any of the Drush tasks. I'm wondering if either you're using a fork of Drupal VM, or if something else is changed from the stock Drupal VM install.

Unless Ansible is broken or set up in a strange way, it will run the roles defined in the main playbook exactly in the order specified. So even if you had the database set to postgresql, it would still at least show that the mysql tasks were skipped.

Can you reproduce this issue if you download the latest version of Drupal VM and just copy over your config.yml file?

**Comment by geerlingguy** [comment] 2016-12-09 16:23
(Note also that I'm running Vagrant 1.9.0 and VirtualBox 5.1.10 on the Windows 10 laptop).

**Comment by jesrig** [comment] 2016-12-11 02:45
@geerlingguy Did a vagrant destroy, I updated to the latest Drupal VM (see below), and still hit the same error

> $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
   Removing geerlingguy/drupal-vm (3.5.1)
   Installing geerlingguy/drupal-vm (3.5.2)
    Loading from cache
Writing lock file
Generating autoload files


If this helps anything, here is the snippet in my compser.json where I require drupalVM for my project:

 "require-dev": {
        "geerlingguy/drupal-vm": "^3.5"
    }

**Comment by geerlingguy** [comment] 2016-12-11 03:52
Can you use a fresh download or clone of Drupal VM (rather than one included with your project through Composer) with the same config.yml, and see if it succeeds?

**Comment by jesrig** [comment] 2016-12-12 13:55
@geerlingguy very weird, I did as you said, and now it provisioned fine. Do you have any idea why the composer update wouldn't have worked as expected?

**Comment by geerlingguy** [comment] 2016-12-12 16:30
@jesrig - I'm wondering if there might be some other file somewhere that's overridden or maybe a Vagrantfile.local that snuck in and did something that's not tracked through the Composer update...

Is it possible to do a diff of the new Drupal VM directory and the one in the composer project, and see if there are any major changes? (Maybe download Drupal VM 3.5.2 to do the diff).

**Comment by jesrig** [comment] 2016-12-12 16:57
@geerlingguy 
A few things I'm noticing which did not exist before I manually downloaded:

docs/other/php.md
.git/.github
tests/ubuntu-16-php56.config.yml

**Comment by geerlingguy** [comment] 2016-12-28 17:12
This was a strange one... and when I updated from Drupal VM 3.5 to 4.0 on a couple of my projects, it seemed to work okay. I'm going to chalk it up to strange Composer behavior, and hopefully it doesn't happen again!

Please let me know if there's anything else related to this that's going wrong, otherwise I'll close this issue as resolved.

**Closed by geerlingguy** 2016-12-28 17:12 UTC
Labels: question, windows
