### ISSUE TITLE
Problems installing on OS X

### ISSUE THREAD

**Issue by justkristin** [geerlingguy/drupal-vm#1324] opened 2017-04-22 02:50 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.20r114629
-bash: ansible: command not found

```

### Your OS

 - **macOS** (version)
Version 10.12.4 (16E195)

### Full console output

(sorry - not full)
https://gist.github.com/justkristin/39fdf1d83b6bc293bb450d8ec6e713bc

### Summary

The errors are included in the gist pasted above.

I am simply trying to install the drupalvm, but my machine/my brain are lacking somehow. :) The first time there was an error with sendmail install, and the second time it died rather spectacularly at nginx.

**Comment by justkristin** [comment] 2017-04-22 03:17
Latest attempt:
https://gist.github.com/justkristin/39e15c117953e8180f6aaacd946b7519

**Comment by thom8** [comment] 2017-04-22 05:01
@justkristin can you try installing [ansible](https://github.com/geerlingguy/drupal-vm#1---install-vagrant-and-virtualbox) and make sure you're using the [latest version](https://github.com/geerlingguy/drupal-vm/releases/tag/4.4.3)

Would also recommend running `vagrant destroy` then `vagrant up` again.

**Comment by Gugols** [comment] 2017-04-22 11:55
I get the same error and same default apache2 default page. Error during install: https://pastebin.com/Bji1sGcy

I have the following setup:
OSX: 10.10.1 (Yosemite)
Vagrant: 1.9.3
Virtualbox: 5.1.18 r114002 (Qt5.6.2)
Ansible: 2.1.0.0

**Comment by Gugols** [comment] 2017-04-22 13:34
I just updated Ansible to 2.3.0.0 (since 2.1. didn't meet requirements). Then I destroyed, and rebuilt the box and got the same problem.

However, I changed the variable drupalvm_webserver from apache to nginx and the built was successful. So it seems that for some reason reason it tries to check whether NGINX is is intalled (which it is not since Apache is used) and then fails:

> TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************

**Comment by justkristin** [comment] 2017-04-22 19:19
I would prefer an apache environment so if Nguni isn't needed can we just comment that line out somewhere?

Also, could you link to an a subtle download page? The only free version I have found is a 30-day free trial version of Tower...?

**Comment by oxyc** [comment] 2017-04-22 20:09
This is currently a bug. `drupalvm.www` lists `geerlingguy.nginx` as a dependency so it runs just before the `drupalvm.www` role even if `drupalvm_webserver` is set to `apache`.

**Comment by geerlingguy** [comment] 2017-04-22 21:28
D'oh, entirely my fault! I even tested things on my prod.drupalvm.com server, noticed a weird nginx-related error and ignored it as a second provision cleared it up :/

Once #1325 is merged, I think that should take care of this bug.

**Comment by geerlingguy** [comment] 2017-04-22 21:38
The fix has been merged to master (#1326), and I'll create a new patch release so it's in the tagged download—just waiting on Travis CI to catch up and complete tests on the PRs and merges this afternoon.

Thanks @oxyc for getting this patched up!

**Comment by justkristin** [comment] 2017-04-22 22:28
Gah - just found a site that showed that ansible can be homebrewed - taken care of! Thank you for the patch as well. Going to test it now.

**Comment by justkristin** [comment] 2017-04-22 23:49
Ok - got the ansible installed, and then succeeded in installing drupalvm, but while the dashboard at http://192.168.88.88/ seemed to be fine, the site itself still will not come up. I changed the settings in the config:

< vagrant_hostname: dcon.dev
< vagrant_machine_name: dcon
---
> vagrant_hostname: drupalvm.dev
> vagrant_machine_name: drupalvm
28c28
<     destination: /var/www/dcon
---
>     destination: /var/www/drupalvm
87c87
< drupal_account_pass: **********
---
> drupal_account_pass: admin

Should that have caused problems?

**Comment by justkristin** [comment] 2017-04-23 00:31
I now have installed it (destroyed first) with no errors, and without changing any variables in the conf files (I did make the two copies, tho, removing "example/default" from the file names).  Still the only page that works for me is the http://192.168.88.88/ one. None of the others show up, and the error is "connection refused".

**Comment by oxyc** [comment] 2017-04-23 00:33
does http://adminer.drupalvm.dev work?

**Comment by oxyc** [comment] 2017-04-23 00:43
I just provisioned a VM and was unable to reproduce.

Is there anything interesting in `/var/log/apache2/error.log` or `/var/log/php7.1-fpm.log`?

Does restarting the webserver work?

```sh
sudo service apache2 restart
sudo service php7.1-fpm restart
```

**Comment by oxyc** [comment] 2017-04-23 00:46
Oh I just noticed, you changed the `destination` value in `vagrant_synced_folders`?

If you did, you should also set:

```yaml
drupal_composer_install_dir: "/var/www/dcon/drupal"
```

**Comment by justkristin** [comment] 2017-04-23 06:06
Tried changing the drupal_composer_install_dir, and then restarting apache/php fpm, but still can only see the dashboard. :( I am sure it is something stupid i am doing. I am going to kill it, and then try recreating without changing ANYTHING at all...

**Comment by justkristin** [comment] 2017-04-23 06:39
Ok. Clean install via vagrant of a fresh git clone.  Copied to create config.yml and drupal.make.yml, but changed NOTHING inside them. The install went into /var/www/drupalvm/drupal/web (as seen when vagrant ssh'ed in. Still, the only thing I get is the IP-addressed dashboard. No other pages work, and all of them give a variant of "adminer.drupalvm.dev refused to connect." (Chrome)

I'm sorry - I haven't saved the entire output from the vagrant up, but it ended with:
drupalvm                   : ok=216  changed=96   unreachable=0    failed=0

Not sure what else to try. Sorry I am such a pain in the butt, and class hasn't even started. :(

**Comment by oxyc** [comment] 2017-04-23 06:42
Do you have the `vagrant-hostsupdater` plugin? Or did you [edit the `/etc/hosts`](https://github.com/geerlingguy/drupal-vm#3---configure-your-host-machine-to-access-the-vm) file yourself?

**Comment by justkristin** [comment] 2017-04-23 06:47
Hokay. That was it. I fat-fingered my hosts file. This is where I slink out, shame-faced. I *knew* it was some stupidity on my part. Thank you, sir!

**Comment by oxyc** [comment] 2017-04-23 06:48
I entirely forgot about that possiblity as well! Glad you got it working!

**Closed by oxyc** 2017-04-23 06:48 UTC
Labels: question
