### ISSUE TITLE
403 Forbidden Access Error drupalvm 1.1.8/1.1.9

### ISSUE THREAD

**Issue by yupthatguy** [geerlingguy/drupal-vm#1769] opened 2018-05-08 12:30 UTC
### Issue Type

 - Bug Report / Support Request
After I `vagrant up` I can access the dashboard of website I want to develop, but when I go to `example.org` all I get is the 403 Forbidden Access Error.  

### Your Environment

```
Vagrant 2.0.4
VirtualBox vboxmanage --version
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/myusername/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

### Your OS

 - **Linux** (version)
16.04 Ubuntu

### Full console output
https://gist.github.com/yupthatguy/5a4356bad96a3f01bab0e61e0be7c7ec

### Config.yml
https://gist.github.com/yupthatguy/ee7e205cd42699b34e70fd0ffd136501

### Summary

1.) I confirmed all file permissions were correct and that apache2 via the vm was pointing at the correct docroot by editing the `000-default...` virtual host file.  
2.) With regards to my config.yml file, I literally copied it from another fully functional installation of drupalvm running a different website...of course, changing the domain name, machine name, and ip address all to be unique... also remembering to "docroot" / "core_path". etc to match `example.org`
3.) And I ran my YAML through three different YAML validators that all say my YAML is 100% correct.
4.) I even updated drupalvm from 1.1.8 to 1.1.9
5.) I directly opened and verified that `/etc/hosts` only has one entry for `example.org` 
6.) I have destroyed and rebuilt the box multiple times
7.) I cleared caches on guest and switched browsers..... `example.org`  simply will not load.  (403 Forbidden access error

> Forbidden
> You don't have permission to access / on this server.
> Apache/2.4.18 (Ubuntu) Server at darrylpenrice.org Port 80

**Comment by oxyc** [comment] 2018-05-11 01:34
Most likely a duplicate of https://github.com/geerlingguy/drupal-vm/issues/1764

**Comment by geerlingguy** [comment] 2018-10-10 15:03
Going to close this issue due to inactivity; but please reopen if you can still reproduce the issue.

**Closed by geerlingguy** 2018-10-10 15:03 UTC
Labels: linux, question
