### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by quietone1** [geerlingguy/drupal-vm#1425] opened 2017-06-14 08:34 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.3
VirtualBox 4.3.36_Debianr105129
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS
$ uname -a
Linux ithilien 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

### Full console output
$ vagrant ssh
ssh_exchange_identification: read: Connection reset by peer
$ ping 192.168.88.88
PING 192.168.88.88 (192.168.88.88) 56(84) bytes of data.
From 192.168.88.1 icmp_seq=1 Destination Host Unreachable
$ curl 192.168.88.88
curl: (7) Failed to connect to 192.168.88.88 port 80: No route to host

$ sudo route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.172.1   0.0.0.0         UG    1024   0        0 wlan0
10.1.1.0        *               255.255.255.0   U     0      0        0 br0
link-local      *               255.255.0.0     U     1000   0        0 br0
192.168.88.0    *               255.255.255.0   U     0      0        0 vboxnet0
192.168.172.0   *               255.255.255.0   U     0      0        0 wlan0

### Summary
Like it says I have no route to the host. 

I haven't tried to use VirtualBox in years and therefor carefully followed instructions. But it does seem I missed something.

**Comment by FinBoWa** [comment] 2017-06-14 09:03
Could you try a newer Virtualbox? 

```
Versions: Make sure you're running the latest releases of Vagrant, VirtualBox, and Ansible—as of late 2016, Drupal VM recommends: Vagrant 1.8.6, VirtualBox 5.1.10+, and Ansible 2.2.x
```

Atleast https://www.virtualbox.org/wiki/Linux_Downloads says there is a newer one.

**Comment by oxyc** [comment] 2017-06-15 16:33
Like @FinBoWa you'll at least need to update your VirtualBox version, v4.3 is not supported.

**Comment by geerlingguy** [comment] 2017-06-15 16:50
Yeah, a later version should help. Closing out this issue, but please reopen if that doesn't solve your problem.

**Comment by quietone1** [comment] 2017-06-15 22:18
OK, I have switched from using the Debian repo. And tried again. The results are exactly the same.
I was also wondering about the time it takes for the DrupalVM to start. It was taking a while, so I went to the kitchen for a few minutes. On my return DrupalVM was still not up. How long should it take?

I use LXC containers and have enabled ip forwarding and I use a firewall. When I disable the firewall I still can't get to the VM. Is there something I should be doing in VirtualBox? 

Vagrant 1.9.3
VirtualBox 5.1.22r115126
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**Comment by oxyc** [comment] 2017-06-15 23:15
There's a few steps you need to take to get it working with LXC. http://docs.drupalvm.com/en/latest/other/vagrant-lxc/

Following those steps got it running for me 2 out of 3 times. https://github.com/geerlingguy/drupal-vm/pull/1094#issuecomment-270010805

**Comment by quietone1** [comment] 2017-06-23 22:48
@oxyc Thanks for the idea but that isn't my situation. My LXC containers are totally separate from Virtualbox and Vagrant. I create and provision containers using my own ansible scripts. The only reason I have installed VirtualBox and vagrant is to try out DrupalVM.

Even with all the containers stopped, the firewall disabled and deleting routes needed for the containers does not help. But I can just do the basics with network setup. I could be missing something obvious.

**Comment by oxyc** [comment] 2017-06-23 23:02
Does Virtualbox work without Vagrant? Are the `vboxnet` interfaces shown with `netstat -rn` and `ifconfig`?

**Comment by oxyc** [comment] 2017-06-23 23:11
Maybe worth trying a different IP also. You can change it with the `vagrant_ip` variable in your `config.yml`.

**Comment by quietone1** [comment] 2017-06-23 23:14
I don't know if Virtualbox works without vagrant.

Yes, the interface is there and the route is there. 
`# ifconfig
br0       Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:10.1.1.2  Bcast:10.1.1.255  Mask:255.255.255.0
          inet6 addr: fe80::f0d3:95ff:fe4d:7f40/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1052546 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1485876 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:474144425 (452.1 MiB)  TX bytes:1310621890 (1.2 GiB)

eth0      Link encap:Ethernet  HWaddr 80:fa:5b:07:14:d9  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:345154 errors:0 dropped:0 overruns:0 frame:0
          TX packets:345154 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:105888845 (100.9 MiB)  TX bytes:105888845 (100.9 MiB)

vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          inet addr:192.168.88.1  Bcast:192.168.88.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:200 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:26700 (26.0 KiB)

wlan0     Link encap:Ethernet  HWaddr 20:7c:8f:84:60:54  
          inet addr:192.168.172.12  Bcast:192.168.172.255  Mask:255.255.255.0
          inet6 addr: fe80::227c:8fff:fe84:6054/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17453359 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10079290 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:21806783777 (20.3 GiB)  TX bytes:4491942898 (4.1 GiB)



# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.172.1   0.0.0.0         UG        0 0          0 wlan0
10.1.1.0        0.0.0.0         255.255.255.0   U         0 0          0 br0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 br0
192.168.88.0    0.0.0.0         255.255.255.0   U         0 0          0 vboxnet0
192.168.172.0   0.0.0.0         255.255.255.0   U         0 0          0 wlan0
`

**Comment by oxyc** [comment] 2017-06-23 23:18
Also, since you updated VirtualBox, did you rebuild the VM? `vagrant destroy; vagrant up`

**Comment by quietone1** [comment] 2017-06-23 23:26
No. Trying now

**Comment by quietone1** [comment] 2017-06-23 23:46
thanks, some progress.

`$vagrant up
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.88.1:/opt/drupal-vm /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
`

I can now `vagrant ssh`.

**Comment by oxyc** [comment] 2017-06-23 23:49
Great. I'm guessing it's because UDP is disabled by default on some distros https://github.com/geerlingguy/drupal-vm/issues/245#issuecomment-308110394.

You can switch to TCP http://docs.drupalvm.com/en/latest/getting-started/installation-linux/#nfs-shares-are-slow-or-hang-due-to-udp-protocol

**Comment by oxyc** [comment] 2017-06-23 23:51
Actually that docs entry I linked to wont work with the latest release of Drupal VM, you'll need master. 

Or you can add a `Vagrantfile.local` file that fixes it: https://github.com/geerlingguy/drupal-vm/issues/1375#issuecomment-302084206

**Comment by oxyc** [comment] 2017-06-23 23:55
Oh forgot, and adding any of the above fixes requires you to reload the VM `vagrant reload`.

**Comment by quietone1** [comment] 2017-06-23 23:57
Thanks heaps. I'll will work on this later. Family calls!

**Comment by oxyc** [comment] 2017-06-24 00:06
Glad you got it working. I'm pretty sure UDP is the cause for your current error so I'll close this but please reopen if it's something else.

**Closed by oxyc** 2017-06-24 00:06 UTC
Labels: linux, question

**Comment by geerlingguy** [comment] 2017-06-30 12:39
Thanks for the help, @oxyc !

And there's a new release of Drupal VM now, so you don't need to use master if you're on 4.6.0 or later.
