### ISSUE TITLE
Admin-Login on 'http://www.drupalvm.test/' failed: "Unrecognized username or password."

### ISSUE THREAD

**Issue by hontiponti** [geerlingguy/drupal-vm#1650] opened 2018-01-05 10:24 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.1
VirtualBox 5.1.10r112026
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/lea/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS
 - **macOS** (version)

### Full console output
https://gist.github.com/hontiponti/c211feb20c990e1258ab0b05059bd10f

### Summary
When I first installed druplvm all seemed to work just fine until I tried to build a custom module in drupal. After that the hosts did not work anymore. So I did 'vagrant destroy' and then 'vagrant up' but it did not help.
Then I downgraded VirtualBox and also uninstalled and reinstalled Vagrant and Ansible.
On 'vagrant up' the error message was 'Ansible failed to complete successfully.' I found a lot of issue posts here and tried out some things.
Now, the VM seems to work, but when I open 'www.drupalvm.test' and try to log in via 'admin' as username and 'admin' as pw, it gives me the error message: "Unrecognized username or password. Forgot your password?".

If you need the config.yml I'll post it here, too. 
I am very thankful for any help!
<img width="1265" alt="bildschirmfoto 2018-01-05 um 10 57 13" src="https://user-images.githubusercontent.com/27226504/34605259-357f1400-f20b-11e7-97e5-261add150148.png">

**Comment by oxyc** [comment] 2018-01-05 12:51
Not sure what's wrong but you can at least use `drush` to get a one time login link:

```sh
drush @drupalvm.test user-login
```

**Comment by hontiponti** [comment] 2018-01-06 19:31
ok, but this does not solve the problem. The startpage on www.drupalvm.test does not look the way it should. I really don't know what to do more to solve this issue..

**Comment by oxyc** [comment] 2018-01-06 23:06
Could you post the entire ansible output from doing a full rebuild of the VM?

```
vagrant destroy -f
vagrant up
```

**Comment by oxyc** [comment] 2018-01-16 16:54
This is actually a duplicate of #1588. I'll close this and please respond in that issue instead.

**Closed by oxyc** 2018-01-16 16:54 UTC
