### ISSUE TITLE
Slow Drush

### ISSUE THREAD

**Issue by anttimakela** [geerlingguy/drupal-vm#69] opened 2015-04-10 19:58 UTC
Drush tasks execute time is relatively longer compared to drupal vagrant enviroments that I've been previously using.
my config:
Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2
....
php_memory_limit: "256M"
php_realpath_cache_size: "1024K"

How can I make it a bit faster?

**Comment by geerlingguy** [comment] 2015-04-10 20:21
@anttimakela - Are you able to give some examples of drush commands that are performing slowly? Most of the time, commands like `status`, `cc`, `features-revert-all`, `updatedb`, `migrate-import`, etc. are highly dependent on the actual Drupal site being run.

That being said, I haven't typically encountered any slowness when running sites on this VM vs other VMs, but if you're running the commands locally (on your host) connecting through to the VM, there's a chance that a connection problem is causing a delay...

**Comment by anttimakela** [comment] 2015-04-10 20:27
@geerlingguy cc, updb, en, dis. I've noticed this after clean make-install and several d7 sites at work when we have changed the vagrant enviroments to drupalvm. It's at least 3-5 seconds longer... I run drush inside vagrant.

**Comment by anttimakela** [comment] 2015-04-10 20:47
I took time for drush cc all. approximately 45-50 seconds to complete. Typical amount of modules enabled for basic site (30), no features created. database.mysql size 3.2M
Site and UI-side is running fast.

**Comment by geerlingguy** [comment] 2015-04-10 20:56
@anttimakela - Can you run `drush --version` to verify what version you're running? It's possible that if you're running a 7.x Drush release (e.g. if you have `drush_version: master` in your `config.yml`), there might be a performance problem in the master/latest release.

Try rebuilding the VM with `drush_version: 6.6.0` or `drush_version: 6.5.0` (for an older stable release), and see if that makes a difference.

**Comment by anttimakela** [comment] 2015-04-10 20:59
@geerlingguy , Drush version:  7.0-dev. I try 6 and comment here the changes.

**Comment by anttimakela** [comment] 2015-04-10 21:45
@geerlingguy 
vagrant@site:/vagrant/drupal$ drush status
Drupal version                  :  7.35                    
Site URI                        :  http://default          
Database driver                 :  mysql                   
Database username               :  drupal                  
Database name                   :  drupal                  
Database                        :  Connected               
Drupal bootstrap                :  Successful              
Drupal user                     :  Anonyymi                
Default theme                   :  theme               
Administration theme            :  seven                   
PHP executable                  :  /usr/bin/php            
PHP configuration               :  /etc/php5/cli/php.ini   
PHP OS                          :  Linux                   
Drush version                   :  6.6.0                   
Drush configuration             :                          
Drush alias files               :                          
Drupal root                     :  /vagrant/drupal         
Site path                       :  sites/default           
File directory path             :  sites/default/files     
Temporary file directory path   :  sites/default/files/tmp 
vagrant@site:/vagrant/drupal$ drush cc all
all' cache was cleared.                                                                                    [success]
vagrant@site:/vagrant/drupal$

*45 seconds, no improvement in performance.*

**Comment by geerlingguy** [comment] 2015-04-10 21:52
@anttimakela - Interesting. Can you also let me know what is the `type` of synced folder in `config.yml`, and also what kind of computer you're using? (Windows, Mac, basic specs, etc.). I'll do a little benchmarking to see if I can find anything obvious.

**Comment by anttimakela** [comment] 2015-04-10 22:03
@geerlingguy, type: nfs
##Home
Model: MacBook Pro
ProIntel Core i5
2,53 GHz
Processors: 1
Cores: 2
Ram: 8 Gt
Prosessoriväylän nopeus: 4.8 Gb/s
Samsung SSD 120Gb
## Work 
iMac
21.5-inch: 1.4GHz
Specifications
1.4GHz dual-core Intel Core i5
Turbo Boost up to 2.7GHz
8GB memory
500GB hard drive1
Intel HD Graphics 5000

**Comment by geerlingguy** [comment] 2015-04-13 22:03
@anttimakela - In my own testing (comparing with drush times in a native Drupal install, a Drupal install on DigitalOcean, and one in Drupal VM), drush times seem to be very close to the same. I wonder if maybe that particular site has, as part of its cache clearing operation, something that's calling a blocking network service or something like that (the length of time points to either a timeout, or just tons of caches being rebuilt, but I suspect the former).

I'm going to close this as not reproducible (since I can't see the site where you're encountering these issues); please try installing the default included Drupal 8 or a Drupal 7 site using the makefile, and see if you are able to reproduce these slow drush operations.

Also, please try comparing some other drush operations like `drush migrate-status`, `drush pm-list`, `drush pm-enable [some-module]`, and see if you can get a better performance comparison. Clearing caches is one operation that can have drastic differences depending on the exact modules you're running and what they're doing.

**Closed by geerlingguy** 2015-04-13 22:03 UTC
Labels: question

**Comment by anttimakela** [comment] 2015-04-14 07:52
@geerlingguy, Drush version:  6.2.0.
<code>drush cc all</code> 18 sec. (before 45 sec.)
<code>drush status</code> 4 sec. (before 14 sec.)
This fixed it for me.

**Comment by geerlingguy** [comment] 2015-04-14 18:18
@anttimakela - Very strange. It seems like maybe drush has some sort of performance bug with later/newer versions in that case. I've been using 6.2.0 and 6.5.0 on most of my live infrastructure, and haven't noticed these performance issues.

I would suggest if you encounter any further issues, try reporting them upstream to the `drush-ops` project: https://github.com/drush-ops/drush

**Comment by guix77** [comment] 2017-01-24 17:01
Just to let you know, that if the NFS shares with Vagrant are still too slow for you, you can do the contrary : instead of installing a NFS server on your host machine, you can install it on the VM guest : http://guillaumeduveau.com/en/drupal-lightning-fast-synced-folders-in-vagrant-virtualbox/

**Comment by geerlingguy** [comment] 2017-01-24 22:12
@guix77 - Definitely an option! There's also `gatling-rsync`: https://github.com/smerrill/vagrant-gatling-rsync

**Comment by guix77** [comment] 2017-01-25 12:24
Well I got the idea from your blog article :) Mollom won't let me add the comment. Thanks again !

**Comment by anttimakela** [comment] 2017-01-25 14:22
Thanks for the updates. I recently bought new macbook pro (Mid 2015, 2,5 GHz Intel Core i7, 16 GB 1600 MHz DDR3) and haven't had any performance issues since. Using mainly Drush 8.x now.

**Comment by geerlingguy** [comment] 2017-01-25 15:42
@guix77 - Ha, well, sometimes Mollom is a bit of a pain :/
