### ISSUE TITLE
Got DrupalVM running (D7) but default login "Sorry, unrecognized username or password"

### ISSUE THREAD

**Issue by hondaman900** [geerlingguy/drupal-vm#1588] opened 2017-10-20 21:20 UTC
### Issue Type
 - Bug Report / Support Request
 - Documentation Report

Documentation says to use admin/admin for the site login, but I'm getting "Sorry, unrecognized username or password". Also tried drupal/drupal and admin/ , to no avail. My install is a Drupal 7 DrupalVM. Everything seems to be working fine, dashboard looks great, just can't get started.

### Your Environment
Running D7 instance of DrupalVM on Win10 as instructed in the docs. 

### Your OS
 - **Windows** (10)

### Full console output
N/A

### Summary
The default DrupalVM administrator login for the fresh site (admin/admin) is not recognized. Wanted to see if there's a different one I can use before I start modifying the database to get in. The documentation clearly states to use admin as both UN & PW.

**Comment by hondaman900** [comment] 2017-10-24 01:58
Anyone? I tried the PHP snippet in the root to give me a hash version of a usable password for the database, but the PHP won't execute. I'll need to revert to a manual install on WAMP if i can't get this operational.

Please help

**Comment by Lawri-van-Buel** [comment] 2017-10-24 06:34
Use ‘drush uli’ from inside the VM to get a one time login link. Or use Drush to diagnose other problems.

**Comment by geerlingguy** [comment] 2017-11-01 04:51
@hondaman900 - Is it possible the site was already installed previously, or you're using a database from an existing site, or you're using a custom install profile or something like a BLT-powered project? In any of those cases, there might not be a default admin user account with admin as the password.

Also, can you verify you're seeing the site running inside Drupal VM, and not a site installed with some other tool (e.g. WAMP)? To verify, run `vagrant halt` to shut down the VM, then try accessing the site again. If you can still hit the site, then it's being run elsewhere.

Finally, check your `config.yml`—did you change any values? Specifically the default drupal admin password variable?

**Comment by hondaman900** [comment] 2017-11-01 20:18
Hi Jeff (and Lawri),

Thanks for answering. I checked out your suggestions and none panned out I'm afraid. The site was fresh and untouched, Vagrant was responding fine. I ended up placing a one-time PHP file in the site root, running it to reset the UN/PW using Drupal API so that the PW is hashed correctly, and that got me in. Still not sure what the issue was.

**Comment by oxyc** [comment] 2018-01-16 16:56
Could you post the entire ansible output from doing a full rebuild of the VM?

Also make sure you've deleted the previously built codebase.

```
rm -rf drupal/
vagrant destroy -f
vagrant up
```

**Comment by geerlingguy** [comment] 2018-03-02 20:34
Going to close this ticket out; I can't reproduce either using the default D7 setup, or the `install-drupal 7.x-dev` script in the docker container.

**Closed by geerlingguy** 2018-03-02 20:34 UTC
Labels: question, windows
