### ISSUE TITLE
geerlingguy.drush : Do not run Composer as root/super user!

### ISSUE THREAD

**Issue by vyasamit2007** [geerlingguy/drupal-vm#1103] opened 2017-01-05 15:14 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.4r110228
ansible 2.2.0.0
```

### Your OS

 - **macOS** (Sierra)

### Full console output

https://gist.github.com/vyasamit2007/4c8e497a61c73aecb878b60fb24b161e

### Summary
geerlingguy.drush role is not downloading correctly. I've tried it with `become: yes` & `become: no` with no luck. If I remove the line, it works correctly but my drush doesn't work. This is the exact error:

```
TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
fatal: [npro]: FAILED! => {"changed": true, "cmd": "/usr/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:00.116993", "end": "2017-01-05 15:05:26.455792", "failed": true, "rc": 2, "start": "2017-01-05 15:05:26.338799", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for phpunit/phpunit 4.8.31 -> satisfiable by phpunit/phpunit[4.8.31].\n    - phpunit/phpunit 4.8.31 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n\n  To enable extensions, verify that they are enabled in your .ini files:\n    - /etc/php/7.1/cli/php.ini\n    - /etc/php/7.1/cli/conf.d/10-opcache.ini\n    - /etc/php/7.1/cli/conf.d/10-pdo.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu_bc.ini\n    - /etc/php/7.1/cli/conf.d/20-calendar.ini\n    - /etc/php/7.1/cli/conf.d/20-ctype.ini\n    - /etc/php/7.1/cli/conf.d/20-exif.ini\n    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.1/cli/conf.d/20-ftp.ini\n    - /etc/php/7.1/cli/conf.d/20-gettext.ini\n    - /etc/php/7.1/cli/conf.d/20-iconv.ini\n    - /etc/php/7.1/cli/conf.d/20-json.ini\n    - /etc/php/7.1/cli/conf.d/20-phar.ini\n    - /etc/php/7.1/cli/conf.d/20-posix.ini\n    - /etc/php/7.1/cli/conf.d/20-readline.ini\n    - /etc/php/7.1/cli/conf.d/20-shmop.ini\n    - /etc/php/7.1/cli/conf.d/20-sockets.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini\n    - /etc/php/7.1/cli/conf.d/20-yaml.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}
```

Also, I've selected php version as 5.6, though its going in 7.1 configs, not sure why.

Thanks!

**Comment by oxyc** [comment] 2017-01-05 15:17
This should work out of the box. What changes have you made? If you've added `become` that means you're editing the playbook? This is not supported.

**Comment by vyasamit2007** [comment] 2017-01-05 15:28
The project was created long before and have loads of project specific changes, now php repos have been changed and it got changed how it works so we've updated just the sections which needs to be updated.

**Comment by oxyc** [comment] 2017-01-05 15:40
Fair enough. In this case the error is:

> phpunit/phpunit 4.8.31 requires ext-dom * -> the requested PHP extension dom is missing from your system.
> To enable extensions, verify that they are enabled in your .ini files:
> /etc/php/7.1/cli/php.ini
> ...

`ext-dom` should be included with `php-xml`. Note that composer believes the config files should reside in `/etc/php/7.1` while it seems you have configured the VM to install php 5.6.

You probably missed something essential when you cherry picked updates.

**Comment by oxyc** [comment] 2017-01-05 15:43
Also, Drupal VM should nowadays be configurable enough that you dont need to "hack" internal tasks. If you contain all your custom changes to `config.yml` and post-provision-tasks, upgrades will be a lot easier.

If there's anything you find that cant be overridden, feel free to open up an issue and we can see if there's something Drupal VM can do to make it easier.

**Comment by oxyc** [comment] 2017-01-05 15:50
Could you post your `config.yml` and any other relevant changes you've made to Drupal VM. Maybe we can spot something.

**Comment by geerlingguy** [comment] 2017-01-05 22:09
@vyasamit2007 - Yeah, is it also possible for you to identify what version of Drupal VM you're running? Is there a CHANGELOG included?

**Comment by vyasamit2007** [comment] 2017-01-06 13:19
No CHANGELOG file and also I don't think there is any file mentioning the Drupal VM version.
Here is my `config.yml` file : https://gist.github.com/vyasamit2007/1e8b4fb6d6a245a207e2309d3e3a7f3b

**Comment by oxyc** [comment] 2017-01-06 14:21
Any chance you could upload a zip of the drupal vm files you have?

A couple of other things:
- Are you attempting to re-provision an existing box? Does this happen if you build a new one with `vagrant destroy; vagrant up`?
- Does the installed PHP version report 5.6 or 7.1 (`vagrant ssh -c 'php -v'`)

**Comment by oxyc** [comment] 2017-01-06 15:04
Also, here's a `config.yml` with only your custom overrides https://gist.github.com/oxyc/ced11adb7b853336fdfd49f105965cdb that should work for the latest version of Drupal VM.

From the looks of it you're using a local codebase and not a composer project which is the default? If you use a local codebase you should also set `build_composer_project: false`

**Comment by vyasamit2007** [comment] 2017-01-09 11:06
- Yes, I guess. I've destroyed multiple times after changing something but that happened, each time.
- It's installing PHP 7.1.
- I'll try to create a box using `build_composer_project: false` option and with the config file you've provided. BUT I'm not sure if it's related to this particular issue.

**Comment by oxyc** [comment] 2017-01-09 11:22
> I'll try to create a box using build_composer_project: false option and with the config file you've provided. BUT I'm not sure if it's related to this particular issue.

Could you send a zip of all the drupal-vm files? The issue is most likely that you havent made all the necessary updates to the drupal vm files. Maybe we can figure out what's missing. Eg. if you hack drupal core files your chance for support on DO drops drastically :)

**Comment by oxyc** [comment] 2017-01-31 16:12
@vyasamit2007 any updates on this? Did you manage to get it working?

**Comment by oxyc** [comment] 2017-02-28 22:07
I'll close this as there's been no updates for some time. I hope you got it working and if not, please re-open and send the drupal-vm files and I'll have a look.

I'd still suggest upgrading to a later version of Drupal VM though, that's the most stable solution.

**Closed by oxyc** 2017-02-28 22:07 UTC
Labels: question
