### ISSUE TITLE
Error when installing apache on the guest machine

### ISSUE THREAD

**Issue by prics** [geerlingguy/drupal-vm#51] opened 2015-03-27 11:08 UTC
This morning I saw a few things changed so I pulled the latest changes, destroyed the last VM I've created and did another vagrant up. Everything is working ok until this:

```
TASK: [geerlingguy.apache | Ensure Apache is installed.] ********************** 
failed: [drupaldev] => (item=apache2,apache2-mpm-prefork,apache2-utils) => {"failed": true, "item": "apache2,apache2-mpm-prefork,apache2-utils"}
stderr: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  apache2-bin apache2-data libaprutil1-dbd-sqlite3 libaprutil1-ldap
  liblua5.1-0
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-mpm-prefork apache2-utils
  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.1-0
0 upgraded, 8 newly installed, 0 to remove and 125 not upgraded.
Need to get 1,526 kB of archives.
After this operation, 5,661 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main libaprutil1-dbd-sqlite3 amd64 1.5.3-2+deb.sury.org~trusty+1 [16.2 kB]
Get:2 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main libaprutil1-ldap amd64 1.5.3-2+deb.sury.org~trusty+1 [14.3 kB]
Get:3 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-bin amd64 2.4.12-1+deb.sury.org~trusty+5 [949 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main liblua5.1-0 amd64 5.1.5-5ubuntu0.1 [99.9 kB]
Get:5 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-utils amd64 2.4.12-1+deb.sury.org~trusty+5 [137 kB]
Get:6 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-data all 2.4.12-1+deb.sury.org~trusty+5 [162 kB]
Get:7 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2 amd64 2.4.12-1+deb.sury.org~trusty+5 [146 kB]
Get:8 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-mpm-prefork amd64 2.4.12-1+deb.sury.org~trusty+5 [1,430 B]
Fetched 1,526 kB in 1s (767 kB/s)
Selecting previously unselected package liblua5.1-0:amd64.
(Reading database ... 60889 files and directories currently installed.)
Preparing to unpack .../liblua5.1-0_5.1.5-5ubuntu0.1_amd64.deb ...
Unpacking liblua5.1-0:amd64 (5.1.5-5ubuntu0.1) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack .../libaprutil1-dbd-sqlite3_1.5.3-2+deb.sury.org~trusty+1_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.5.3-2+deb.sury.org~trusty+1) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../libaprutil1-ldap_1.5.3-2+deb.sury.org~trusty+1_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.5.3-2+deb.sury.org~trusty+1) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../apache2-bin_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-bin (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../apache2-utils_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-utils (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../apache2-data_2.4.12-1+deb.sury.org~trusty+5_all.deb ...
Unpacking apache2-data (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2.
Preparing to unpack .../apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2 (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-mpm-prefork.
Preparing to unpack .../apache2-mpm-prefork_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-mpm-prefork (2.4.12-1+deb.sury.org~trusty+5) ...
Processing triggers for man-db (2.6.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...

msg: 'apt-get install 'apache2' 'apache2-mpm-prefork' 'apache2-utils'' failed: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/rnegrean/playbook.retry

drupaldev                  : ok=16   changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by enapthine** [comment] 2015-03-28 03:53
First attempt of running, fresh install of vagrant, ansible & virtualbox.. receiving similar error:

```
< TASK: geerlingguy.apache | Ensure Apache is installed. >
 --------------------------------------------------------
failed: [drupaldev] => (item=apache2,apache2-mpm-prefork,apache2-utils) => {"failed": true, "item": "apache2,apache2-mpm-prefork,apache2-utils"}
stderr: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

stdout: Reading package lists...
Building dependency tree...
Reading state information...
apache2-mpm-prefork is already the newest version.
apache2-utils is already the newest version.
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
The following NEW packages will be installed:
  apache2
0 upgraded, 1 newly installed, 0 to remove and 125 not upgraded.
7 not fully installed or removed.
Need to get 0 B/146 kB of archives.
After this operation, 461 kB of additional disk space will be used.
(Reading database ... 61347 files and directories currently installed.)
Preparing to unpack .../apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2 (2.4.12-1+deb.sury.org~trusty+5) ...
Processing triggers for man-db (2.6.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'apache2' 'apache2-mpm-prefork' 'apache2-utils'' failed: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


FATAL: all hosts have already failed -- aborting
 ____________
< PLAY RECAP >
 ------------
           to retry, use: --limit @/home/elliot/playbook.retry

drupaldev                  : ok=16   changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment] 2015-03-28 20:01
@prics and @enapthine - Can you try deleting all the contents of your shared folder (e.g. the `local_path` in the first item in `vagrant_synced_folders`), and see if that makes this problem go away?

If that doesn't work, can you also report:

  - What host OS you're using (Linux? Mac? Windows?)
  - What type of synced folder you're using (`nfs`, `smb`, `rsync`?)

Thanks!

**Comment by enapthine** [comment] 2015-03-29 00:30
Tried recreated the directory ( ~Sites/drupalvm ), same issue still occurs. Using NFS. Practically untouched config files. 

Linux Mint 17.1
3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by enapthine** [comment] 2015-03-29 00:49
VM launches but when visiting drupaltest.dev receiving:

```Fatal error: Class '__TwigTemplate_d15c9e55d7ded766d70402f2f86b2b0429d0e0b1ef2f74044ed6baeb1ce38d3d' not found in /var/www/drupal/core/lib/Drupal/Core/Template/TwigEnvironment.php on line 141```

**Comment by enapthine** [comment] 2015-03-29 01:17
Changed config.yml back to ```type: nfs```, ```sudo service nfs-kernel-server restart``` , ```vagrant reload```, ```vagrant provision```. VM booted successfully (much faster), site working when visiting drupaltest.dev.

**Comment by geerlingguy** [comment] 2015-03-30 02:41
For the commands `sudo rm -f /etc/exports` and `sudo service nfs-kernel-server restart`, those were run locally on your Mint host machine? Sounds like maybe Vagrant was creating invalid exports for NFS, or something else messed up the NFS exports on your host.

If that's the case, then I think we can close this issue and I'll note that there are two possible causes for this issue:

  1. Invalid `/etc/exports` on the host machine, causing the Vagrant NFS exports to not work correctly.
  2. Having an old Drupal install inside the shared folder when provisioning a new instance of Drupal VM.

**Closed by geerlingguy** 2015-03-30 02:41 UTC
Labels: question

**Comment by theodorosploumis** [comment] 2015-04-22 00:30
I had the same issue and it worked when I disabled  the **nfs option** on **drupal.make.yml** as mentioned [above](#issuecomment-87333981) by @enapthine.

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_from_makefile is 'true'.
  - local_path: ~/www/local/drupalvm
    destination: /var/www
    id: drupal
    type:
    create: true 
```

**Comment by marcvangend** [comment] 2015-07-06 14:34
Same here, I'm having exactly the same problem, changing `type: nfs` to `type:` solves it for me (Arch Linux). I don't quite see how the March 30th comment "solves" this issue. I don't use NFS on my machine so I don't see how anything could be messed up. Also, this was a completely fresh install so it can't be caused by old code somewhere.

**Comment by geerlingguy** [comment] 2015-07-06 14:46
@marcvangend - In that case, it seems Vagrant should've bailed out earlier (if you don't have NFS on your host machine); but if switching to the default share works for you, then that could be okay. I would also try the rsync share type if you want to see if that might be a little more performant. NFS is much faster than native shares, and rsync is a bit faster than NFS (though more annoying to use, since you have to manually set up syncing each time you bring up the machine.

**Comment by marcvangend** [comment] 2015-07-06 15:02
Well it did bail out pretty soon at first. Then I started the NFS server following the [instructions](https://wiki.archlinux.org/index.php/NFS#Starting_the_server):

    sudo systemctl start rpcbind.service
    sudo systemctl start nfs-server.service

That did solve the "It appears your machine doesn't support NFS" message, but obviously it was still not good enough.

**Comment by niccolox** [comment] 2015-07-13 22:31
you might want to consider adding fago's watch.sh somehow to do auto rsync 
http://wolfgangziegler.net/auto-rsync-local-changes-to-remote-server
