### ISSUE TITLE
Vagrant up fails with default Solr under CentOS 7

### ISSUE THREAD

**Issue by marikomay** [geerlingguy/drupal-vm#789] opened 2016-07-09 19:45 UTC
Vagrant up on fresh VM fails with default 5.5.1 Solr/CentOs 7. Here is the error:

> TASK [geerlingguy.solr : Ensure solr is started and enabled on boot.] **********
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Job for solr.service failed because the control process exited with error code. See \"systemctl status solr.service\" and \"journalctl -xe\" for details.\n"}

It only fails with CentOs 7 (works fine with Ubuntu).

My system:
OS X Yosemite (version 10.11)
Drupal VM 3.13
Vagrant 1.8.4
VirtualBox 5.0.24
Ansible 2.1.0

**Comment by geerlingguy** [comment] 2016-07-10 02:50
Interesting... The test for Solr 6.x on CentOS 7 seems to be passing (for the role itself: https://travis-ci.org/geerlingguy/ansible-role-solr), so either it's something with the older 5.5.1 version or some other config.

Can you log into the VM and run `sudo journalctl -u solr` to see the full output of what's failing?

**Comment by marikomay** [comment] 2016-07-10 03:23
OK, so it looks like port 8983 is already being used by another process? I'm not sure what is using it, since this is a default install. The only change I've made to the config is vagrant_box: geerlingguy/centos7. Here is the output:

> Jul 10 03:08:16 drupalvm.dev systemd[1]: Starting LSB: Controls Apache Solr as a Service...
Jul 10 03:08:16 drupalvm.dev su[30658]: (to solr) root on none
Jul 10 03:08:16 drupalvm.dev solr[30656]: Port 8983 is already being used by another process (pid: 30452)
Jul 10 03:08:16 drupalvm.dev solr[30656]: Please choose a different port using the -p option.
Jul 10 03:08:16 drupalvm.dev systemd[1]: solr.service: control process exited, code=exited status=1
Jul 10 03:08:16 drupalvm.dev systemd[1]: Failed to start LSB: Controls Apache Solr as a Service.
Jul 10 03:08:16 drupalvm.dev systemd[1]: Unit solr.service entered failed state.
Jul 10 03:08:16 drupalvm.dev systemd[1]: solr.service failed.

**Comment by geerlingguy** [comment] 2016-07-10 04:11
That's quite odd! Can you run one of the following commands and see what service might be running on the port?

```
$ lsof -i 8983 -S
# or
$ netstat -a | grep 8983
```

**Comment by marikomay** [comment] 2016-07-10 04:45
Here is the output from `lsof -i :8983 -S`:

> COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    30452 solr   90u  IPv6  66642      0t0  TCP *:8983 (LISTEN)

**Comment by geerlingguy** [comment] 2016-07-11 04:45
@marikomay - It looks like Solr is already running somehow—can you visit `drupalvm.dev:8983/solr` and see if it returns the Solr Admin page? (Or whatever your site's URL is, if it's not `drupalvm.dev`).

**Comment by marikomay** [comment] 2016-07-11 15:34
Strange. `drupalvm.dev:8983/solr` does return Solr Admin page. I destroyed the box and tried a fresh VM with the same results. I can access Solr Admin page but provisioning fails:

> fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Job for solr.service failed because the control process exited with error code. See \"systemctl status solr.service\" and \"journalctl -xe\" for details.\n"}

**Comment by geerlingguy** [comment] 2016-07-11 15:35
It could be a CentOS-specific thing. I haven't tested with CentOS 7 and Solr 5 in a month or so, I should try again! I'll try to figure out what's happening.

**Comment by marikomay** [comment] 2016-07-11 16:21
Sounds good. I should mention provisioning with Solr 6.1.0 failed as well. It worked with CentOS 6 and Ubuntu, however, so it appears to be specific to CentOS 7 only.

**Comment by geerlingguy** [comment] 2016-07-24 02:59
Testing now.

**Comment by geerlingguy** [comment] 2016-07-24 03:14
I can definitely reproduce on CentOS 7:

```
TASK [geerlingguy.solr : Ensure solr is started and enabled on boot.] **********
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Job for solr.service failed because the control process exited with error code. See \"systemctl status solr.service\" and \"journalctl -xe\" for details.\n"}
```

I'm going to do some poking and prodding on the upstream role to see if I can find a good workaround.

**Comment by geerlingguy** [comment] 2016-07-24 03:15
Upstream issue: https://github.com/geerlingguy/ansible-role-solr/issues/33

**Comment by geerlingguy** [comment] 2016-07-24 04:29
This _should_ be fixed upstream; it seems it was caused by _this_ not-really-bug-but-not-worked-around-for-RHEL7 thing in Ansible: https://github.com/ansible/ansible-modules-core/issues/915

**Comment by geerlingguy** [comment] 2016-07-24 04:29
I'm testing with Drupal VM now (was running tests in a standalone VM).

**Comment by geerlingguy** [comment] 2016-07-24 04:42
Just waiting on an upstream role [build](https://travis-ci.org/geerlingguy/ansible-role-solr/builds/146946037) to complete, then I'll update the role in Drupal VM to 3.1.2, and this should be resolved!

**Comment by geerlingguy** [comment] 2016-07-24 14:39
Fixed via the above commit... testing with a variety of OSes locally.

**Comment by geerlingguy** [comment] 2016-07-24 14:43
Tested 5.x and 6.x on both Ubuntu 16 and CentOS 7, and upstream role tests are still passing for other supported OSes, so I'm going to mark this as 'closed'.

Hopefully I'll be able to tag a new Drupal VM release in the next day or two, but until then, you can either update the Solr role manually, or pull master.

**Closed by geerlingguy** 2016-07-24 14:43 UTC
Labels: question, upstream

**Comment by geerlingguy** [comment] 2016-07-24 15:09
Hmm... 6.1.0 seems to be failing still on CentOS 7 only.

**Comment by geerlingguy** [comment] 2016-07-24 15:17
Ah nevermind, forgot to also install Java 8, by setting the following in `config.yml`:

```yaml
solr_version: "6.1.0"
java_packages:
  - java-1.8.0-openjdk
```

**Comment by marikomay** [comment] 2016-07-25 02:58
Thanks @geerlingguy! I can confirm both 5.x and 6.x are now working on CentOS 7 after updating the Solr role.
