### ISSUE TITLE
Snakeoil certificate for https is not accepted by Chrome

### ISSUE THREAD

**Issue by danlobo02** [geerlingguy/drupal-vm#2053] opened 2020-06-08 09:43 UTC
### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```
Vagrant 2.2.6
VirtualBox 6.0.15r135660
ansible 2.8.10
  config file = None
  configured module search path = ['/Users/daniel.lobo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.8/2.8.10/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.8/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

### Your OS

 - **macOS** (10.15.4)

**Comment by danlobo02** [comment] 2020-06-08 10:11
ok using this work around for now:

https://www.robpeck.com/2010/10/google-chrome-mac-os-x-and-self-signed-ssl-certificates/

**Comment by phizev** [comment] 2020-06-08 12:58
@danlobo02 if you are using Ubuntu as your VM's OS, you can work around the issue on provision with [this Ansible task](https://github.com/geerlingguy/drupal-vm/issues/2001#issuecomment-570039873). I believe this is also a duplicate of #2001.

**Comment by geerlingguy** [comment] 2020-07-08 00:15
Yeah; I'm going to mark this as a dupe of #2001 — please follow progress for getting this fixed more permanently there.

**Closed by geerlingguy** 2020-07-08 00:15 UTC
