### ISSUE TITLE
Installing Drupal fails to drop or create database

### ISSUE THREAD

**Issue by jb-asi** [geerlingguy/drupal-vm#1937] opened 2019-06-05 02:03 UTC
### Issue Type
 - Bug Report / Support Request

### Your Environment
Docker 18.09.6 on Ubuntu 18.04.2 LTS, and Win10

```

```

### Your OS
 - Windows 10 Enterprise
 - Ubuntu 18.04.2 LTS

### Full console output
After successfully starting drupalvm container (as per Method 1), using `docker exec drupalvm install-drupal` results in:
`...
> DrupalProject\composer\ScriptHandler::createRequiredFiles
Created a sites/default/settings.php file with chmod 0666
Created a sites/default/files directory with chmod 0777
Installing Drupal
`
` // You are about to CREATE the 'drupal' database. Do you want to continue?:    
 // yes.                                                                        
`
`
In SiteInstallCommands.php line 367:
`                                          
`  Failed to drop or create the database:  
`
`
site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command> [<profile>]...
`

### Summary
I followed Method 1 instructions from http://docs.drupalvm.com/en/latest/other/docker/ on two different Ubuntu 18.04.2 systems on completely different wired networks (home & office) and on Windows 10 Enterprise on office network.  Method 1's `drupal run` step works fine on all three systems (the result is drupalvm container is running).  But the second step `docker exec drupalvm install-drupal` results in _Failed to drop or create the database_.

![Screenshot from 2019-06-04 22-02-34](https://user-images.githubusercontent.com/20977235/58925173-8ca17d00-8714-11e9-8c2c-8c91718091c1.png)

**Comment by geerlingguy** [comment] 2019-06-05 05:19
Yeah, unfortunately there's an odd bug I haven't had time to look at which prevents MySQL from starting up on the first start of the Docker container instance.

Inside the container (if you do `docker exec -it [docker container name] bash`), you can run `systemctl start mysql` and I believe that will get it running. It's a little bit difficult to figure that out because the Drush message doesn't really indicate the server's not _running_ at all.

**Comment by geerlingguy** [comment] 2019-06-05 12:03
This is a duplicate of #1856 — so closing this and moving discussion there.

**Closed by geerlingguy** 2019-06-05 12:03 UTC
Labels: docker, question, windows
