### ISSUE TITLE
Unable to use chmod in with vagrant_sync folder in Windows

### ISSUE THREAD

**Issue by chumkui** [geerlingguy/drupal-vm#1586] opened 2017-10-19 12:50 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.28r117968
Ansible - remote install as Windows machine
DVM 4.7.0
```

### Your OS
 - **Windows** (10 Pro  build1703)
### Full console output

Sync folder chmod not working:

```
PS C:\................\geerlingguy-drupal-vm-4.7.0-0-gaedfc16> vagrant ssh
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

vagrant@drupalvm:/var/www/drupalvm/drupal/web$ ls -la
total 48
drwxrwxrwx 1 vagrant vagrant  4096 Oct 17 16:42 .
drwxrwxrwx 1 vagrant vagrant  4096 Oct 17 16:44 ..
-rwxrwxrwx 1 vagrant vagrant   385 Oct 17 16:42 autoload.php
drwxrwxrwx 1 vagrant vagrant 12288 Oct 17 16:43 core
-rwxrwxrwx 1 vagrant vagrant  1025 Oct 17 16:42 .csslintrc
-rwxrwxrwx 1 vagrant vagrant   357 Oct 17 16:42 .editorconfig
-rwxrwxrwx 1 vagrant vagrant   151 Oct 17 16:42 .eslintignore
-rwxrwxrwx 1 vagrant vagrant    41 Oct 17 16:42 .eslintrc.json
-rwxrwxrwx 1 vagrant vagrant  3858 Oct 17 16:42 .gitattributes
-rwxrwxrwx 1 vagrant vagrant  7866 Oct 17 16:42 .htaccess
-rwxrwxrwx 1 vagrant vagrant   549 Oct 17 16:42 index.php
drwxrwxrwx 1 vagrant vagrant     0 Oct 17 16:43 modules
drwxrwxrwx 1 vagrant vagrant     0 Oct 17 16:42 profiles
-rwxrwxrwx 1 vagrant vagrant  1596 Oct 17 16:42 robots.txt
drwxrwxrwx 1 vagrant vagrant  4096 Oct 17 16:42 sites
drwxrwxrwx 1 vagrant vagrant     0 Oct 17 16:42 themes
-rwxrwxrwx 1 vagrant vagrant   848 Oct 17 16:42 update.php
-rwxrwxrwx 1 vagrant vagrant  4555 Oct 17 16:42 web.config
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ cd sites/default/
vagrant@drupalvm:/var/www/drupalvm/drupal/web/sites/default$ sudo chmod -R 755 files/
vagrant@drupalvm:/var/www/drupalvm/drupal/web/sites/default$ ls -la files/
total 9
drwxrwxrwx 1 vagrant vagrant    0 Oct 19 08:07 .
drwxrwxrwx 1 vagrant vagrant 4096 Oct 19 08:11 ..
drwxrwxrwx 1 vagrant vagrant 4096 Oct 19 08:07 css
-rwxrwxrwx 1 vagrant vagrant  487 Oct 17 16:44 .htaccess
drwxrwxrwx 1 vagrant vagrant    0 Oct 19 08:07 js
drwxrwxrwx 1 vagrant vagrant    0 Oct 19 08:07 php
drwxrwxrwx 1 vagrant vagrant    0 Oct 17 16:44 styles
vagrant@drupalvm:/var/www/drupalvm/drupal/web/sites/default$

Home folder chmod is fine:
vagrant@drupalvm:~$ mkdir sites
vagrant@drupalvm:~$ mkdir sites/files
vagrant@drupalvm:~$ ls -la sites/files/
total 8
drwxrwxr-x 2 vagrant vagrant 4096 Oct 19 09:00 .
drwxrwxr-x 3 vagrant vagrant 4096 Oct 19 09:00 ..
vagrant@drupalvm:~$ chmod -R 755 sites/files/
vagrant@drupalvm:~$ ls -la sites/files/
total 8
drwxr-xr-x 2 vagrant vagrant 4096 Oct 19 09:00 .
drwxrwxr-x 3 vagrant vagrant 4096 Oct 19 09:00 ..
```

### Summary

Somewhere along the line I have lost the ability to chmod the .../sites/default/files directory.  I built a site yesterday that I have not worked on for a while.  A custom module threw an Exception and I know exactly what this is - it is ultimately a file permission issue.  I assumed I had forgotten to run the script that sets the various file permissions required and ran it again but still the same issue - on closer investigation, it looks like chmod has no affect any more - see output for step by step check on this.  It works fine in the home directory (or anywhere else) so I am assuming it must be something to do with the sync mounted share. I know this worked a few months back.  I have read that some experience strangeness with the sync folders, but I have never had an issue (using just defaults  -nfs).  Before I go spending hours on this I wondered if I was alone or if something had changed?  Everything runs fine other than the custom module actions.  Any ideas?

**Comment by fubarhouse** [comment] 2017-10-31 01:46
Historically I have seen this many times on OSX hosts.

I'll subscribe and see what happens here...

In my case, I can't sudo delete seemingly random files inside the Drupal installation directories which live underneath the nfs-synced folder, in fact I can only delete them from the host. I'll see if I can find some more information to contribute here...

**Comment by chumkui** [comment] 2017-11-13 16:25
Thanks - I have created a work around by simply not having a shared folder for this one project where there is specialist ownership.  No matter what I tried, once it was shared, I could not change the permissions post provision.  My colleague, who uses a MacBook running Sierra, has no such issues.

**Comment by MichaelMallett** [comment] 2017-11-29 03:19
On OSX, have a similar issue where composer running inside the VM can't delete folders in the shared directory. Tried using vagrant bindfs, however that also causes enormous errors because the files directory can't have separate permissions to the rest of the web/ folder (vagrant:www-data) and so I get thousands of chmod errors because php doesn't own the file when it tries to create twig entities.

**Comment by oxyc** [comment] 2018-01-16 18:07
@chumkui could you post your `config.yml`? There was one change to synced folders recently, switching from UDP to TCP.

NFS should never have been working on Windows afaik though. I'm guessing it's been using the native sync which is a fallback.

**Comment by chumkui** [comment] 2018-01-17 17:23
@oxyc  Thanks! See link to config file: [https://gist.github.com/chumkui/9b54d4c060abccc70d50f74f928a6280.js](url)

**Comment by timwood** [comment] 2018-03-13 18:39
I also have a terrible time with permission issues when running various commands from inside the VM, after recently updating to BLT 9.x, which recommends all blt commands be run inside the VM.

**Comment by geerlingguy** [comment] 2018-12-28 23:20
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!

**Closed by geerlingguy** 2018-12-28 23:20 UTC
Labels: windows
