### ISSUE TITLE
MariaDB broken packages

### ISSUE THREAD

**Issue by jasloe** [geerlingguy/drupal-vm#1977] opened 2019-10-03 23:51 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.4
VirtualBox 6.0.12r133076
ansible 2.8.5
```

### Your OS

 - **macOS** 10.14.3

### Full console output
```
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
fatal: [local-aarome]: FAILED! => {"cache_update_time": 1570146131, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'mariadb-client' 'mariadb-server'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n mariadb-server : Depends: mariadb-server-10.1 (>= 1:10.1.41-0ubuntu0.18.04.1) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " mariadb-server : Depends: mariadb-server-10.1 (>= 1:10.1.41-0ubuntu0.18.04.1) but it is not going to be installed"]}
```

### Summary

At ```config.yml```:
```
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
```

Installing MariaDB throws error listed above on vagrant up.

**Comment by jasloe** [comment] 2019-10-10 22:02
Anyone?

**Comment by geerlingguy** [comment] 2019-11-01 16:46
@jasloe is this on a brand new install? Also, what OS are you using? By default, Debian-based OSes install mariadb packages even with all the defaults...

**Comment by dercheffe** [comment] 2020-03-29 16:40
Experienced same error with Ubuntu 19.10 as host system on my pc. 
Using this solved the problem:
mysql_packages:
  - mariadb-client-10.1
  - mariadb-server-10.1
  - python-mysqldb

**Comment by jatorresdev** [comment] 2020-04-07 14:49
Duplicate of #1922

**Comment by geerlingguy** [comment] 2020-04-07 22:08
@jatorresdev - Thanks, that should be adequate, I think.

**Closed by geerlingguy** 2020-04-07 22:08 UTC
Labels: question
