### ISSUE TITLE
vagrant up fails on Windows with CentOS 6 base box

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#773] opened 2016-07-02 21:10 UTC
While running vagrant up for the first time for Drupal VM I get 

==> drupalvm: AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
vagrant : The SSH command responded with a non-zero exit status. Vagrant
At line:1 char:1
+ vagrant up
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The SSH command...status. Vagrant:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

A partial log follows ...

I am a newbie so please make your response as clear and unambiguous as possible while avoiding terms that I may not understand.

Thanks!

==> drupalvm: Successfully built ansible pycrypto
==> drupalvm: Installing collected packages: pycrypto, ansible
==> drupalvm:   Found existing installation: pycrypto 2.0.1
==> drupalvm:     DEPRECATION: Uninstalling a distutils installed project (pycrypto) has been deprecated and will be removed in a f
uture version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
==> drupalvm:     Uninstalling pycrypto-2.0.1:
==> drupalvm:       Successfully uninstalled pycrypto-2.0.1
==> drupalvm: Successfully installed ansible-2.1.0.0 pycrypto-2.6.1
==> drupalvm: Installing Ansible roles from requirements file, if available.
==> drupalvm: - downloading role 'selenium', owned by arknoll
==> drupalvm: - downloading role from https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
==> drupalvm: - extracting arknoll.selenium to /etc/ansible/roles/arknoll.selenium
==> drupalvm: - arknoll.selenium was installed successfully
==> drupalvm: - downloading role 'newrelic', owned by franklinkim
==> drupalvm: - downloading role from https://github.com/weareinteractive/ansible-newrelic/archive/1.2.0.tar.gz
==> drupalvm: - extracting franklinkim.newrelic to /etc/ansible/roles/franklinkim.newrelic
==> drupalvm: - franklinkim.newrelic was installed successfully
==> drupalvm: - downloading role 'adminer', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-adminer/archive/1.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.adminer to /etc/ansible/roles/geerlingguy.adminer
==> drupalvm: - geerlingguy.adminer was installed successfully
==> drupalvm: - downloading role 'apache', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/1.7.2.tar.gz
==> drupalvm: - extracting geerlingguy.apache to /etc/ansible/roles/geerlingguy.apache
==> drupalvm: - geerlingguy.apache was installed successfully
==> drupalvm: - downloading role 'apache-php-fpm', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-apache-php-fpm/archive/1.0.2.tar.gz
==> drupalvm: - extracting geerlingguy.apache-php-fpm to /etc/ansible/roles/geerlingguy.apache-php-fpm
==> drupalvm: - geerlingguy.apache-php-fpm was installed successfully
==> drupalvm: - dependency geerlingguy.apache already pending installation.
==> drupalvm: - downloading role 'blackfire', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-blackfire/archive/1.0.0.tar.gz
==> drupalvm: - extracting geerlingguy.blackfire to /etc/ansible/roles/geerlingguy.blackfire
==> drupalvm: - geerlingguy.blackfire was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'composer', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.4.0.tar.gz
==> drupalvm: - extracting geerlingguy.composer to /etc/ansible/roles/geerlingguy.composer
==> drupalvm: - geerlingguy.composer was installed successfully
==> drupalvm: - downloading role 'daemonize', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-daemonize/archive/1.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.daemonize to /etc/ansible/roles/geerlingguy.daemonize
==> drupalvm: - geerlingguy.daemonize was installed successfully
==> drupalvm: - downloading role 'drupal-console', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-drupal-console/archive/1.0.7.tar.gz
==> drupalvm: - extracting geerlingguy.drupal-console to /etc/ansible/roles/geerlingguy.drupal-console
==> drupalvm: - geerlingguy.drupal-console was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'drush', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-drush/archive/1.1.2.tar.gz
==> drupalvm: - extracting geerlingguy.drush to /etc/ansible/roles/geerlingguy.drush
==> drupalvm: - geerlingguy.drush was installed successfully
==> drupalvm: - dependency geerlingguy.git already pending installation.
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - dependency geerlingguy.composer already pending installation.
==> drupalvm: - downloading role 'firewall', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-firewall/archive/1.0.9.tar.gz
==> drupalvm: - extracting geerlingguy.firewall to /etc/ansible/roles/geerlingguy.firewall
==> drupalvm: - geerlingguy.firewall was installed successfully
==> drupalvm: - downloading role 'git', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-git/archive/1.1.1.tar.gz
==> drupalvm: - extracting geerlingguy.git to /etc/ansible/roles/geerlingguy.git
==> drupalvm: - geerlingguy.git was installed successfully
==> drupalvm: - downloading role 'java', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-java/archive/1.4.0.tar.gz
==> drupalvm: - extracting geerlingguy.java to /etc/ansible/roles/geerlingguy.java
==> drupalvm: - geerlingguy.java was installed successfully
==> drupalvm: - downloading role 'mailhog', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-mailhog/archive/1.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.mailhog to /etc/ansible/roles/geerlingguy.mailhog
==> drupalvm: - geerlingguy.mailhog was installed successfully
==> drupalvm: - dependency geerlingguy.daemonize already pending installation.
==> drupalvm: - downloading role 'memcached', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-memcached/archive/1.0.4.tar.gz
==> drupalvm: - extracting geerlingguy.memcached to /etc/ansible/roles/geerlingguy.memcached
==> drupalvm: - geerlingguy.memcached was installed successfully
==> drupalvm: - downloading role 'mysql', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.2.1.tar.gz
==> drupalvm: - extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
==> drupalvm: - geerlingguy.mysql was installed successfully
==> drupalvm: - downloading role 'nginx', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/1.9.2.tar.gz
==> drupalvm: - extracting geerlingguy.nginx to /etc/ansible/roles/geerlingguy.nginx
==> drupalvm: - geerlingguy.nginx was installed successfully
==> drupalvm: - downloading role 'nodejs', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/3.0.0.tar.gz
==> drupalvm: - extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
==> drupalvm: - geerlingguy.nodejs was installed successfully
==> drupalvm: - downloading role 'php', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.0.4.tar.gz
==> drupalvm: - extracting geerlingguy.php to /etc/ansible/roles/geerlingguy.php
==> drupalvm: - geerlingguy.php was installed successfully
==> drupalvm: - downloading role 'php-memcached', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-memcached/archive/2.0.0.tar.gz
==> drupalvm: - extracting geerlingguy.php-memcached to /etc/ansible/roles/geerlingguy.php-memcached
==> drupalvm: - geerlingguy.php-memcached was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'php-mysql', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-mysql/archive/2.0.0.tar.gz
==> drupalvm: - extracting geerlingguy.php-mysql to /etc/ansible/roles/geerlingguy.php-mysql
==> drupalvm: - geerlingguy.php-mysql was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'php-pecl', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-pecl/archive/1.2.1.tar.gz
==> drupalvm: - extracting geerlingguy.php-pecl to /etc/ansible/roles/geerlingguy.php-pecl
==> drupalvm: - geerlingguy.php-pecl was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'php-redis', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-redis/archive/3.0.0.tar.gz
==> drupalvm: - extracting geerlingguy.php-redis to /etc/ansible/roles/geerlingguy.php-redis
==> drupalvm: - geerlingguy.php-redis was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'php-xdebug', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-xdebug/archive/2.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.php-xdebug to /etc/ansible/roles/geerlingguy.php-xdebug
==> drupalvm: - geerlingguy.php-xdebug was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'php-xhprof', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-php-xhprof/archive/2.1.2.tar.gz
==> drupalvm: - extracting geerlingguy.php-xhprof to /etc/ansible/roles/geerlingguy.php-xhprof
==> drupalvm: - geerlingguy.php-xhprof was installed successfully
==> drupalvm: - dependency geerlingguy.php already pending installation.
==> drupalvm: - downloading role 'pimpmylog', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-pimpmylog/archive/1.0.2.tar.gz
==> drupalvm: - extracting geerlingguy.pimpmylog to /etc/ansible/roles/geerlingguy.pimpmylog
==> drupalvm: - geerlingguy.pimpmylog was installed successfully
==> drupalvm: - downloading role 'postfix', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-postfix/archive/1.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.postfix to /etc/ansible/roles/geerlingguy.postfix
==> drupalvm: - geerlingguy.postfix was installed successfully
==> drupalvm: - downloading role 'redis', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-redis/archive/1.2.0.tar.gz
==> drupalvm: - extracting geerlingguy.redis to /etc/ansible/roles/geerlingguy.redis
==> drupalvm: - geerlingguy.redis was installed successfully
==> drupalvm: - downloading role 'repo-remi', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-repo-remi/archive/1.2.0.tar.gz
==> drupalvm: - extracting geerlingguy.repo-remi to /etc/ansible/roles/geerlingguy.repo-remi
==> drupalvm: - geerlingguy.repo-remi was installed successfully
==> drupalvm: - downloading role 'ruby', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-ruby/archive/2.3.1.tar.gz
==> drupalvm: - extracting geerlingguy.ruby to /etc/ansible/roles/geerlingguy.ruby
==> drupalvm: - geerlingguy.ruby was installed successfully
==> drupalvm: - downloading role 'security', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-security/archive/1.2.0.tar.gz
==> drupalvm: - extracting geerlingguy.security to /etc/ansible/roles/geerlingguy.security
==> drupalvm: - geerlingguy.security was installed successfully
==> drupalvm: - downloading role 'solr', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-solr/archive/2.1.0.tar.gz
==> drupalvm: - extracting geerlingguy.solr to /etc/ansible/roles/geerlingguy.solr
==> drupalvm: - geerlingguy.solr was installed successfully
==> drupalvm: - downloading role 'varnish', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-varnish/archive/1.6.0.tar.gz
==> drupalvm: - extracting geerlingguy.varnish to /etc/ansible/roles/geerlingguy.varnish
==> drupalvm: - geerlingguy.varnish was installed successfully
==> drupalvm: Running Ansible provisioner defined in Vagrantfile.
==> drupalvm: ERROR! Unexpected Exception: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
==> drupalvm: the full traceback was:
==> drupalvm: 
==> drupalvm: Traceback (most recent call last):
==> drupalvm:   File "/usr/bin/ansible-playbook", line 79, in <module>
==> drupalvm:     mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/cli/playbook.py", line 30, in <module>
==> drupalvm:     from ansible.executor.playbook_executor import PlaybookExecutor
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 27, in <module>
==> drupalvm:     from ansible.executor.task_queue_manager import TaskQueueManager
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 29, in <module>
==> drupalvm:     from ansible.executor.process.result import ResultProcess
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/process/result.py", line 34, in <module>
==> drupalvm:     from Crypto.Random import atfork
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
==> drupalvm:     from Crypto.Random import _UserFriendlyRNG
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
==> drupalvm:     from Crypto.Random.Fortuna import FortunaAccumulator
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
==> drupalvm:     import FortunaGenerator
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
==> drupalvm:     from Crypto.Util.number import ceil_shift, exact_log2, exact_div
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
==> drupalvm:     if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
==> drupalvm: AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
vagrant : The SSH command responded with a non-zero exit status. Vagrant
At line:1 char:1
+ vagrant up
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The SSH command...status. Vagrant:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by geerlingguy** [comment] 2016-07-02 21:47
@ColumbiaBlooms - What OS are you running on your host machine? Also, can you run the command `ansible --version` on your command line to see what version of Ansible is installed?

**Comment by ColumbiaBlooms** [comment] 2016-07-02 22:00
I'm using Win 10. 

I get the following when I run ansible --version

ansible : The term 'ansible' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ansible --version

**Comment by geerlingguy** [comment] 2016-07-03 02:03
@ColumbiaBlooms - Ah, so in that case, you don't have Ansible installed locally, so that's helpful to know!

Another question—do you have a custom `config.yml`, and have you overridden the base box (e.g. `vagrant_box` option)?

**Comment by ColumbiaBlooms** [comment] 2016-07-03 05:22
I guess I do have a custom config.yml. Not sure since this is the first time I've used Vagrant/Drupal VM. 
 I'm using your Drupal VM configuration. 

Please see attached file. [config.zip](https://github.com/geerlingguy/drupal-vm/files/344880/config.zip)

**Comment by geerlingguy** [comment] 2016-07-03 19:19
@ColumbiaBlooms - It looks like the issue is you're running CentOS 6 inside the VM. While this is a supported operating system, it is only tested when run from a Mac or Linux PC with `ansible` installed on the host. In your case, since you're on Windows and Ansible is being installed inside the VM, it's having some trouble since CentOS 6 has really old system libraries.

Would it be acceptable to try running things with `vagrant_box: geerlingguy/centos7` instead? I'm not sure how much longer I can keep official CentOS 6 support going, since there are little failures like the one you've run into that make it hard.

Otherwise, please try doing the following:

  1. Wait for `vagrant up` or `vagrant provision` to fail (like it does in your original post).
  2. Log in with `vagrant ssh`
  3. Run the command `yum remove python-crypto`
  4. Log back out with `exit`
  5. Run `vagrant provision` and see if it works this time.

(See https://github.com/ansible/ansible/issues/276#issuecomment-46676269 for more info)

**Comment by ColumbiaBlooms** [comment] 2016-07-03 20:52
Sorry that I have to use CentOS 6. I'm trying to mirror my remote site. It's running on bluehost with CentOS 6. I'm new to building web sites & chose to use Drupal. I've been working with it about a year. Maybe I should have chosen a different host?

Here are the results of "vagrant up".

PS C:\Users\samst\Desktop\Drupal\Drupal VM> vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/centos6' is up to date...
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
    drupalvm: Warning: Remote connection disconnect. Retrying...
==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => C:/Users/samst/Desktop/Drupal/Drupal VM
    drupalvm: /var/www/drupalvm => C:/Users/samst/Sites/drupalvm
==> drupalvm: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm: flag to force provisioning. Provisioners marked to run always will still run.

I ran "vagrant provision" next with the following messages. Note: I edited out some of them that didn't seem relevant.

PS C:\Users\samst\Desktop\Drupal\Drupal VM> vagrant provision
==> drupalvm: Running provisioner: shell...
    drupalvm: Running: C:/Users/samst/AppData/Local/Temp/vagrant-shell20160703-7480-13bhej7.sh
==> drupalvm: Installing Ansible roles from requirements file, if available.
==> drupalvm: - downloading role 'selenium', owned by arknoll
==> drupalvm: - downloading role from https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
==> drupalvm: - extracting arknoll.selenium to /etc/ansible/roles/arknoll.selenium
==> drupalvm: - arknoll.selenium was installed successfully
...
==> drupalvm: - downloading role 'varnish', owned by geerlingguy
==> drupalvm: - downloading role from https://github.com/geerlingguy/ansible-role-varnish/archive/1.6.0.tar.gz
==> drupalvm: - extracting geerlingguy.varnish to /etc/ansible/roles/geerlingguy.varnish
==> drupalvm: - geerlingguy.varnish was installed successfully
==> drupalvm: Running Ansible provisioner defined in Vagrantfile.
==> drupalvm: ERROR! Unexpected Exception: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
==> drupalvm: the full traceback was:
==> drupalvm: 
==> drupalvm: Traceback (most recent call last):
==> drupalvm:   File "/usr/bin/ansible-playbook", line 79, in <module>
==> drupalvm:     mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/cli/playbook.py", line 30, in <module>
==> drupalvm:     from ansible.executor.playbook_executor import PlaybookExecutor
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 27, in <module>
==> drupalvm:     from ansible.executor.task_queue_manager import TaskQueueManager
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 29, in <module>
==> drupalvm:     from ansible.executor.process.result import ResultProcess
==> drupalvm:   File "/usr/lib/python2.6/site-packages/ansible/executor/process/result.py", line 34, in <module>
==> drupalvm:     from Crypto.Random import atfork
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
==> drupalvm:     from Crypto.Random import _UserFriendlyRNG
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
==> drupalvm:     from Crypto.Random.Fortuna import FortunaAccumulator
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
==> drupalvm:     import FortunaGenerator
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
==> drupalvm:     from Crypto.Util.number import ceil_shift, exact_log2, exact_div
==> drupalvm:   File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
==> drupalvm:     if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
==> drupalvm: AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
vagrant : The SSH command responded with a non-zero exit status. Vagrant
At line:1 char:1
+ vagrant provision
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The SSH command...status. Vagrant:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

"vagrant ssh" does not work. I guess that's because of the error above?

**Comment by geerlingguy** [comment] 2016-07-03 21:25
BlueHost isn't a bad host or anything... but you might be okay running centos7 on Drupal VM.

However, `vagrant ssh` should still work even after you get those errors, assuming you're using Cygwin, Cmder, or Git Bash. If you're using PowerShell built into Windows, you won't be able to use SSH to ssh into the box. See: http://docs.drupalvm.com/en/latest/other/windows/#command-line-environment

**Comment by ColumbiaBlooms** [comment] 2016-07-03 22:36
Hmmm. There always seems to be something lurking in the shadows! 

I was using PowerShell. I downloaded Cmder. When I unzip it in which Windows folder should I put Cmder folders & files?

If I were to switch to Centos7 would I still have to use Cmder? Remember I'm a newbie. Also, I'm a one-man-shop. I really want to get back to designing my site, columbiablooms.org, and not have to fiddle with all this server stuff. Am I asking too much of Vagrant/Drupal VM?

Perhaps the documentation needs to be updated. It says nothing about the SSH issue in Windows PowerShell.

**Comment by geerlingguy** [comment] 2016-07-04 03:04
@ColumbiaBlooms - Yeah, it might be best to try using CentOS 7, because then you could just use PowerShell and there shouldn't be any issues.

(And the reason the docs don't mention the PowerShell issue is because it works fine as long as you're running Ubuntu 16/14/12 or CentOS 6 on Windows with PowerShell... it's only CentOS 6 that has this problem :) ).

**Comment by geerlingguy** [comment] 2016-07-04 03:05
Make sure to change the base box to `geerlingguy/centos7`, then also do a `vagrant destroy` to make sure the box is gone, then `vagrant up` to build a new box.

**Comment by ColumbiaBlooms** [comment] 2016-07-04 14:00
Sorry to bother you again. 

"vagrant destroy" seems to hang. I get no messages in the Windows PowerShell window after waiting many minutes. I even re-booted, but there was no change. What have I managed to mess up?

**Comment by ColumbiaBlooms** [comment] 2016-07-04 21:18
I've uninstalled Vagrant and am in the process of re-installing it to hopefully get around this problem.

**Comment by geerlingguy** [comment] 2016-07-04 21:52
@ColumbiaBlooms - Yeah, something seems like it might have gone wrong with the Vagrant installation, so see if that helps. Sorry it's being such a pain!

**Comment by ColumbiaBlooms** [comment] 2016-07-05 02:34
Yea! It works, sort of. I got "The website encountered an unexpected error. Please try again later." when vagrant up finished, I refreshed the page and then got the Drupal page.

The uninstall/install of Vagrant & VirtualBox seemed to fix everything. I'm disappointed that these components are scattered all over my hard drive at 

C:\Users\samst\.vagrant
C:\Users\samst\.vagrant.d
C:\HashiCorp
C:\Program Files\Oracle
C:\Users\samst\VirtualBox VMs

I understand that VirtualBox is from a different vendor than Vagrant, but it would have been nice if there had been only two install folders used. One for Vagrant. One for VirtualBox. I hate clutter!

My next step is to follow instructions at http://docs.drupalvm.com/en/latest/deployment/local-codebase/ to port my local site into Vagrant/DrupalVM. I guess the best approach would be to change the various components to match my live site (Apache, PHP, MySQL, and CentOS) one at a time to isolate potential problems?

**Comment by geerlingguy** [comment] 2016-07-05 02:57
@ColumbiaBlooms - woohoo! And yeah, it's a little annoying having the files scattered around... but such is life using this open source toolkit :D

Yes, I'd make a few changes to your config, then run `vagrant provision`, then make other changes—that way you can see where something went wrong (if anything goes wrong).

I'm going to close this issue as a 'kind-of-won't-fix' in the particular instance of CentOS 6 as a guest OS on Windows specifically, since there's no easy way for me to support this scenario automatically (since CentOS 6 has such old libraries).

**Closed by geerlingguy** 2016-07-05 02:57 UTC
Labels: question, windows
