### ISSUE TITLE
Could not find the requested service firewall

### ISSUE THREAD

**Issue by matolsen** [geerlingguy/drupal-vm#695] opened 2016-06-03 19:27 UTC
When running vagrant up (and vagrant provision twice) I get the following error 

`fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}`

drupalvm                   : ok=10   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Mac version 10.11.4
Vagrant 1.8.1
ansible 2.2.0

**Comment by geerlingguy** [comment] 2016-06-03 20:02
Hmm... what OS are you using in `default.config.yml` or in `config.yml` (the base box)?

**Comment by matolsen** [comment] 2016-06-03 20:19
vagrant_box: geerlingguy/ubuntu1604

**Comment by matolsen** [comment] 2016-06-06 14:39
I updated my config to use vagrant_box: geerlingguy/ubuntu1404 and that works fine.

**Comment by alesrebec** [comment] 2016-06-11 22:04
Same thing here: "Could not find the requested service \"'firewall'\"

OSX 10.11.4
Vagrant 1.8.3
Ansible 2.2.0
Vagrant box: geerlingguy/ubuntu1604

**Comment by geerlingguy** [comment] 2016-06-13 04:14
@alesrebec - If you got to that point, then it seems the firewall error would be okay.

That particular error was caused by a couple different things (directory permissions and possibly another bug that was fixed in the 3.1.1 release). Can you try again with 3.1.1 and see if things are working now?

**Comment by alesrebec** [comment] 2016-06-13 08:42
I can confirm composer create-project works in 3.1.1.

About the original 'firewall' issue in Ubuntu 16.04, is there a known solution for it or should we stay on 14.04 for now?

**Comment by geerlingguy** [comment] 2016-06-13 22:44
@alesrebec - I can't reproduce that problem on my Mac (10.11) or Windows (10) environments... and I had a few other people try on their Macs, without any issue (nor is there an issue in the Travis CI automated builds on top of Ubuntu 16.04: https://travis-ci.org/geerlingguy/drupal-vm). Can someone download a fresh copy of Drupal VM and offer steps to definitively reproduce the issue?

**Comment by alesrebec** [comment] 2016-06-14 07:27
It worked the second time after I destroyed the VM, set the Vagrant box back to geerlingguy/ubuntu1604 and ran "vagrant up".
If it can be reproduced, it's probably reproducible just on a clean machine.

**Comment by geerlingguy** [comment] 2016-06-14 19:42
@alesrebec - I deleted all the vagrant and virtualbox directories on my Windows 10 laptop, and also reinstalled VirtualBox and Vagrant, and I couldn't get the problem to occur in that environment either... I wonder if it was some strange on-off issue.

I'm going to close this issue, but will reopen if more people start seeing it happen.

**Comment by emdahlstrom** [comment] 2016-06-19 11:07
I got the same problem with a fresh download of drupal.vm, vagrant and virtualbox with the ubuntu1604 config on OSX El Capitan: fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}

**Comment by geerlingguy** [comment] 2016-06-19 20:22
@emdahlstrom - If you do `vagrant provision` again, does it work the second time? Maybe it's something that only happens on the initial `up`.

**Comment by jweite** [comment] 2016-08-10 01:53
I'm experiencing the same firewall error (failed determining service state, possible typo of service name) on a fresh download/install.  Running `vagrant provision` fails identically.   Switched OS to geerlingguy/ubuntu1404 - same results for both `vagrant up` and `vagrant provision`.

VM does come up but I can't get through on ports 80 or 2222.

Windows 10 Pro
Vagrant 1.8.5
VirtualBox 5.0.24

**Comment by geerlingguy** [comment] 2016-08-10 02:30
@jweite - This issue has been closed, but since you're the 3rd or 4th person to hit this, I wonder if there might be a pattern. I'm going to try to do a full reimage/reinstall of everything on my poor old Windows 10 laptop, and see if I can reproduce the issue...

I know there are many others using Windows 10 without any problem, I wonder if it could be a corporate firewall or proxy issue, a VPN issue, or something else entirely.

**Comment by jweite** [comment] 2016-08-10 12:28
Thanks Jeff.  Fwiw I wasn't behind a corporate firewall or proxy or using a vpn at that time.  (Was at home on my personal network).  Let me know what other info I can feed back or tests I can do.

**Comment by stevepurkiss** [comment] 2016-08-15 16:25
Changing to Ubuntu 1404 worked for me too. But I'm not using Windoze on anything so hopefully that is of some help. Now to downgrade ansible from 2.2 to 2.1 and hopefully that'll work!

I can't imagine where I'd be without drupalvm so thanks again Jeff!

**Comment by geerlingguy** [comment] 2016-08-16 19:41
Alrighty, reopening the issue... it seems repeatable, and I'm going to do some more testing on my Windows laptop to see if I can reproduce it.

**Comment by geerlingguy** [comment] 2016-08-16 19:42
Actually, moving conversation over to #829 — merging this issue into that one.

**Closed by geerlingguy** 2016-08-16 19:42 UTC
Labels: question, windows
