### ISSUE TITLE
Drupal 7

### ISSUE THREAD

**Issue by dev-dev00** [geerlingguy/drupal-vm#1346] opened 2017-04-27 09:51 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```

```

### Your OS

 - **macOS** (version)

### Summary

Drupal 7 and PHP 5.6 configuration instructions:
Mac OS X El Capitan, Version 10.11.6
Requirements: Python 2.7.13

[DrupalVM Ubuntu 16_04 Instructions.pdf](https://github.com/geerlingguy/drupal-vm/files/962985/DrupalVM.Ubuntu.16_04.Instructions.pdf)

**Comment by thom8** [comment] 2017-04-27 09:54
@dev-dev00 please include your config file, environment info would be useful too so we can try to replicate the issue.

**Comment by dev-dev00** [comment] 2017-04-27 09:58
---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/debian8, geerlingguy/ubuntu1404, geerlingguy/ubuntu1204, etc.
vagrant_box: geerlingguy/ubuntu1604
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for more.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

# Minimum required versions.
drupalvm_vagrant_version_min: '1.8.6'
drupalvm_ansible_version_min: '2.2'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
drupal_db_backend: mysql

# Set this to 'false' if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
drupal_build_makefile: true 
drush_makefile_path: "drupal.make.yml"
drush_make_options: "--no-gitinfofile"

# Set 'build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
drupal_build_composer: false
drupal_composer_path: "drupal.composer.json"
drupal_composer_install_dir: "/var/www/drupalvm/drupal"
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
drupal_build_composer_project: false
drupal_composer_project_package: "drupal-composer/drupal-project:7.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
drupal_install_site: true

# Required Drupal settings.
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_core_owner: "{{ drupalvm_user }}"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Settings for installing a Drupal site if 'install_site:' is 'true'.
drupal_major_version: 7
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin

# Additional arguments or options to pass to `drush site-install`.
drupal_site_install_extra_args: []

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: true

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_packages_state: latest
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"
    is_php: true

nginx_remove_default_vhost: true
nginx_ppa_use: true

# MySQL databases and users.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ drupal_db_name }}"

postgresql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    db: "{{ drupal_db_name }}"
    priv: "ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  # - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

drush_version: "8.1.10"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "5.6"
php_install_recommends: no
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts: []
post_provision_scripts: []
  # - "../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ drupalvm_user }}"
ruby_install_gems: []

# Varnish Configuration (if enabled above).
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256

# Solr Configuration (if enabled above).
solr_version: "5.5.3"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.53.0

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts
hostname_fqdn: "{{ vagrant_hostname }}"
ssh_home: "{{ drupal_core_path }}"

**Comment by dev-dev00** [comment] 2017-04-27 10:01
Vagrant 1.9.4
VirtualBox 5.1.20r114629
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

**Comment by thom8** [comment] 2017-04-27 10:02
thx also the `drupal.make.yml`

**Comment by dev-dev00** [comment] 2017-04-27 10:05
[make.pdf](https://github.com/geerlingguy/drupal-vm/files/961207/make.pdf)

**Comment by thom8** [comment] 2017-04-27 10:08
and this file is called `drupal.make.yml` in the root directory or where your `config.yml` file is?

**Comment by dev-dev00** [comment] 2017-04-27 10:09
In my root directory it is call drupal.make.yml. Yes, in the same directory as the default.config.yml file.

**Comment by thom8** [comment] 2017-04-27 10:09
Ahh I think you need the `{{ config_dir }}` prefix as below

```
# Set this to 'false' if you are using a different site deployment
strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts'
manually.
drupal_build_makefile: true
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
drush_make_options: "--no-gitinfofile"
```

**Comment by thom8** [comment] 2017-04-27 10:10
see default -- https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L52

**Comment by dev-dev00** [comment] 2017-04-27 10:12
let me try that.
I'm pretty sure those files weren't being found with: drush_makefile_path: "{{ config_dir }}/drupal.make.yml". But I will verify.

**Comment by thom8** [comment] 2017-04-27 10:26
@dev-dev00 you might be onto something - not sure where `playbook_dir` is set, but would assume `config_dir` defaults to `/..`

https://github.com/geerlingguy/drupal-vm/blob/bd6ba6924dc0b2d783de839e548b032d32021d59/provisioning/tasks/config.yml#L7

**Comment by dev-dev00** [comment] 2017-04-27 10:34
This is the error when setting drush_makefile_path: "{{ config_dir }}/drupal.make.yml".
![error](https://cloud.githubusercontent.com/assets/28093956/25479607/1a9e88fe-2b0b-11e7-901a-8fad46be57e0.png)

**Comment by thom8** [comment] 2017-04-27 10:41
can you try `vagrant destroy -f && vagrant up` -- also do you have any extra vagrant plugins?

`vagrant plugin list`

**Comment by dev-dev00** [comment] 2017-04-27 10:43
plugin list: vagrant-share (1.1.7, system)

**Comment by dev-dev00** [comment] 2017-04-27 11:17
It appears the same error is occurring after vagrant destroy -f && vagrant up.
![error 2](https://cloud.githubusercontent.com/assets/28093956/25481086/32a9aefa-2b11-11e7-83c5-eb8e11ec0d58.png)

**Comment by thom8** [comment] 2017-04-27 11:22
I'm a bit stuck then sorry, only thing I could suggest is trying -- https://github.com/thom8/drupal8-vagrant#drupal-7 to check it the issue is related to DrupalVM or your Vagrant config.

**Comment by dev-dev00** [comment] 2017-04-27 11:26
I will double check that. 

Attached is the complete terminal output from the last vagrant up. 
[error complete.pdf](https://github.com/geerlingguy/drupal-vm/files/961413/error.complete.pdf)

**Comment by oxyc** [comment] 2017-04-27 11:34
> not sure where playbook_dir is set, but would assume config_dir defaults to /..

Correct, it's set by ansible to the playbook base directory. http://docs.ansible.com/ansible/playbooks_variables.html

Wonder if it's something with your host python environment.

Could you try updating your python version? At least you're using 2.7.10 (2015) while I have 2.7.13 (2016). This is my version for reference

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by dev-dev00** [comment] 2017-04-27 13:43
Can confirm that I updated python. 
It did fix the error message received previously when utilizing the default code of:
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"

But, it still loads D8

**Comment by oxyc** [comment] 2017-04-27 18:14
Did you delete the previously generated drupal codebase from your host machine? `vagrant destroy` will not delete the `drupal/` directory, you have to do it manually. https://github.com/geerlingguy/drupal-vm/issues/1046#issuecomment-266335495

**Comment by dev-dev00** [comment] 2017-04-27 20:35
@oxyc Good call.  That did it. Drupal 7 works now!

**Comment by dev-dev00** [comment] 2017-04-27 21:32
Drupal 7 and PHP 5.6 configuration instructions:
Mac OS X El Capitan, Version 10.11.6
Requirements: Python 2.7.13

[DrupalVM Ubuntu 16_04 Instructions.pdf](https://github.com/geerlingguy/drupal-vm/files/962985/DrupalVM.Ubuntu.16_04.Instructions.pdf)

**Comment by thom8** [comment] 2017-04-30 00:31
@dev-dev00 did you manage to get it all sorted?

**Comment by dev-dev00** [comment] 2017-05-01 18:42
Yes, 


Thank you all again for the help. 
Seems like the python upgrade and clearing the Drupal folder between builds did the trick.

**Comment by geerlingguy** [comment] 2017-05-01 20:01
Great! Closing the issue in that case.

**Closed by geerlingguy** 2017-05-01 20:01 UTC
Labels: question
