### ISSUE TITLE
Provision Failing on "Configure hostname."

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#1445] opened 2017-06-23 14:09 UTC
### Issue Type

Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

Mac OS Sierra

### Console output

```
TASK [Configure hostname.] *****************************************************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "Failed to get information on remote file (/etc/hostname): MODULE FAILURE"}
	to retry, use: --limit @/Users/mjarrell/Sites/drupal-vm/provisioning/playbook.retry
```

### Config

https://gist.github.com/attheshow/c8f8cb2a932c68e254557172d5d0b125

### Summary

I'm just setting up Drupal VM on a new Mac and downloaded the latest versions of VirtualBox and Vagrant. I'm still using the same config.yml that I have been (see link above) and still using DrupalVM version 4.4.5 at the moment. Any ideas what might be going wrong with the hostname? I'm not seeing any other issues in the issue queue related to this. Thanks!

**Comment by geerlingguy** [comment] 2017-06-23 15:28
That's strange... seems like it could be a networking issue maybe?

If you run `vagrant ssh` to log in, then `ls -lah /etc/hostname`, what do you get?

**Comment by attheshow** [comment] 2017-06-23 15:30
```
vagrant@drupalvm:~$ ls -lah /etc/hostname
-rw-r--r-- 1 root root 9 Jun 23 15:07 /etc/hostname
```

**Comment by geerlingguy** [comment] 2017-06-23 15:33
So it's definitely there... and if you run `vagrant provision` again, can you provide the full output? up to and including the error message?

And finally, maybe try updating Ansible to 2.3.1?

**Comment by attheshow** [comment] 2017-06-23 15:35
OK, here's the output.

https://gist.github.com/attheshow/cd434e826dca01c1e35725339d7b6d4a

Updating ansible now.

**Comment by attheshow** [comment] 2017-06-23 15:42
Apparently pip wasn't installing that version by default. It was doing version 2.2.2.0 for some reason. I had to specify the version to get to 2.3.1 like so:

```
sudo pip install -Iv ansible==2.3.1
```
That worked to get it update. After that I tried `vagrant provision` again and it's made it past the hostname issue above. Hopefully it will finish up now. Thanks so much!

**Comment by oxyc** [comment] 2017-06-23 19:46
As we dont have Ansible 2.3 as a requirement yet this should be fixed though. I'll look into it during the weekend.

**Comment by oxyc** [comment] 2017-06-23 22:43
Unfortunately I cant reproduce this.

I used your `config.yml` and tested Ansible 2.2.2.0 with
- Python 2.7.10 (the default on macOS sierra)
- Python 2.7.13 (the latest when installed with homebrew)

Neither failed on the hostname task. Not sure what could have caused it.

**Comment by oxyc** [comment] 2017-06-24 00:11
I'll close this again as you did get it working and i'm not able to reproduce it. If more issues start popping up with Ansible 2.2 I guess we have to look into it further.

**Closed by oxyc** 2017-06-24 00:11 UTC
Labels: question
