### ISSUE TITLE
MySQL errors on vagrant up

### ISSUE THREAD

**Issue by ogs22** [geerlingguy/drupal-vm#95] opened 2015-05-11 14:53 UTC
## Original Issue

I'm seeing on vagrant up:

```
TASK: [geerlingguy.mysql | Ensure MySQL users are present.] ******************* 
failed: [drupaldev] => (item={'host': '%', 'password': u'drupal', 'name': u'drupal', 'priv': u'drupal.*:ALL'}) => {"failed": true, "item": {"host": "%", "name": "drupal", "password": "drupal", "priv": "drupal.*:ALL"}}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

FATAL: all hosts have already failed -- aborting

```

## Current Workarounds

If this is happening to you, please try one of the following:

  1. Run `vagrant reload --provision` to restart and re-provision Drupal VM.
  2. Run `vagrant destroy -f && vagrant up` to completely destroy and rebuild Drupal VM.
  3. Run `sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo pip install -U`.
  4. Make sure you're running the current stable releases of both Vagrant (e.g. 1.7.2) and Ansible (e.g. 1.9.1).

**Comment by ogs22** [comment] 2015-05-11 15:03
/root/.my.cnf does exist and mysql is running. but there's no drupal user in the mysql user table.

**Comment by geerlingguy** [comment] 2015-05-11 18:23
@ogs22 - If you start with a clean VM (e.g. `vagrant destroy -f` to destroy the entire VM, then `vagrant up` fresh), does this error still exist?

There's a possibility you have an outdated version of the `geerlingguy.mysql` role too; can you also run `ansible-galaxy install --force geerlingguy.mysql` to make sure you have the latest version (which should be able to update passwords a little more correctly).

**Comment by ogs22** [comment] 2015-05-12 09:01
@geerlingguy no luck, even after force reinstalling geerlingguy.mysql I get the same error on vagrant up.

**Comment by geerlingguy** [comment] 2015-05-12 15:51
@ogs22 - Can you paste in all the `mysql_*` variables in your `config.yml` file (except for any sensitive info, of course)? With the defaults, everything should just work.

And, even though this *shouldn't* make a difference—what kind of OS are you using for the host, and what's the output of `vagrant --version` and `ansible --version`?

**Comment by ogs22** [comment] 2015-05-12 15:55
@geerlingguy I get the error using the default config files.

Host is OS X Yosemite‎, I'll post vagrant/ansible version next time I'm near the Mac.

**Comment by davidlukac** [comment] 2015-05-12 18:50
I've had the same error when I made any modification to `config.yml` and/or `drupal.make.yml`, install went through when I reverted them back to original. I've modified the _config_ files afterwards and installed the VM successfully, so I'm really not sure what the issue was :-/. I made sure though that _yaml_ files are valid using http://www.yamllint.com/.

_I'm on MacPro Yosemite 10.10.3._

**Comment by davidlukac** [comment] 2015-05-13 06:34
Hm, at some point I downgraded to 1.8.1. @ogs22 maybe start from scratch there, we default config to see if the issue remains? I'll try to replicate the issue again but probably won't get to is today; tomorrow perhaps.

@geerlingguy: Consider adding version number to e.g. CHANGELOG.md - someone in the office had older running version (when we were trying to resolve the same ^ issue), but we couldn't easily figure out what version it was ;-).

**Comment by ogs22** [comment] 2015-05-13 12:00
I'm on Vagrant 1.7.2 and Ansible 2.0.0
```
git clone https://github.com/geerlingguy/drupal-vm.git
cd drupal-vm
cp example.config.yml config.yml
cp example.drupal.make.yml drupal.make.yml
sudo ansible-galaxy install --force -r requirements.txt
vagrant up
```

Yields the same error
Not usre this is any help but if I increase the ansible verboseness I get
```
TASK: [geerlingguy.mysql | Ensure MySQL users are present.] ******************* 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE mysql_user name=drupal host=% password=VALUE_HIDDEN state=present priv='drupal.*:ALL'
<127.0.0.1> EXEC ssh -C -tt -v -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/ogs22/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/ogs22/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888 && echo $HOME/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888'
<127.0.0.1> PUT /var/folders/ld/lc22sjcs5bx66fjbxw5m69b80000gn/T/tmpBr7vuz TO /home/vagrant/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888/mysql_user
<127.0.0.1> EXEC ssh -C -tt -v -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/ogs22/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/ogs22/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jdaopktfshbapwrrqmfmydacvvcbxwot] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jdaopktfshbapwrrqmfmydacvvcbxwot; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888/mysql_user; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1431517109.65-156956443596888/ >/dev/null 2>&1'"'"''
failed: [drupaldev] => (item={'host': '%', 'password': u'drupal', 'name': u'drupal', 'priv': u'drupal.*:ALL'}) => {"failed": true, "item": {"host": "%", "name": "drupal", "password": "drupal", "priv": "drupal.*:ALL"}}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
```

**Comment by geerlingguy** [comment] 2015-05-13 14:05
@ogs22 - One more thing to try really quick; can you log into the machine with `vagrant ssh` and then do a `sudo cat /root/.my.cnf`, and also `cat ~/.my.cnf` and make sure it has the right information inside (MySQL root password)?

I'm still able to build the VM successfully on my Mac and on a Windows 7 machine using the default config.yml settings with no issue. It could be there's a bug with the mysql module in Ansible 2.0.0—could you try downgrading your Ansible to 1.9.1?

**Comment by ogs22** [comment] 2015-05-13 15:22
Away from the mac now but /root/.my.cnf looked fine - there wasn't a ~/.my.cnf though.

**Comment by davidlukac** [comment] 2015-05-14 09:13
Yesterday I've encountered this problem again, on my previously perfectly running VM.

I got:

```
TASK: [geerlingguy.mysql | Get list of hosts for the root user.] **************
failed: [drupaldev] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"root\" ORDER BY (Host=\"localhost\") ASC"], "delta": "0:00:00.003632", "end": "2015-05-13 08:30:41.153211", "rc": 1, "start": "2015-05-13 08:30:41.149579", "stdout_lines": [], "warnings": []}
stderr: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/davidlukac/playbook.retry

drupaldev                  : ok=115  changed=49   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

We seem to encounter this problem randomly across devs using the VM in the office.

`vagrant halt` -> `vagrant up` -> `vagrant provision` worked to revive it. It's a bit annoying though :-\.

**Comment by ogs22** [comment] 2015-05-14 12:00
I uninstalled ansible 2.0.0 upgraded all my other python packages and installed ansible 1.9.1 and everything is working as it should now.

Thanks

**Comment by davidlukac** [comment] 2015-05-14 13:48
@ogs22 thanks for letting know!

**Comment by kalabro** [comment] 2015-05-15 16:46
I have the same problem with Vagrant 1.7.2 and ansible 1.9.1.

> `vagrant halt` -> `vagrant up` -> `vagrant provision` worked to revive it. It's a bit annoying though :-.

This doesn't help.

> - there wasn't a ~/.my.cnf though.

The same here.

**Comment by geerlingguy** [comment] 2015-05-16 01:14
@kalabro - thanks for the info—I'm going to reopen this and try to reproduce. I still can't after building and rebuilding the VM a few different ways... but I'll persist!

**Comment by Elfiggo** [comment] 2015-05-18 12:17
I ran this to update the python packages and it seemed to come to life again

```sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U```

Using ansible 1.9.1 and homebrew.

**Comment by davidlukac** [comment] 2015-05-26 09:55
Slight variation of the command above @karolkasas used & spun up the VM successfully afterwards:

`sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo pip install -U`

**Comment by geerlingguy** [comment] 2015-05-26 15:17
Very strange... It seems like it could be related to some different pip-installed versions of the tools you're using, or Ansible versions, etc.

I usually just stick with the latest stable release (currently Ansible 1.9.1, Vagrant 1.7.2), so if you do the same, you'll probably have more success ;-)

If I get some time, I'm going to try some other versions of Ansible (dev, 1.8.x, etc.) and see if I can reproduce the issue.

**Comment by theneonlobster** [comment] 2015-05-26 19:45
I have Ansible 1.9.1 and Vagrant 1.7.2 installed via Homebrew and am having the same issue.

**Comment by geerlingguy** [comment] 2015-05-26 19:54
@theneonlobster - If you run `sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo pip install -U`, then try again, does it work? Maybe some pip dependency is out of date in the local env.

**Comment by theneonlobster** [comment] 2015-05-26 20:03
@geerlingguy - That did not fix the problem. :(

**Comment by geerlingguy** [comment] 2015-05-26 20:07
@theneonlobster - Can you try running `vagrant reload --provision` and see if that fixes it?

**Comment by theneonlobster** [comment] 2015-05-26 20:13
Not exactly; after posting https://github.com/geerlingguy/drupal-vm/issues/95#issuecomment-105650044 I destroyed the machine and then rebuilt and voila!

**Comment by geerlingguy** [comment] 2015-05-26 20:18
@theneonlobster - Well, there's always that nuclear option :P

I'm going to add a summary to the OP on this issue with some suggested solutions and ideas... hopefully we can get to the bottom of this, but for now, a couple ways to solve:

  1. Run `vagrant reload --provision`.
  2. Run `sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo pip install -U`.
  3. Make sure you're running the current stable releases of both Vagrant (e.g. 1.7.2) and Ansible (e.g. 1.9.1).

**Comment by los-dwarf** [comment] 2015-06-06 14:42
I had the same problem on my work machine, but not on my home machine running identical setups.
I found that the only difference was the installed version of Ansible. 
After downgrading to 1.9.0.1 on my work machine, the problem went away.

Hope this helps.

**Comment by geerlingguy** [comment] 2015-06-18 05:10
@los-dwarf - Thanks for that tidbit! It definitely seems to be related to the version of Ansible installed (at least, for the majority of people who have had this issue)—so I'm hoping this issue just 'goes away' as the next releases of Ansible start getting into all the various distribution channels. I know homebrew is often a point release or two behind :/

Closing this ticket, but please feel free to continue adding to the discussion.

**Closed by geerlingguy** 2015-06-18 05:10 UTC
Labels: question

**Comment by geerlingguy** [comment] 2015-06-19 19:43
See related: https://github.com/geerlingguy/ansible-role-mysql/issues/40
