### ISSUE TITLE
Vagrant is not yet compatible with guest-installed Ansible 2.x

### ISSUE THREAD

**Issue by artemkolotilkin** [geerlingguy/drupal-vm#372] opened 2016-01-13 18:04 UTC
## Problem

Drupal VM 2.2.0+ uses the new `ansible_local` provisioner provided by Vagrant. This worked great with Ansible 1.9.x, which was current at the time, but after Ansible 2.0.0 was released, Vagrant's `ansible_local` integration was broken. There are two bugs causing the issue:

  - https://github.com/mitchellh/vagrant/issues/6793
  - https://github.com/mitchellh/vagrant/issues/6757

The next release of Vagrant (1.8.2) will contain fixes for both of the above bugs, and when that release is public this issue will be closed. For now, if you'd like to use the latest version of Drupal VM, you can apply the patches from the two issues above locally, and that will at least get you a working VM!

## Original Issue

When I try to provision a new box I get:
```
vagrant provision
==> dev: Checking for host entries
==> dev: Running provisioner: ansible_local...
The Ansible software could not be found! Please verify that Ansible is correctly installed on your guest system.

If you haven't installed Ansible yet, please install Ansible on your Vagrant basebox, or enable the automated setup with the `install` option of this provisioner. Please check https://docs.vagrantup.com/v2/provisioning/ansible_local.html for more information.
```

If I SSH to the box though, I can see ansible installed there:
```
vagrant@dev:~$ ansible --version
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Seems that Vagrant fails to identify and use a new version of Ansible.

**Comment by geerlingguy** [comment] 2016-01-13 18:10
Are you on Windows or another OS? Also, this might be an upstream issue with Vagrant not being able to identify Ansible 2.x (which was just released yesterday) as a valid provisioner.

**Comment by geerlingguy** [comment] 2016-01-13 18:11
Here's the bug report: https://github.com/mitchellh/vagrant/issues/6793

For now, I'd recommend sticking to the previous point release of Drupal VM until that issue gets worked out.

**Comment by artemkolotilkin** [comment] 2016-01-13 18:59
Thanks, I installed Ansible on my host machine and it worked fine.

**Comment by itsgreggmarshall** [comment] 2016-01-20 00:25
Just to clarify (having tried master, then 2.2.0, and then finally 2.1.2) 

2.1.2 appears to be the point release to use on Windows 7 to get past this issue.

**Comment by geerlingguy** [comment] 2016-01-20 00:57
@itsgreggmarshall - Yeah, I was considering holding off on releasing 2.2.0, because it's an upstream bug. I hope Vagrant 1.8.2 is released soon, it will help with this project and many others!

**Comment by itsgreggmarshall** [comment] 2016-01-25 16:20
@geerlingguy I am trying 2.2.1 on Windows and it appears to be trying to use ansible_local, which doesn't work.  Do I need to upgrade Vagrant higher than 1.8.1?


     ==> drupalvm: Running provisioner: ansible_local...
        drupalvm: Installing Ansible...
     The Ansible software could not be found! Please verify
     that Ansible is correctly installed on your guest system.

     If you haven't installed Ansible yet, please install Ansible
     on your Vagrant basebox, or enable the automated setup with the
     `install` option of this provisioner. Please check
     https://docs.vagrantup.com/v2/provisioning/ansible_local.html
     for more information.

**Comment by geerlingguy** [comment] 2016-01-25 16:23
@itsgreggmarshall - yes, unfortunately Vagrant 1.8.1 doesn't have the patch to fix this bug, and 1.8.2 hasn't been released yet—see https://github.com/mitchellh/vagrant/issues/6793, and if you want to patch 1.8.1, you can do so with this patch: https://github.com/mitchellh/vagrant/commit/9dbdb9397a92d4fc489e9afcb022621df7f60d11

**Comment by itsgreggmarshall** [comment] 2016-01-25 17:00
That patch got me further, but now I'm getting

      drupalvm: Running ansible-galaxy...
      [ERROR]: Unable to open C:/vagrant/provisioning/requirements.yml: [Errno 2] No
      such file or directory: 'C:/vagrant/provisioning/requirements.yml'
      drupalvm: Running ansible-playbook...
      ERROR! the role 'geerlingguy.repo-remi' was not found in /vagrant/provisioning/roles:/vagrant/provisioning:/etc/ansible/roles

     The error appears to have been in '/vagrant/provisioning/playbook.yml': line 21, column 7, but may
      be elsewhere in the file depending on the exact syntax problem.

      The offending line appears to be:

         # Essential roles.
         - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
           ^ here

      Ansible failed to complete successfully. Any error output should be
      visible above. Please fix these errors and try again.

**Comment by itsgreggmarshall** [comment] 2016-01-25 17:09
Looking around it appears the C:/vagrant/provisioning/requirements.yml should be C:/drupal-vm/provisioning/requirements.yml?

**Comment by oxyc** [comment] 2016-01-25 17:15
Sounds like it could be caused by https://github.com/mitchellh/vagrant/issues/6757

This is another fix scheduled for 1.8.2

**Comment by geerlingguy** [comment] 2016-01-25 17:28
Augh! 1.8.2. can't come soon enough...

**Comment by itsgreggmarshall** [comment] 2016-01-25 21:08
Thanks @oxyc 

That got me past this problem, and it actually built a VM that shows a Drupal site!!!!

I'm excited. 

And thanks @geerlingguy for your patience during this.

**Comment by geerlingguy** [comment] 2016-01-25 21:37
@itsgreggmarshall - It's no problem! You just chose possibly the worst couple weeks ever to try getting things set up—at the beginning of the year I was tracking bugs in Vagrant 1.8.x, Ansible 2.x, and VirtualBox 5.0.x... all causing funky issues on Windows. Now at least the only major problem is caused by Vagrant, so it's a lot easier to handle, and once 1.8.2 is released, all the major pain points should be gone :)

**Comment by geerlingguy** [comment] 2016-02-19 03:11
See #450 - I'm closing this ticket as Drupal VM has, for the time being, switched back to using [JJG-Ansible-Windows](https://github.com/geerlingguy/JJG-Ansible-Windows), so local provisioning inside Windows or any environment without Ansible installed on the host will work normally.

**Closed by geerlingguy** 2016-02-19 03:11 UTC
Labels: upstream
