### ISSUE TITLE
Simpletest can't remove its .htaccess files or directories

### ISSUE THREAD

**Issue by kdmcguire** [geerlingguy/drupal-vm#1793] opened 2018-06-27 12:34 UTC
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
Virtualbox 5.2.8 r121009 (Qt5.6.2)
```
Ansible not installed on host.

### Your OS

 - **Windows** version 1709, build 16299.492

### Summary

File directory mapping config:

```
  - local_path: ~/sites/drupal-vm/website-dir
    destination: /var/www/drupalvm
    type: ""
    create: true
    mount_options: ["dmode=775", "fmode=664"]
    options_override:
      owner: "vagrant"
      group: "www-data"

  - local_path: ~/sites/private
    destination: /var/www/private
    type: ""
    create: true
    mount_options: ["dmode=775", "fmode=664"]
    options_override:
      owner: "vagrant"
      group: "www-data"
```

When running Simpletest tests, the tests always end with exceptions saying that they cannot unlink the .htaccess files or directories generated by the tests, and thus cannot rmdir the directories because they're not empty.

dblog entries in the order that they appeared:

```
Warning: unlink(/var/www/drupalvm/sites/default/files/simpletest/537781/.htaccess): Operation not permitted in drupal_unlink() (line 2308 of /var/www/drupalvm/includes/file.inc).

Warning: unlink(/var/www/drupalvm/sites/default/files/simpletest/537781/private/.htaccess): Operation not permitted in drupal_unlink() (line 2308 of /var/www/drupalvm/includes/file.inc).

Warning: unlink(/var/www/drupalvm/sites/default/files/simpletest/537781/private/temp/.htaccess): Operation not permitted in drupal_unlink() (line 2308 of /var/www/drupalvm/includes/file.inc).

Warning: rmdir(/var/www/drupalvm/sites/default/files/simpletest/537781/private/temp): Directory not empty in drupal_rmdir() (line 2472 of /var/www/drupalvm/includes/file.inc).

Warning: rmdir(/var/www/drupalvm/sites/default/files/simpletest/537781/private): Directory not empty in drupal_rmdir() (line 2472 of /var/www/drupalvm/includes/file.inc).

Warning: rmdir(/var/www/drupalvm/sites/default/files/simpletest/537781): Directory not empty in drupal_rmdir() (line 2472 of /var/www/drupalvm/includes/file.inc).
```

When SSH'd into the machine, I cannot change or remove the .htaccess files - I get an "operation not permitted" response, even when using sudo.

I've tried numerous patches from d.o but none have resolved it.

Happy to provide more info but might need instructions!

**Comment by kdmcguire** [comment] 2018-06-28 13:49
Looks like Simpletest can remove _public_ files/directories, as tests that don't involve private files don't get this issue.

**Comment by geerlingguy** [comment] 2018-08-14 19:10
Interesting, I haven't ever tried doing anything with the private filesystem in simpletest.

**Comment by geerlingguy** [comment] 2018-12-28 23:33
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!

**Comment by geerlingguy** [comment] 2018-12-28 23:33
But regardless, in this particular case, since I don't have any projects which use private filesystems, I would not be of much assistance. If you can open a new issue with some steps to reproduce (e.g. build this project or clone that project, then run this and that command...), we could take a deeper look.

**Closed by geerlingguy** 2018-12-28 23:33 UTC
Labels: question
